// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module uniform_move_operation_tree_sum_2_s (
        ap_ready,
        x_0_val,
        x_1_val,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [8:0] x_0_val;
input  [8:0] x_1_val;
output  [8:0] ap_return;
input   ap_rst;

wire    agg_result_tree_sum_1_s_fu_34_ap_ready;
wire   [8:0] agg_result_tree_sum_1_s_fu_34_x_val;
wire   [8:0] agg_result_tree_sum_1_s_fu_34_ap_return;
wire  signed [8:0] sext_ln90_fu_39_p0;
wire  signed [8:0] sext_ln90_47_fu_43_p0;
wire  signed [8:0] add_ln90_fu_47_p0;
wire  signed [8:0] add_ln90_fu_47_p1;
wire  signed [9:0] sext_ln90_47_fu_43_p1;
wire  signed [9:0] sext_ln90_fu_39_p1;
wire   [9:0] add_ln90_47_fu_53_p2;
wire   [8:0] add_ln90_fu_47_p2;
wire   [0:0] tmp_fu_59_p3;
wire   [0:0] tmp_48_fu_67_p3;
wire   [0:0] xor_ln90_fu_75_p2;
wire   [0:0] and_ln90_fu_81_p2;
wire   [0:0] xor_ln90_47_fu_87_p2;
wire   [8:0] select_ln90_fu_93_p3;

uniform_move_operation_tree_sum_1_s agg_result_tree_sum_1_s_fu_34(
    .ap_ready(agg_result_tree_sum_1_s_fu_34_ap_ready),
    .x_val(agg_result_tree_sum_1_s_fu_34_x_val),
    .ap_return(agg_result_tree_sum_1_s_fu_34_ap_return),
    .ap_rst(ap_rst)
);

assign add_ln90_47_fu_53_p2 = ($signed(sext_ln90_47_fu_43_p1) + $signed(sext_ln90_fu_39_p1));

assign add_ln90_fu_47_p2 = ($signed(add_ln90_fu_47_p0) + $signed(add_ln90_fu_47_p1));

assign and_ln90_fu_81_p2 = (xor_ln90_fu_75_p2 & tmp_48_fu_67_p3);

assign ap_ready = 1'b1;

assign select_ln90_fu_93_p3 = ((and_ln90_fu_81_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign sext_ln90_47_fu_43_p1 = sext_ln90_47_fu_43_p0;

assign sext_ln90_fu_39_p1 = sext_ln90_fu_39_p0;

assign tmp_48_fu_67_p3 = add_ln90_fu_47_p2[32'd8];

assign tmp_fu_59_p3 = add_ln90_47_fu_53_p2[32'd9];

assign xor_ln90_47_fu_87_p2 = (tmp_fu_59_p3 ^ tmp_48_fu_67_p3);

assign xor_ln90_fu_75_p2 = (tmp_fu_59_p3 ^ 1'd1);

assign add_ln90_fu_47_p0 = x_1_val;

assign add_ln90_fu_47_p1 = x_0_val;

assign agg_result_tree_sum_1_s_fu_34_x_val = ((xor_ln90_47_fu_87_p2[0:0] == 1'b1) ? select_ln90_fu_93_p3 : add_ln90_fu_47_p2);

assign ap_return = agg_result_tree_sum_1_s_fu_34_ap_return;

assign sext_ln90_47_fu_43_p0 = x_1_val;

assign sext_ln90_fu_39_p0 = x_0_val;

endmodule //uniform_move_operation_tree_sum_2_s
