// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module uniform_move_operation_tree_sum_36_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_0_val,
        x_1_val,
        x_2_val,
        x_3_val,
        x_4_val,
        x_5_val,
        x_6_val,
        x_7_val,
        x_8_val,
        x_9_val,
        x_10_val,
        x_11_val,
        x_12_val,
        x_13_val,
        x_14_val,
        x_15_val,
        x_16_val,
        x_17_val,
        x_18_val,
        x_19_val,
        x_20_val,
        x_21_val,
        x_22_val,
        x_23_val,
        x_24_val,
        x_25_val,
        x_26_val,
        x_27_val,
        x_28_val,
        x_29_val,
        x_30_val,
        x_31_val,
        x_32_val,
        x_33_val,
        x_34_val,
        x_35_val,
        ap_return
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] x_0_val;
input  [8:0] x_1_val;
input  [8:0] x_2_val;
input  [8:0] x_3_val;
input  [8:0] x_4_val;
input  [8:0] x_5_val;
input  [8:0] x_6_val;
input  [8:0] x_7_val;
input  [8:0] x_8_val;
input  [8:0] x_9_val;
input  [8:0] x_10_val;
input  [8:0] x_11_val;
input  [8:0] x_12_val;
input  [8:0] x_13_val;
input  [8:0] x_14_val;
input  [8:0] x_15_val;
input  [8:0] x_16_val;
input  [8:0] x_17_val;
input  [8:0] x_18_val;
input  [8:0] x_19_val;
input  [8:0] x_20_val;
input  [8:0] x_21_val;
input  [8:0] x_22_val;
input  [8:0] x_23_val;
input  [8:0] x_24_val;
input  [8:0] x_25_val;
input  [8:0] x_26_val;
input  [8:0] x_27_val;
input  [8:0] x_28_val;
input  [8:0] x_29_val;
input  [8:0] x_30_val;
input  [8:0] x_31_val;
input  [8:0] x_32_val;
input  [8:0] x_33_val;
input  [8:0] x_34_val;
input  [8:0] x_35_val;
output  [8:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[8:0] ap_return;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [8:0] y_fu_390_p3;
reg   [8:0] y_reg_1606;
wire   [8:0] y_5_fu_461_p3;
reg   [8:0] y_5_reg_1611;
wire   [8:0] y_6_fu_532_p3;
reg   [8:0] y_6_reg_1616;
wire   [8:0] y_7_fu_603_p3;
reg   [8:0] y_7_reg_1621;
wire   [8:0] y_8_fu_674_p3;
reg   [8:0] y_8_reg_1626;
wire   [8:0] y_9_fu_745_p3;
reg   [8:0] y_9_reg_1631;
wire   [8:0] y_10_fu_816_p3;
reg   [8:0] y_10_reg_1636;
wire   [8:0] y_11_fu_887_p3;
reg   [8:0] y_11_reg_1641;
wire   [8:0] y_12_fu_958_p3;
reg   [8:0] y_12_reg_1646;
wire   [8:0] y_13_fu_1029_p3;
reg   [8:0] y_13_reg_1651;
wire   [8:0] y_14_fu_1100_p3;
reg   [8:0] y_14_reg_1656;
wire   [8:0] y_15_fu_1171_p3;
reg   [8:0] y_15_reg_1661;
wire   [8:0] y_16_fu_1242_p3;
reg   [8:0] y_16_reg_1666;
wire   [8:0] y_17_fu_1313_p3;
reg   [8:0] y_17_reg_1671;
wire   [8:0] y_18_fu_1384_p3;
reg   [8:0] y_18_reg_1676;
wire   [8:0] y_19_fu_1455_p3;
reg   [8:0] y_19_reg_1681;
wire   [8:0] y_20_fu_1526_p3;
reg   [8:0] y_20_reg_1686;
wire   [8:0] y_21_fu_1597_p3;
reg   [8:0] y_21_reg_1691;
wire    grp_tree_sum_18_s_fu_306_ap_start;
wire    grp_tree_sum_18_s_fu_306_ap_done;
wire    grp_tree_sum_18_s_fu_306_ap_idle;
wire    grp_tree_sum_18_s_fu_306_ap_ready;
wire   [8:0] grp_tree_sum_18_s_fu_306_ap_return;
reg    grp_tree_sum_18_s_fu_306_ap_start_reg;
wire    ap_CS_fsm_state2;
wire  signed [8:0] sext_ln90_fu_328_p0;
wire  signed [8:0] sext_ln90_12_fu_332_p0;
wire  signed [8:0] add_ln90_fu_336_p0;
wire  signed [8:0] add_ln90_fu_336_p1;
wire  signed [9:0] sext_ln90_12_fu_332_p1;
wire  signed [9:0] sext_ln90_fu_328_p1;
wire   [9:0] add_ln90_12_fu_342_p2;
wire   [8:0] add_ln90_fu_336_p2;
wire   [0:0] tmp_fu_348_p3;
wire   [0:0] tmp_13_fu_356_p3;
wire   [0:0] xor_ln90_fu_364_p2;
wire   [0:0] and_ln90_fu_370_p2;
wire   [0:0] xor_ln90_12_fu_376_p2;
wire   [8:0] select_ln90_fu_382_p3;
wire  signed [8:0] sext_ln90_13_fu_399_p0;
wire  signed [8:0] sext_ln90_14_fu_403_p0;
wire  signed [8:0] add_ln90_13_fu_407_p0;
wire  signed [8:0] add_ln90_13_fu_407_p1;
wire  signed [9:0] sext_ln90_14_fu_403_p1;
wire  signed [9:0] sext_ln90_13_fu_399_p1;
wire   [9:0] add_ln90_14_fu_413_p2;
wire   [8:0] add_ln90_13_fu_407_p2;
wire   [0:0] tmp_14_fu_419_p3;
wire   [0:0] tmp_15_fu_427_p3;
wire   [0:0] xor_ln90_13_fu_435_p2;
wire   [0:0] and_ln90_5_fu_441_p2;
wire   [0:0] xor_ln90_14_fu_447_p2;
wire   [8:0] select_ln90_13_fu_453_p3;
wire  signed [8:0] sext_ln90_15_fu_470_p0;
wire  signed [8:0] sext_ln90_16_fu_474_p0;
wire  signed [8:0] add_ln90_15_fu_478_p0;
wire  signed [8:0] add_ln90_15_fu_478_p1;
wire  signed [9:0] sext_ln90_16_fu_474_p1;
wire  signed [9:0] sext_ln90_15_fu_470_p1;
wire   [9:0] add_ln90_16_fu_484_p2;
wire   [8:0] add_ln90_15_fu_478_p2;
wire   [0:0] tmp_16_fu_490_p3;
wire   [0:0] tmp_17_fu_498_p3;
wire   [0:0] xor_ln90_15_fu_506_p2;
wire   [0:0] and_ln90_6_fu_512_p2;
wire   [0:0] xor_ln90_16_fu_518_p2;
wire   [8:0] select_ln90_15_fu_524_p3;
wire  signed [8:0] sext_ln90_17_fu_541_p0;
wire  signed [8:0] sext_ln90_18_fu_545_p0;
wire  signed [8:0] add_ln90_17_fu_549_p0;
wire  signed [8:0] add_ln90_17_fu_549_p1;
wire  signed [9:0] sext_ln90_18_fu_545_p1;
wire  signed [9:0] sext_ln90_17_fu_541_p1;
wire   [9:0] add_ln90_18_fu_555_p2;
wire   [8:0] add_ln90_17_fu_549_p2;
wire   [0:0] tmp_18_fu_561_p3;
wire   [0:0] tmp_19_fu_569_p3;
wire   [0:0] xor_ln90_17_fu_577_p2;
wire   [0:0] and_ln90_7_fu_583_p2;
wire   [0:0] xor_ln90_18_fu_589_p2;
wire   [8:0] select_ln90_17_fu_595_p3;
wire  signed [8:0] sext_ln90_19_fu_612_p0;
wire  signed [8:0] sext_ln90_20_fu_616_p0;
wire  signed [8:0] add_ln90_19_fu_620_p0;
wire  signed [8:0] add_ln90_19_fu_620_p1;
wire  signed [9:0] sext_ln90_20_fu_616_p1;
wire  signed [9:0] sext_ln90_19_fu_612_p1;
wire   [9:0] add_ln90_20_fu_626_p2;
wire   [8:0] add_ln90_19_fu_620_p2;
wire   [0:0] tmp_20_fu_632_p3;
wire   [0:0] tmp_21_fu_640_p3;
wire   [0:0] xor_ln90_19_fu_648_p2;
wire   [0:0] and_ln90_8_fu_654_p2;
wire   [0:0] xor_ln90_20_fu_660_p2;
wire   [8:0] select_ln90_19_fu_666_p3;
wire  signed [8:0] sext_ln90_21_fu_683_p0;
wire  signed [8:0] sext_ln90_22_fu_687_p0;
wire  signed [8:0] add_ln90_21_fu_691_p0;
wire  signed [8:0] add_ln90_21_fu_691_p1;
wire  signed [9:0] sext_ln90_22_fu_687_p1;
wire  signed [9:0] sext_ln90_21_fu_683_p1;
wire   [9:0] add_ln90_22_fu_697_p2;
wire   [8:0] add_ln90_21_fu_691_p2;
wire   [0:0] tmp_22_fu_703_p3;
wire   [0:0] tmp_23_fu_711_p3;
wire   [0:0] xor_ln90_21_fu_719_p2;
wire   [0:0] and_ln90_9_fu_725_p2;
wire   [0:0] xor_ln90_22_fu_731_p2;
wire   [8:0] select_ln90_21_fu_737_p3;
wire  signed [8:0] sext_ln90_23_fu_754_p0;
wire  signed [8:0] sext_ln90_24_fu_758_p0;
wire  signed [8:0] add_ln90_23_fu_762_p0;
wire  signed [8:0] add_ln90_23_fu_762_p1;
wire  signed [9:0] sext_ln90_24_fu_758_p1;
wire  signed [9:0] sext_ln90_23_fu_754_p1;
wire   [9:0] add_ln90_24_fu_768_p2;
wire   [8:0] add_ln90_23_fu_762_p2;
wire   [0:0] tmp_24_fu_774_p3;
wire   [0:0] tmp_25_fu_782_p3;
wire   [0:0] xor_ln90_23_fu_790_p2;
wire   [0:0] and_ln90_10_fu_796_p2;
wire   [0:0] xor_ln90_24_fu_802_p2;
wire   [8:0] select_ln90_23_fu_808_p3;
wire  signed [8:0] sext_ln90_25_fu_825_p0;
wire  signed [8:0] sext_ln90_26_fu_829_p0;
wire  signed [8:0] add_ln90_25_fu_833_p0;
wire  signed [8:0] add_ln90_25_fu_833_p1;
wire  signed [9:0] sext_ln90_26_fu_829_p1;
wire  signed [9:0] sext_ln90_25_fu_825_p1;
wire   [9:0] add_ln90_26_fu_839_p2;
wire   [8:0] add_ln90_25_fu_833_p2;
wire   [0:0] tmp_26_fu_845_p3;
wire   [0:0] tmp_27_fu_853_p3;
wire   [0:0] xor_ln90_25_fu_861_p2;
wire   [0:0] and_ln90_11_fu_867_p2;
wire   [0:0] xor_ln90_26_fu_873_p2;
wire   [8:0] select_ln90_25_fu_879_p3;
wire  signed [8:0] sext_ln90_27_fu_896_p0;
wire  signed [8:0] sext_ln90_28_fu_900_p0;
wire  signed [8:0] add_ln90_27_fu_904_p0;
wire  signed [8:0] add_ln90_27_fu_904_p1;
wire  signed [9:0] sext_ln90_28_fu_900_p1;
wire  signed [9:0] sext_ln90_27_fu_896_p1;
wire   [9:0] add_ln90_28_fu_910_p2;
wire   [8:0] add_ln90_27_fu_904_p2;
wire   [0:0] tmp_28_fu_916_p3;
wire   [0:0] tmp_29_fu_924_p3;
wire   [0:0] xor_ln90_27_fu_932_p2;
wire   [0:0] and_ln90_12_fu_938_p2;
wire   [0:0] xor_ln90_28_fu_944_p2;
wire   [8:0] select_ln90_27_fu_950_p3;
wire  signed [8:0] sext_ln90_29_fu_967_p0;
wire  signed [8:0] sext_ln90_30_fu_971_p0;
wire  signed [8:0] add_ln90_29_fu_975_p0;
wire  signed [8:0] add_ln90_29_fu_975_p1;
wire  signed [9:0] sext_ln90_30_fu_971_p1;
wire  signed [9:0] sext_ln90_29_fu_967_p1;
wire   [9:0] add_ln90_30_fu_981_p2;
wire   [8:0] add_ln90_29_fu_975_p2;
wire   [0:0] tmp_30_fu_987_p3;
wire   [0:0] tmp_31_fu_995_p3;
wire   [0:0] xor_ln90_29_fu_1003_p2;
wire   [0:0] and_ln90_13_fu_1009_p2;
wire   [0:0] xor_ln90_30_fu_1015_p2;
wire   [8:0] select_ln90_29_fu_1021_p3;
wire  signed [8:0] sext_ln90_31_fu_1038_p0;
wire  signed [8:0] sext_ln90_32_fu_1042_p0;
wire  signed [8:0] add_ln90_31_fu_1046_p0;
wire  signed [8:0] add_ln90_31_fu_1046_p1;
wire  signed [9:0] sext_ln90_32_fu_1042_p1;
wire  signed [9:0] sext_ln90_31_fu_1038_p1;
wire   [9:0] add_ln90_32_fu_1052_p2;
wire   [8:0] add_ln90_31_fu_1046_p2;
wire   [0:0] tmp_32_fu_1058_p3;
wire   [0:0] tmp_33_fu_1066_p3;
wire   [0:0] xor_ln90_31_fu_1074_p2;
wire   [0:0] and_ln90_14_fu_1080_p2;
wire   [0:0] xor_ln90_32_fu_1086_p2;
wire   [8:0] select_ln90_31_fu_1092_p3;
wire  signed [8:0] sext_ln90_33_fu_1109_p0;
wire  signed [8:0] sext_ln90_34_fu_1113_p0;
wire  signed [8:0] add_ln90_33_fu_1117_p0;
wire  signed [8:0] add_ln90_33_fu_1117_p1;
wire  signed [9:0] sext_ln90_34_fu_1113_p1;
wire  signed [9:0] sext_ln90_33_fu_1109_p1;
wire   [9:0] add_ln90_34_fu_1123_p2;
wire   [8:0] add_ln90_33_fu_1117_p2;
wire   [0:0] tmp_34_fu_1129_p3;
wire   [0:0] tmp_35_fu_1137_p3;
wire   [0:0] xor_ln90_33_fu_1145_p2;
wire   [0:0] and_ln90_15_fu_1151_p2;
wire   [0:0] xor_ln90_34_fu_1157_p2;
wire   [8:0] select_ln90_33_fu_1163_p3;
wire  signed [8:0] sext_ln90_35_fu_1180_p0;
wire  signed [8:0] sext_ln90_36_fu_1184_p0;
wire  signed [8:0] add_ln90_35_fu_1188_p0;
wire  signed [8:0] add_ln90_35_fu_1188_p1;
wire  signed [9:0] sext_ln90_36_fu_1184_p1;
wire  signed [9:0] sext_ln90_35_fu_1180_p1;
wire   [9:0] add_ln90_36_fu_1194_p2;
wire   [8:0] add_ln90_35_fu_1188_p2;
wire   [0:0] tmp_36_fu_1200_p3;
wire   [0:0] tmp_37_fu_1208_p3;
wire   [0:0] xor_ln90_35_fu_1216_p2;
wire   [0:0] and_ln90_16_fu_1222_p2;
wire   [0:0] xor_ln90_36_fu_1228_p2;
wire   [8:0] select_ln90_35_fu_1234_p3;
wire  signed [8:0] sext_ln90_37_fu_1251_p0;
wire  signed [8:0] sext_ln90_38_fu_1255_p0;
wire  signed [8:0] add_ln90_37_fu_1259_p0;
wire  signed [8:0] add_ln90_37_fu_1259_p1;
wire  signed [9:0] sext_ln90_38_fu_1255_p1;
wire  signed [9:0] sext_ln90_37_fu_1251_p1;
wire   [9:0] add_ln90_38_fu_1265_p2;
wire   [8:0] add_ln90_37_fu_1259_p2;
wire   [0:0] tmp_38_fu_1271_p3;
wire   [0:0] tmp_39_fu_1279_p3;
wire   [0:0] xor_ln90_37_fu_1287_p2;
wire   [0:0] and_ln90_17_fu_1293_p2;
wire   [0:0] xor_ln90_38_fu_1299_p2;
wire   [8:0] select_ln90_37_fu_1305_p3;
wire  signed [8:0] sext_ln90_39_fu_1322_p0;
wire  signed [8:0] sext_ln90_40_fu_1326_p0;
wire  signed [8:0] add_ln90_39_fu_1330_p0;
wire  signed [8:0] add_ln90_39_fu_1330_p1;
wire  signed [9:0] sext_ln90_40_fu_1326_p1;
wire  signed [9:0] sext_ln90_39_fu_1322_p1;
wire   [9:0] add_ln90_40_fu_1336_p2;
wire   [8:0] add_ln90_39_fu_1330_p2;
wire   [0:0] tmp_40_fu_1342_p3;
wire   [0:0] tmp_41_fu_1350_p3;
wire   [0:0] xor_ln90_39_fu_1358_p2;
wire   [0:0] and_ln90_18_fu_1364_p2;
wire   [0:0] xor_ln90_40_fu_1370_p2;
wire   [8:0] select_ln90_39_fu_1376_p3;
wire  signed [8:0] sext_ln90_41_fu_1393_p0;
wire  signed [8:0] sext_ln90_42_fu_1397_p0;
wire  signed [8:0] add_ln90_41_fu_1401_p0;
wire  signed [8:0] add_ln90_41_fu_1401_p1;
wire  signed [9:0] sext_ln90_42_fu_1397_p1;
wire  signed [9:0] sext_ln90_41_fu_1393_p1;
wire   [9:0] add_ln90_42_fu_1407_p2;
wire   [8:0] add_ln90_41_fu_1401_p2;
wire   [0:0] tmp_42_fu_1413_p3;
wire   [0:0] tmp_43_fu_1421_p3;
wire   [0:0] xor_ln90_41_fu_1429_p2;
wire   [0:0] and_ln90_19_fu_1435_p2;
wire   [0:0] xor_ln90_42_fu_1441_p2;
wire   [8:0] select_ln90_41_fu_1447_p3;
wire  signed [8:0] sext_ln90_43_fu_1464_p0;
wire  signed [8:0] sext_ln90_44_fu_1468_p0;
wire  signed [8:0] add_ln90_43_fu_1472_p0;
wire  signed [8:0] add_ln90_43_fu_1472_p1;
wire  signed [9:0] sext_ln90_44_fu_1468_p1;
wire  signed [9:0] sext_ln90_43_fu_1464_p1;
wire   [9:0] add_ln90_44_fu_1478_p2;
wire   [8:0] add_ln90_43_fu_1472_p2;
wire   [0:0] tmp_44_fu_1484_p3;
wire   [0:0] tmp_45_fu_1492_p3;
wire   [0:0] xor_ln90_43_fu_1500_p2;
wire   [0:0] and_ln90_20_fu_1506_p2;
wire   [0:0] xor_ln90_44_fu_1512_p2;
wire   [8:0] select_ln90_43_fu_1518_p3;
wire  signed [8:0] sext_ln90_45_fu_1535_p0;
wire  signed [8:0] sext_ln90_46_fu_1539_p0;
wire  signed [8:0] add_ln90_45_fu_1543_p0;
wire  signed [8:0] add_ln90_45_fu_1543_p1;
wire  signed [9:0] sext_ln90_46_fu_1539_p1;
wire  signed [9:0] sext_ln90_45_fu_1535_p1;
wire   [9:0] add_ln90_46_fu_1549_p2;
wire   [8:0] add_ln90_45_fu_1543_p2;
wire   [0:0] tmp_46_fu_1555_p3;
wire   [0:0] tmp_47_fu_1563_p3;
wire   [0:0] xor_ln90_45_fu_1571_p2;
wire   [0:0] and_ln90_21_fu_1577_p2;
wire   [0:0] xor_ln90_46_fu_1583_p2;
wire   [8:0] select_ln90_45_fu_1589_p3;
reg   [8:0] ap_return_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_tree_sum_18_s_fu_306_ap_start_reg = 1'b0;
#0 ap_return_preg = 9'd0;
end

uniform_move_operation_tree_sum_18_s grp_tree_sum_18_s_fu_306(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tree_sum_18_s_fu_306_ap_start),
    .ap_done(grp_tree_sum_18_s_fu_306_ap_done),
    .ap_idle(grp_tree_sum_18_s_fu_306_ap_idle),
    .ap_ready(grp_tree_sum_18_s_fu_306_ap_ready),
    .x_0_val(y_reg_1606),
    .x_1_val(y_5_reg_1611),
    .x_2_val(y_6_reg_1616),
    .x_3_val(y_7_reg_1621),
    .x_4_val(y_8_reg_1626),
    .x_5_val(y_9_reg_1631),
    .x_6_val(y_10_reg_1636),
    .x_7_val(y_11_reg_1641),
    .x_8_val(y_12_reg_1646),
    .x_9_val(y_13_reg_1651),
    .x_10_val(y_14_reg_1656),
    .x_11_val(y_15_reg_1661),
    .x_12_val(y_16_reg_1666),
    .x_13_val(y_17_reg_1671),
    .x_14_val(y_18_reg_1676),
    .x_15_val(y_19_reg_1681),
    .x_16_val(y_20_reg_1686),
    .x_17_val(y_21_reg_1691),
    .ap_return(grp_tree_sum_18_s_fu_306_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 9'd0;
    end else begin
        if (((grp_tree_sum_18_s_fu_306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_return_preg <= grp_tree_sum_18_s_fu_306_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tree_sum_18_s_fu_306_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_tree_sum_18_s_fu_306_ap_start_reg <= 1'b1;
        end else if ((grp_tree_sum_18_s_fu_306_ap_ready == 1'b1)) begin
            grp_tree_sum_18_s_fu_306_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        y_10_reg_1636 <= y_10_fu_816_p3;
        y_11_reg_1641 <= y_11_fu_887_p3;
        y_12_reg_1646 <= y_12_fu_958_p3;
        y_13_reg_1651 <= y_13_fu_1029_p3;
        y_14_reg_1656 <= y_14_fu_1100_p3;
        y_15_reg_1661 <= y_15_fu_1171_p3;
        y_16_reg_1666 <= y_16_fu_1242_p3;
        y_17_reg_1671 <= y_17_fu_1313_p3;
        y_18_reg_1676 <= y_18_fu_1384_p3;
        y_19_reg_1681 <= y_19_fu_1455_p3;
        y_20_reg_1686 <= y_20_fu_1526_p3;
        y_21_reg_1691 <= y_21_fu_1597_p3;
        y_5_reg_1611 <= y_5_fu_461_p3;
        y_6_reg_1616 <= y_6_fu_532_p3;
        y_7_reg_1621 <= y_7_fu_603_p3;
        y_8_reg_1626 <= y_8_fu_674_p3;
        y_9_reg_1631 <= y_9_fu_745_p3;
        y_reg_1606 <= y_fu_390_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_tree_sum_18_s_fu_306_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_tree_sum_18_s_fu_306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_tree_sum_18_s_fu_306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_tree_sum_18_s_fu_306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_return = grp_tree_sum_18_s_fu_306_ap_return;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_tree_sum_18_s_fu_306_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln90_12_fu_342_p2 = ($signed(sext_ln90_12_fu_332_p1) + $signed(sext_ln90_fu_328_p1));

assign add_ln90_13_fu_407_p0 = x_3_val;

assign add_ln90_13_fu_407_p1 = x_2_val;

assign add_ln90_13_fu_407_p2 = ($signed(add_ln90_13_fu_407_p0) + $signed(add_ln90_13_fu_407_p1));

assign add_ln90_14_fu_413_p2 = ($signed(sext_ln90_14_fu_403_p1) + $signed(sext_ln90_13_fu_399_p1));

assign add_ln90_15_fu_478_p0 = x_5_val;

assign add_ln90_15_fu_478_p1 = x_4_val;

assign add_ln90_15_fu_478_p2 = ($signed(add_ln90_15_fu_478_p0) + $signed(add_ln90_15_fu_478_p1));

assign add_ln90_16_fu_484_p2 = ($signed(sext_ln90_16_fu_474_p1) + $signed(sext_ln90_15_fu_470_p1));

assign add_ln90_17_fu_549_p0 = x_7_val;

assign add_ln90_17_fu_549_p1 = x_6_val;

assign add_ln90_17_fu_549_p2 = ($signed(add_ln90_17_fu_549_p0) + $signed(add_ln90_17_fu_549_p1));

assign add_ln90_18_fu_555_p2 = ($signed(sext_ln90_18_fu_545_p1) + $signed(sext_ln90_17_fu_541_p1));

assign add_ln90_19_fu_620_p0 = x_9_val;

assign add_ln90_19_fu_620_p1 = x_8_val;

assign add_ln90_19_fu_620_p2 = ($signed(add_ln90_19_fu_620_p0) + $signed(add_ln90_19_fu_620_p1));

assign add_ln90_20_fu_626_p2 = ($signed(sext_ln90_20_fu_616_p1) + $signed(sext_ln90_19_fu_612_p1));

assign add_ln90_21_fu_691_p0 = x_11_val;

assign add_ln90_21_fu_691_p1 = x_10_val;

assign add_ln90_21_fu_691_p2 = ($signed(add_ln90_21_fu_691_p0) + $signed(add_ln90_21_fu_691_p1));

assign add_ln90_22_fu_697_p2 = ($signed(sext_ln90_22_fu_687_p1) + $signed(sext_ln90_21_fu_683_p1));

assign add_ln90_23_fu_762_p0 = x_13_val;

assign add_ln90_23_fu_762_p1 = x_12_val;

assign add_ln90_23_fu_762_p2 = ($signed(add_ln90_23_fu_762_p0) + $signed(add_ln90_23_fu_762_p1));

assign add_ln90_24_fu_768_p2 = ($signed(sext_ln90_24_fu_758_p1) + $signed(sext_ln90_23_fu_754_p1));

assign add_ln90_25_fu_833_p0 = x_15_val;

assign add_ln90_25_fu_833_p1 = x_14_val;

assign add_ln90_25_fu_833_p2 = ($signed(add_ln90_25_fu_833_p0) + $signed(add_ln90_25_fu_833_p1));

assign add_ln90_26_fu_839_p2 = ($signed(sext_ln90_26_fu_829_p1) + $signed(sext_ln90_25_fu_825_p1));

assign add_ln90_27_fu_904_p0 = x_17_val;

assign add_ln90_27_fu_904_p1 = x_16_val;

assign add_ln90_27_fu_904_p2 = ($signed(add_ln90_27_fu_904_p0) + $signed(add_ln90_27_fu_904_p1));

assign add_ln90_28_fu_910_p2 = ($signed(sext_ln90_28_fu_900_p1) + $signed(sext_ln90_27_fu_896_p1));

assign add_ln90_29_fu_975_p0 = x_19_val;

assign add_ln90_29_fu_975_p1 = x_18_val;

assign add_ln90_29_fu_975_p2 = ($signed(add_ln90_29_fu_975_p0) + $signed(add_ln90_29_fu_975_p1));

assign add_ln90_30_fu_981_p2 = ($signed(sext_ln90_30_fu_971_p1) + $signed(sext_ln90_29_fu_967_p1));

assign add_ln90_31_fu_1046_p0 = x_21_val;

assign add_ln90_31_fu_1046_p1 = x_20_val;

assign add_ln90_31_fu_1046_p2 = ($signed(add_ln90_31_fu_1046_p0) + $signed(add_ln90_31_fu_1046_p1));

assign add_ln90_32_fu_1052_p2 = ($signed(sext_ln90_32_fu_1042_p1) + $signed(sext_ln90_31_fu_1038_p1));

assign add_ln90_33_fu_1117_p0 = x_23_val;

assign add_ln90_33_fu_1117_p1 = x_22_val;

assign add_ln90_33_fu_1117_p2 = ($signed(add_ln90_33_fu_1117_p0) + $signed(add_ln90_33_fu_1117_p1));

assign add_ln90_34_fu_1123_p2 = ($signed(sext_ln90_34_fu_1113_p1) + $signed(sext_ln90_33_fu_1109_p1));

assign add_ln90_35_fu_1188_p0 = x_25_val;

assign add_ln90_35_fu_1188_p1 = x_24_val;

assign add_ln90_35_fu_1188_p2 = ($signed(add_ln90_35_fu_1188_p0) + $signed(add_ln90_35_fu_1188_p1));

assign add_ln90_36_fu_1194_p2 = ($signed(sext_ln90_36_fu_1184_p1) + $signed(sext_ln90_35_fu_1180_p1));

assign add_ln90_37_fu_1259_p0 = x_27_val;

assign add_ln90_37_fu_1259_p1 = x_26_val;

assign add_ln90_37_fu_1259_p2 = ($signed(add_ln90_37_fu_1259_p0) + $signed(add_ln90_37_fu_1259_p1));

assign add_ln90_38_fu_1265_p2 = ($signed(sext_ln90_38_fu_1255_p1) + $signed(sext_ln90_37_fu_1251_p1));

assign add_ln90_39_fu_1330_p0 = x_29_val;

assign add_ln90_39_fu_1330_p1 = x_28_val;

assign add_ln90_39_fu_1330_p2 = ($signed(add_ln90_39_fu_1330_p0) + $signed(add_ln90_39_fu_1330_p1));

assign add_ln90_40_fu_1336_p2 = ($signed(sext_ln90_40_fu_1326_p1) + $signed(sext_ln90_39_fu_1322_p1));

assign add_ln90_41_fu_1401_p0 = x_31_val;

assign add_ln90_41_fu_1401_p1 = x_30_val;

assign add_ln90_41_fu_1401_p2 = ($signed(add_ln90_41_fu_1401_p0) + $signed(add_ln90_41_fu_1401_p1));

assign add_ln90_42_fu_1407_p2 = ($signed(sext_ln90_42_fu_1397_p1) + $signed(sext_ln90_41_fu_1393_p1));

assign add_ln90_43_fu_1472_p0 = x_33_val;

assign add_ln90_43_fu_1472_p1 = x_32_val;

assign add_ln90_43_fu_1472_p2 = ($signed(add_ln90_43_fu_1472_p0) + $signed(add_ln90_43_fu_1472_p1));

assign add_ln90_44_fu_1478_p2 = ($signed(sext_ln90_44_fu_1468_p1) + $signed(sext_ln90_43_fu_1464_p1));

assign add_ln90_45_fu_1543_p0 = x_35_val;

assign add_ln90_45_fu_1543_p1 = x_34_val;

assign add_ln90_45_fu_1543_p2 = ($signed(add_ln90_45_fu_1543_p0) + $signed(add_ln90_45_fu_1543_p1));

assign add_ln90_46_fu_1549_p2 = ($signed(sext_ln90_46_fu_1539_p1) + $signed(sext_ln90_45_fu_1535_p1));

assign add_ln90_fu_336_p0 = x_1_val;

assign add_ln90_fu_336_p1 = x_0_val;

assign add_ln90_fu_336_p2 = ($signed(add_ln90_fu_336_p0) + $signed(add_ln90_fu_336_p1));

assign and_ln90_10_fu_796_p2 = (xor_ln90_23_fu_790_p2 & tmp_25_fu_782_p3);

assign and_ln90_11_fu_867_p2 = (xor_ln90_25_fu_861_p2 & tmp_27_fu_853_p3);

assign and_ln90_12_fu_938_p2 = (xor_ln90_27_fu_932_p2 & tmp_29_fu_924_p3);

assign and_ln90_13_fu_1009_p2 = (xor_ln90_29_fu_1003_p2 & tmp_31_fu_995_p3);

assign and_ln90_14_fu_1080_p2 = (xor_ln90_31_fu_1074_p2 & tmp_33_fu_1066_p3);

assign and_ln90_15_fu_1151_p2 = (xor_ln90_33_fu_1145_p2 & tmp_35_fu_1137_p3);

assign and_ln90_16_fu_1222_p2 = (xor_ln90_35_fu_1216_p2 & tmp_37_fu_1208_p3);

assign and_ln90_17_fu_1293_p2 = (xor_ln90_37_fu_1287_p2 & tmp_39_fu_1279_p3);

assign and_ln90_18_fu_1364_p2 = (xor_ln90_39_fu_1358_p2 & tmp_41_fu_1350_p3);

assign and_ln90_19_fu_1435_p2 = (xor_ln90_41_fu_1429_p2 & tmp_43_fu_1421_p3);

assign and_ln90_20_fu_1506_p2 = (xor_ln90_43_fu_1500_p2 & tmp_45_fu_1492_p3);

assign and_ln90_21_fu_1577_p2 = (xor_ln90_45_fu_1571_p2 & tmp_47_fu_1563_p3);

assign and_ln90_5_fu_441_p2 = (xor_ln90_13_fu_435_p2 & tmp_15_fu_427_p3);

assign and_ln90_6_fu_512_p2 = (xor_ln90_15_fu_506_p2 & tmp_17_fu_498_p3);

assign and_ln90_7_fu_583_p2 = (xor_ln90_17_fu_577_p2 & tmp_19_fu_569_p3);

assign and_ln90_8_fu_654_p2 = (xor_ln90_19_fu_648_p2 & tmp_21_fu_640_p3);

assign and_ln90_9_fu_725_p2 = (xor_ln90_21_fu_719_p2 & tmp_23_fu_711_p3);

assign and_ln90_fu_370_p2 = (xor_ln90_fu_364_p2 & tmp_13_fu_356_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_tree_sum_18_s_fu_306_ap_start = grp_tree_sum_18_s_fu_306_ap_start_reg;

assign select_ln90_13_fu_453_p3 = ((and_ln90_5_fu_441_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_15_fu_524_p3 = ((and_ln90_6_fu_512_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_17_fu_595_p3 = ((and_ln90_7_fu_583_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_19_fu_666_p3 = ((and_ln90_8_fu_654_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_21_fu_737_p3 = ((and_ln90_9_fu_725_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_23_fu_808_p3 = ((and_ln90_10_fu_796_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_25_fu_879_p3 = ((and_ln90_11_fu_867_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_27_fu_950_p3 = ((and_ln90_12_fu_938_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_29_fu_1021_p3 = ((and_ln90_13_fu_1009_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_31_fu_1092_p3 = ((and_ln90_14_fu_1080_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_33_fu_1163_p3 = ((and_ln90_15_fu_1151_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_35_fu_1234_p3 = ((and_ln90_16_fu_1222_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_37_fu_1305_p3 = ((and_ln90_17_fu_1293_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_39_fu_1376_p3 = ((and_ln90_18_fu_1364_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_41_fu_1447_p3 = ((and_ln90_19_fu_1435_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_43_fu_1518_p3 = ((and_ln90_20_fu_1506_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_45_fu_1589_p3 = ((and_ln90_21_fu_1577_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_fu_382_p3 = ((and_ln90_fu_370_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign sext_ln90_12_fu_332_p0 = x_1_val;

assign sext_ln90_12_fu_332_p1 = sext_ln90_12_fu_332_p0;

assign sext_ln90_13_fu_399_p0 = x_2_val;

assign sext_ln90_13_fu_399_p1 = sext_ln90_13_fu_399_p0;

assign sext_ln90_14_fu_403_p0 = x_3_val;

assign sext_ln90_14_fu_403_p1 = sext_ln90_14_fu_403_p0;

assign sext_ln90_15_fu_470_p0 = x_4_val;

assign sext_ln90_15_fu_470_p1 = sext_ln90_15_fu_470_p0;

assign sext_ln90_16_fu_474_p0 = x_5_val;

assign sext_ln90_16_fu_474_p1 = sext_ln90_16_fu_474_p0;

assign sext_ln90_17_fu_541_p0 = x_6_val;

assign sext_ln90_17_fu_541_p1 = sext_ln90_17_fu_541_p0;

assign sext_ln90_18_fu_545_p0 = x_7_val;

assign sext_ln90_18_fu_545_p1 = sext_ln90_18_fu_545_p0;

assign sext_ln90_19_fu_612_p0 = x_8_val;

assign sext_ln90_19_fu_612_p1 = sext_ln90_19_fu_612_p0;

assign sext_ln90_20_fu_616_p0 = x_9_val;

assign sext_ln90_20_fu_616_p1 = sext_ln90_20_fu_616_p0;

assign sext_ln90_21_fu_683_p0 = x_10_val;

assign sext_ln90_21_fu_683_p1 = sext_ln90_21_fu_683_p0;

assign sext_ln90_22_fu_687_p0 = x_11_val;

assign sext_ln90_22_fu_687_p1 = sext_ln90_22_fu_687_p0;

assign sext_ln90_23_fu_754_p0 = x_12_val;

assign sext_ln90_23_fu_754_p1 = sext_ln90_23_fu_754_p0;

assign sext_ln90_24_fu_758_p0 = x_13_val;

assign sext_ln90_24_fu_758_p1 = sext_ln90_24_fu_758_p0;

assign sext_ln90_25_fu_825_p0 = x_14_val;

assign sext_ln90_25_fu_825_p1 = sext_ln90_25_fu_825_p0;

assign sext_ln90_26_fu_829_p0 = x_15_val;

assign sext_ln90_26_fu_829_p1 = sext_ln90_26_fu_829_p0;

assign sext_ln90_27_fu_896_p0 = x_16_val;

assign sext_ln90_27_fu_896_p1 = sext_ln90_27_fu_896_p0;

assign sext_ln90_28_fu_900_p0 = x_17_val;

assign sext_ln90_28_fu_900_p1 = sext_ln90_28_fu_900_p0;

assign sext_ln90_29_fu_967_p0 = x_18_val;

assign sext_ln90_29_fu_967_p1 = sext_ln90_29_fu_967_p0;

assign sext_ln90_30_fu_971_p0 = x_19_val;

assign sext_ln90_30_fu_971_p1 = sext_ln90_30_fu_971_p0;

assign sext_ln90_31_fu_1038_p0 = x_20_val;

assign sext_ln90_31_fu_1038_p1 = sext_ln90_31_fu_1038_p0;

assign sext_ln90_32_fu_1042_p0 = x_21_val;

assign sext_ln90_32_fu_1042_p1 = sext_ln90_32_fu_1042_p0;

assign sext_ln90_33_fu_1109_p0 = x_22_val;

assign sext_ln90_33_fu_1109_p1 = sext_ln90_33_fu_1109_p0;

assign sext_ln90_34_fu_1113_p0 = x_23_val;

assign sext_ln90_34_fu_1113_p1 = sext_ln90_34_fu_1113_p0;

assign sext_ln90_35_fu_1180_p0 = x_24_val;

assign sext_ln90_35_fu_1180_p1 = sext_ln90_35_fu_1180_p0;

assign sext_ln90_36_fu_1184_p0 = x_25_val;

assign sext_ln90_36_fu_1184_p1 = sext_ln90_36_fu_1184_p0;

assign sext_ln90_37_fu_1251_p0 = x_26_val;

assign sext_ln90_37_fu_1251_p1 = sext_ln90_37_fu_1251_p0;

assign sext_ln90_38_fu_1255_p0 = x_27_val;

assign sext_ln90_38_fu_1255_p1 = sext_ln90_38_fu_1255_p0;

assign sext_ln90_39_fu_1322_p0 = x_28_val;

assign sext_ln90_39_fu_1322_p1 = sext_ln90_39_fu_1322_p0;

assign sext_ln90_40_fu_1326_p0 = x_29_val;

assign sext_ln90_40_fu_1326_p1 = sext_ln90_40_fu_1326_p0;

assign sext_ln90_41_fu_1393_p0 = x_30_val;

assign sext_ln90_41_fu_1393_p1 = sext_ln90_41_fu_1393_p0;

assign sext_ln90_42_fu_1397_p0 = x_31_val;

assign sext_ln90_42_fu_1397_p1 = sext_ln90_42_fu_1397_p0;

assign sext_ln90_43_fu_1464_p0 = x_32_val;

assign sext_ln90_43_fu_1464_p1 = sext_ln90_43_fu_1464_p0;

assign sext_ln90_44_fu_1468_p0 = x_33_val;

assign sext_ln90_44_fu_1468_p1 = sext_ln90_44_fu_1468_p0;

assign sext_ln90_45_fu_1535_p0 = x_34_val;

assign sext_ln90_45_fu_1535_p1 = sext_ln90_45_fu_1535_p0;

assign sext_ln90_46_fu_1539_p0 = x_35_val;

assign sext_ln90_46_fu_1539_p1 = sext_ln90_46_fu_1539_p0;

assign sext_ln90_fu_328_p0 = x_0_val;

assign sext_ln90_fu_328_p1 = sext_ln90_fu_328_p0;

assign tmp_13_fu_356_p3 = add_ln90_fu_336_p2[32'd8];

assign tmp_14_fu_419_p3 = add_ln90_14_fu_413_p2[32'd9];

assign tmp_15_fu_427_p3 = add_ln90_13_fu_407_p2[32'd8];

assign tmp_16_fu_490_p3 = add_ln90_16_fu_484_p2[32'd9];

assign tmp_17_fu_498_p3 = add_ln90_15_fu_478_p2[32'd8];

assign tmp_18_fu_561_p3 = add_ln90_18_fu_555_p2[32'd9];

assign tmp_19_fu_569_p3 = add_ln90_17_fu_549_p2[32'd8];

assign tmp_20_fu_632_p3 = add_ln90_20_fu_626_p2[32'd9];

assign tmp_21_fu_640_p3 = add_ln90_19_fu_620_p2[32'd8];

assign tmp_22_fu_703_p3 = add_ln90_22_fu_697_p2[32'd9];

assign tmp_23_fu_711_p3 = add_ln90_21_fu_691_p2[32'd8];

assign tmp_24_fu_774_p3 = add_ln90_24_fu_768_p2[32'd9];

assign tmp_25_fu_782_p3 = add_ln90_23_fu_762_p2[32'd8];

assign tmp_26_fu_845_p3 = add_ln90_26_fu_839_p2[32'd9];

assign tmp_27_fu_853_p3 = add_ln90_25_fu_833_p2[32'd8];

assign tmp_28_fu_916_p3 = add_ln90_28_fu_910_p2[32'd9];

assign tmp_29_fu_924_p3 = add_ln90_27_fu_904_p2[32'd8];

assign tmp_30_fu_987_p3 = add_ln90_30_fu_981_p2[32'd9];

assign tmp_31_fu_995_p3 = add_ln90_29_fu_975_p2[32'd8];

assign tmp_32_fu_1058_p3 = add_ln90_32_fu_1052_p2[32'd9];

assign tmp_33_fu_1066_p3 = add_ln90_31_fu_1046_p2[32'd8];

assign tmp_34_fu_1129_p3 = add_ln90_34_fu_1123_p2[32'd9];

assign tmp_35_fu_1137_p3 = add_ln90_33_fu_1117_p2[32'd8];

assign tmp_36_fu_1200_p3 = add_ln90_36_fu_1194_p2[32'd9];

assign tmp_37_fu_1208_p3 = add_ln90_35_fu_1188_p2[32'd8];

assign tmp_38_fu_1271_p3 = add_ln90_38_fu_1265_p2[32'd9];

assign tmp_39_fu_1279_p3 = add_ln90_37_fu_1259_p2[32'd8];

assign tmp_40_fu_1342_p3 = add_ln90_40_fu_1336_p2[32'd9];

assign tmp_41_fu_1350_p3 = add_ln90_39_fu_1330_p2[32'd8];

assign tmp_42_fu_1413_p3 = add_ln90_42_fu_1407_p2[32'd9];

assign tmp_43_fu_1421_p3 = add_ln90_41_fu_1401_p2[32'd8];

assign tmp_44_fu_1484_p3 = add_ln90_44_fu_1478_p2[32'd9];

assign tmp_45_fu_1492_p3 = add_ln90_43_fu_1472_p2[32'd8];

assign tmp_46_fu_1555_p3 = add_ln90_46_fu_1549_p2[32'd9];

assign tmp_47_fu_1563_p3 = add_ln90_45_fu_1543_p2[32'd8];

assign tmp_fu_348_p3 = add_ln90_12_fu_342_p2[32'd9];

assign xor_ln90_12_fu_376_p2 = (tmp_fu_348_p3 ^ tmp_13_fu_356_p3);

assign xor_ln90_13_fu_435_p2 = (tmp_14_fu_419_p3 ^ 1'd1);

assign xor_ln90_14_fu_447_p2 = (tmp_15_fu_427_p3 ^ tmp_14_fu_419_p3);

assign xor_ln90_15_fu_506_p2 = (tmp_16_fu_490_p3 ^ 1'd1);

assign xor_ln90_16_fu_518_p2 = (tmp_17_fu_498_p3 ^ tmp_16_fu_490_p3);

assign xor_ln90_17_fu_577_p2 = (tmp_18_fu_561_p3 ^ 1'd1);

assign xor_ln90_18_fu_589_p2 = (tmp_19_fu_569_p3 ^ tmp_18_fu_561_p3);

assign xor_ln90_19_fu_648_p2 = (tmp_20_fu_632_p3 ^ 1'd1);

assign xor_ln90_20_fu_660_p2 = (tmp_21_fu_640_p3 ^ tmp_20_fu_632_p3);

assign xor_ln90_21_fu_719_p2 = (tmp_22_fu_703_p3 ^ 1'd1);

assign xor_ln90_22_fu_731_p2 = (tmp_23_fu_711_p3 ^ tmp_22_fu_703_p3);

assign xor_ln90_23_fu_790_p2 = (tmp_24_fu_774_p3 ^ 1'd1);

assign xor_ln90_24_fu_802_p2 = (tmp_25_fu_782_p3 ^ tmp_24_fu_774_p3);

assign xor_ln90_25_fu_861_p2 = (tmp_26_fu_845_p3 ^ 1'd1);

assign xor_ln90_26_fu_873_p2 = (tmp_27_fu_853_p3 ^ tmp_26_fu_845_p3);

assign xor_ln90_27_fu_932_p2 = (tmp_28_fu_916_p3 ^ 1'd1);

assign xor_ln90_28_fu_944_p2 = (tmp_29_fu_924_p3 ^ tmp_28_fu_916_p3);

assign xor_ln90_29_fu_1003_p2 = (tmp_30_fu_987_p3 ^ 1'd1);

assign xor_ln90_30_fu_1015_p2 = (tmp_31_fu_995_p3 ^ tmp_30_fu_987_p3);

assign xor_ln90_31_fu_1074_p2 = (tmp_32_fu_1058_p3 ^ 1'd1);

assign xor_ln90_32_fu_1086_p2 = (tmp_33_fu_1066_p3 ^ tmp_32_fu_1058_p3);

assign xor_ln90_33_fu_1145_p2 = (tmp_34_fu_1129_p3 ^ 1'd1);

assign xor_ln90_34_fu_1157_p2 = (tmp_35_fu_1137_p3 ^ tmp_34_fu_1129_p3);

assign xor_ln90_35_fu_1216_p2 = (tmp_36_fu_1200_p3 ^ 1'd1);

assign xor_ln90_36_fu_1228_p2 = (tmp_37_fu_1208_p3 ^ tmp_36_fu_1200_p3);

assign xor_ln90_37_fu_1287_p2 = (tmp_38_fu_1271_p3 ^ 1'd1);

assign xor_ln90_38_fu_1299_p2 = (tmp_39_fu_1279_p3 ^ tmp_38_fu_1271_p3);

assign xor_ln90_39_fu_1358_p2 = (tmp_40_fu_1342_p3 ^ 1'd1);

assign xor_ln90_40_fu_1370_p2 = (tmp_41_fu_1350_p3 ^ tmp_40_fu_1342_p3);

assign xor_ln90_41_fu_1429_p2 = (tmp_42_fu_1413_p3 ^ 1'd1);

assign xor_ln90_42_fu_1441_p2 = (tmp_43_fu_1421_p3 ^ tmp_42_fu_1413_p3);

assign xor_ln90_43_fu_1500_p2 = (tmp_44_fu_1484_p3 ^ 1'd1);

assign xor_ln90_44_fu_1512_p2 = (tmp_45_fu_1492_p3 ^ tmp_44_fu_1484_p3);

assign xor_ln90_45_fu_1571_p2 = (tmp_46_fu_1555_p3 ^ 1'd1);

assign xor_ln90_46_fu_1583_p2 = (tmp_47_fu_1563_p3 ^ tmp_46_fu_1555_p3);

assign xor_ln90_fu_364_p2 = (tmp_fu_348_p3 ^ 1'd1);

assign y_10_fu_816_p3 = ((xor_ln90_24_fu_802_p2[0:0] == 1'b1) ? select_ln90_23_fu_808_p3 : add_ln90_23_fu_762_p2);

assign y_11_fu_887_p3 = ((xor_ln90_26_fu_873_p2[0:0] == 1'b1) ? select_ln90_25_fu_879_p3 : add_ln90_25_fu_833_p2);

assign y_12_fu_958_p3 = ((xor_ln90_28_fu_944_p2[0:0] == 1'b1) ? select_ln90_27_fu_950_p3 : add_ln90_27_fu_904_p2);

assign y_13_fu_1029_p3 = ((xor_ln90_30_fu_1015_p2[0:0] == 1'b1) ? select_ln90_29_fu_1021_p3 : add_ln90_29_fu_975_p2);

assign y_14_fu_1100_p3 = ((xor_ln90_32_fu_1086_p2[0:0] == 1'b1) ? select_ln90_31_fu_1092_p3 : add_ln90_31_fu_1046_p2);

assign y_15_fu_1171_p3 = ((xor_ln90_34_fu_1157_p2[0:0] == 1'b1) ? select_ln90_33_fu_1163_p3 : add_ln90_33_fu_1117_p2);

assign y_16_fu_1242_p3 = ((xor_ln90_36_fu_1228_p2[0:0] == 1'b1) ? select_ln90_35_fu_1234_p3 : add_ln90_35_fu_1188_p2);

assign y_17_fu_1313_p3 = ((xor_ln90_38_fu_1299_p2[0:0] == 1'b1) ? select_ln90_37_fu_1305_p3 : add_ln90_37_fu_1259_p2);

assign y_18_fu_1384_p3 = ((xor_ln90_40_fu_1370_p2[0:0] == 1'b1) ? select_ln90_39_fu_1376_p3 : add_ln90_39_fu_1330_p2);

assign y_19_fu_1455_p3 = ((xor_ln90_42_fu_1441_p2[0:0] == 1'b1) ? select_ln90_41_fu_1447_p3 : add_ln90_41_fu_1401_p2);

assign y_20_fu_1526_p3 = ((xor_ln90_44_fu_1512_p2[0:0] == 1'b1) ? select_ln90_43_fu_1518_p3 : add_ln90_43_fu_1472_p2);

assign y_21_fu_1597_p3 = ((xor_ln90_46_fu_1583_p2[0:0] == 1'b1) ? select_ln90_45_fu_1589_p3 : add_ln90_45_fu_1543_p2);

assign y_5_fu_461_p3 = ((xor_ln90_14_fu_447_p2[0:0] == 1'b1) ? select_ln90_13_fu_453_p3 : add_ln90_13_fu_407_p2);

assign y_6_fu_532_p3 = ((xor_ln90_16_fu_518_p2[0:0] == 1'b1) ? select_ln90_15_fu_524_p3 : add_ln90_15_fu_478_p2);

assign y_7_fu_603_p3 = ((xor_ln90_18_fu_589_p2[0:0] == 1'b1) ? select_ln90_17_fu_595_p3 : add_ln90_17_fu_549_p2);

assign y_8_fu_674_p3 = ((xor_ln90_20_fu_660_p2[0:0] == 1'b1) ? select_ln90_19_fu_666_p3 : add_ln90_19_fu_620_p2);

assign y_9_fu_745_p3 = ((xor_ln90_22_fu_731_p2[0:0] == 1'b1) ? select_ln90_21_fu_737_p3 : add_ln90_21_fu_691_p2);

assign y_fu_390_p3 = ((xor_ln90_12_fu_376_p2[0:0] == 1'b1) ? select_ln90_fu_382_p3 : add_ln90_fu_336_p2);

endmodule //uniform_move_operation_tree_sum_36_s
