// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module uniform_move_operation_tree_sum_5_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_0_val,
        x_1_val,
        x_2_val,
        x_3_val,
        x_4_val,
        ap_return
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] x_0_val;
input  [8:0] x_1_val;
input  [8:0] x_2_val;
input  [8:0] x_3_val;
input  [8:0] x_4_val;
output  [8:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[8:0] ap_return;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [8:0] y_fu_128_p3;
reg   [8:0] y_reg_206;
wire   [8:0] y_4_fu_198_p3;
reg   [8:0] y_4_reg_211;
wire    agg_result_tree_sum_3_s_fu_58_ap_ready;
wire   [8:0] agg_result_tree_sum_3_s_fu_58_ap_return;
wire    ap_CS_fsm_state2;
wire  signed [8:0] sext_ln90_fu_66_p0;
wire  signed [8:0] sext_ln90_8_fu_70_p0;
wire  signed [8:0] add_ln90_fu_74_p0;
wire  signed [8:0] add_ln90_fu_74_p1;
wire  signed [9:0] sext_ln90_8_fu_70_p1;
wire  signed [9:0] sext_ln90_fu_66_p1;
wire   [9:0] add_ln90_8_fu_80_p2;
wire   [8:0] add_ln90_fu_74_p2;
wire   [0:0] tmp_fu_86_p3;
wire   [0:0] tmp_9_fu_94_p3;
wire   [0:0] xor_ln90_fu_102_p2;
wire   [0:0] and_ln90_fu_108_p2;
wire   [0:0] xor_ln90_8_fu_114_p2;
wire   [8:0] select_ln90_fu_120_p3;
wire  signed [8:0] sext_ln90_9_fu_136_p0;
wire  signed [8:0] sext_ln90_10_fu_140_p0;
wire  signed [8:0] add_ln90_9_fu_144_p0;
wire  signed [8:0] add_ln90_9_fu_144_p1;
wire  signed [9:0] sext_ln90_10_fu_140_p1;
wire  signed [9:0] sext_ln90_9_fu_136_p1;
wire   [9:0] add_ln90_10_fu_150_p2;
wire   [8:0] add_ln90_9_fu_144_p2;
wire   [0:0] tmp_10_fu_156_p3;
wire   [0:0] tmp_11_fu_164_p3;
wire   [0:0] xor_ln90_9_fu_172_p2;
wire   [0:0] and_ln90_4_fu_178_p2;
wire   [0:0] xor_ln90_10_fu_184_p2;
wire   [8:0] select_ln90_9_fu_190_p3;
reg   [8:0] ap_return_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_return_preg = 9'd0;
end

uniform_move_operation_tree_sum_3_s agg_result_tree_sum_3_s_fu_58(
    .ap_ready(agg_result_tree_sum_3_s_fu_58_ap_ready),
    .x_0_val(y_reg_206),
    .x_1_val(y_4_reg_211),
    .x_2_val(x_4_val),
    .ap_return(agg_result_tree_sum_3_s_fu_58_ap_return),
    .ap_rst(ap_rst)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 9'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            ap_return_preg <= agg_result_tree_sum_3_s_fu_58_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        y_4_reg_211 <= y_4_fu_198_p3;
        y_reg_206 <= y_fu_128_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_return = agg_result_tree_sum_3_s_fu_58_ap_return;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln90_10_fu_150_p2 = ($signed(sext_ln90_10_fu_140_p1) + $signed(sext_ln90_9_fu_136_p1));

assign add_ln90_8_fu_80_p2 = ($signed(sext_ln90_8_fu_70_p1) + $signed(sext_ln90_fu_66_p1));

assign add_ln90_9_fu_144_p0 = x_3_val;

assign add_ln90_9_fu_144_p1 = x_2_val;

assign add_ln90_9_fu_144_p2 = ($signed(add_ln90_9_fu_144_p0) + $signed(add_ln90_9_fu_144_p1));

assign add_ln90_fu_74_p0 = x_1_val;

assign add_ln90_fu_74_p1 = x_0_val;

assign add_ln90_fu_74_p2 = ($signed(add_ln90_fu_74_p0) + $signed(add_ln90_fu_74_p1));

assign and_ln90_4_fu_178_p2 = (xor_ln90_9_fu_172_p2 & tmp_11_fu_164_p3);

assign and_ln90_fu_108_p2 = (xor_ln90_fu_102_p2 & tmp_9_fu_94_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign select_ln90_9_fu_190_p3 = ((and_ln90_4_fu_178_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_fu_120_p3 = ((and_ln90_fu_108_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign sext_ln90_10_fu_140_p0 = x_3_val;

assign sext_ln90_10_fu_140_p1 = sext_ln90_10_fu_140_p0;

assign sext_ln90_8_fu_70_p0 = x_1_val;

assign sext_ln90_8_fu_70_p1 = sext_ln90_8_fu_70_p0;

assign sext_ln90_9_fu_136_p0 = x_2_val;

assign sext_ln90_9_fu_136_p1 = sext_ln90_9_fu_136_p0;

assign sext_ln90_fu_66_p0 = x_0_val;

assign sext_ln90_fu_66_p1 = sext_ln90_fu_66_p0;

assign tmp_10_fu_156_p3 = add_ln90_10_fu_150_p2[32'd9];

assign tmp_11_fu_164_p3 = add_ln90_9_fu_144_p2[32'd8];

assign tmp_9_fu_94_p3 = add_ln90_fu_74_p2[32'd8];

assign tmp_fu_86_p3 = add_ln90_8_fu_80_p2[32'd9];

assign xor_ln90_10_fu_184_p2 = (tmp_11_fu_164_p3 ^ tmp_10_fu_156_p3);

assign xor_ln90_8_fu_114_p2 = (tmp_fu_86_p3 ^ tmp_9_fu_94_p3);

assign xor_ln90_9_fu_172_p2 = (tmp_10_fu_156_p3 ^ 1'd1);

assign xor_ln90_fu_102_p2 = (tmp_fu_86_p3 ^ 1'd1);

assign y_4_fu_198_p3 = ((xor_ln90_10_fu_184_p2[0:0] == 1'b1) ? select_ln90_9_fu_190_p3 : add_ln90_9_fu_144_p2);

assign y_fu_128_p3 = ((xor_ln90_8_fu_114_p2[0:0] == 1'b1) ? select_ln90_fu_120_p3 : add_ln90_fu_74_p2);

endmodule //uniform_move_operation_tree_sum_5_s
