// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module uniform_move_operation_tree_sum_1_s (
        ap_ready,
        x_val,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [8:0] x_val;
output  [8:0] ap_return;
input   ap_rst;

assign ap_ready = 1'b1;

assign ap_return = x_val;

endmodule //uniform_move_operation_tree_sum_1_s
