// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module uniform_move_operation_chebyshev_g (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        ap_return
);

parameter    ap_ST_fsm_state1 = 28'd1;
parameter    ap_ST_fsm_state2 = 28'd2;
parameter    ap_ST_fsm_state3 = 28'd4;
parameter    ap_ST_fsm_state4 = 28'd8;
parameter    ap_ST_fsm_state5 = 28'd16;
parameter    ap_ST_fsm_state6 = 28'd32;
parameter    ap_ST_fsm_state7 = 28'd64;
parameter    ap_ST_fsm_state8 = 28'd128;
parameter    ap_ST_fsm_state9 = 28'd256;
parameter    ap_ST_fsm_state10 = 28'd512;
parameter    ap_ST_fsm_state11 = 28'd1024;
parameter    ap_ST_fsm_state12 = 28'd2048;
parameter    ap_ST_fsm_state13 = 28'd4096;
parameter    ap_ST_fsm_state14 = 28'd8192;
parameter    ap_ST_fsm_state15 = 28'd16384;
parameter    ap_ST_fsm_state16 = 28'd32768;
parameter    ap_ST_fsm_state17 = 28'd65536;
parameter    ap_ST_fsm_state18 = 28'd131072;
parameter    ap_ST_fsm_state19 = 28'd262144;
parameter    ap_ST_fsm_state20 = 28'd524288;
parameter    ap_ST_fsm_state21 = 28'd1048576;
parameter    ap_ST_fsm_state22 = 28'd2097152;
parameter    ap_ST_fsm_state23 = 28'd4194304;
parameter    ap_ST_fsm_state24 = 28'd8388608;
parameter    ap_ST_fsm_state25 = 28'd16777216;
parameter    ap_ST_fsm_state26 = 28'd33554432;
parameter    ap_ST_fsm_state27 = 28'd67108864;
parameter    ap_ST_fsm_state28 = 28'd134217728;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] x;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [27:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [116:0] grp_fu_181_p2;
reg   [116:0] reg_190;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state22;
wire   [0:0] icmp_ln173_fu_194_p2;
reg   [0:0] icmp_ln173_reg_1471;
wire   [0:0] icmp_ln177_fu_200_p2;
reg   [0:0] icmp_ln177_reg_1478;
reg   [35:0] trunc_ln_reg_1489;
wire    ap_CS_fsm_state2;
reg   [0:0] tmp_91_reg_1494;
wire  signed [76:0] add_ln183_fu_285_p2;
reg  signed [76:0] add_ln183_reg_1499;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_93_fu_295_p3;
reg   [0:0] tmp_93_reg_1504;
wire   [0:0] tmp_94_fu_303_p3;
reg   [0:0] tmp_94_reg_1509;
wire   [0:0] tmp_95_fu_311_p3;
reg   [0:0] tmp_95_reg_1514;
wire   [0:0] and_ln183_fu_331_p2;
reg   [0:0] and_ln183_reg_1519;
wire  signed [39:0] y_30_fu_381_p3;
reg  signed [39:0] y_30_reg_1525;
wire    ap_CS_fsm_state4;
wire  signed [76:0] shl_ln2_fu_389_p3;
reg  signed [76:0] shl_ln2_reg_1530;
wire   [109:0] grp_fu_185_p2;
reg   [109:0] mul_ln191_reg_1540;
wire    ap_CS_fsm_state8;
reg   [0:0] tmp_96_reg_1545;
wire    ap_CS_fsm_state9;
reg   [37:0] b0_reg_1554;
reg   [0:0] tmp_97_reg_1559;
wire  signed [39:0] b0_9_fu_544_p3;
reg  signed [39:0] b0_9_reg_1564;
wire    ap_CS_fsm_state10;
wire  signed [116:0] sext_ln191_1_fu_552_p1;
reg  signed [116:0] sext_ln191_1_reg_1570;
wire    ap_CS_fsm_state11;
wire  signed [116:0] sext_ln191_4_fu_556_p1;
wire   [116:0] add_ln191_2_fu_560_p2;
reg   [116:0] add_ln191_2_reg_1580;
wire    ap_CS_fsm_state16;
reg   [0:0] tmp_99_reg_1586;
reg   [39:0] b0_3_reg_1592;
reg   [0:0] tmp_100_reg_1597;
wire   [0:0] icmp_ln191_fu_602_p2;
reg   [0:0] icmp_ln191_reg_1602;
wire   [0:0] icmp_ln191_1_fu_618_p2;
reg   [0:0] icmp_ln191_1_reg_1607;
wire   [0:0] icmp_ln191_2_fu_624_p2;
reg   [0:0] icmp_ln191_2_reg_1614;
wire  signed [39:0] b0_10_fu_761_p3;
reg  signed [39:0] b0_10_reg_1619;
wire    ap_CS_fsm_state17;
wire  signed [116:0] sext_ln191_5_fu_769_p1;
wire    ap_CS_fsm_state18;
wire   [0:0] tmp_104_fu_796_p3;
reg   [0:0] tmp_104_reg_1630;
wire    ap_CS_fsm_state23;
wire   [39:0] b0_7_fu_834_p2;
reg   [39:0] b0_7_reg_1635;
wire   [0:0] and_ln191_10_fu_854_p2;
reg   [0:0] and_ln191_10_reg_1640;
wire   [0:0] icmp_ln191_4_fu_894_p2;
reg   [0:0] icmp_ln191_4_reg_1645;
wire   [0:0] and_ln191_13_fu_952_p2;
reg   [0:0] and_ln191_13_reg_1650;
wire   [0:0] and_ln191_14_fu_958_p2;
reg   [0:0] and_ln191_14_reg_1656;
wire   [39:0] b0_11_fu_996_p3;
reg  signed [39:0] b0_11_reg_1661;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire   [79:0] grp_fu_177_p2;
reg   [79:0] mul_ln196_reg_1676;
wire    ap_CS_fsm_state26;
wire   [39:0] p_1_fu_1071_p2;
reg   [39:0] p_1_reg_1681;
wire    ap_CS_fsm_state27;
wire   [0:0] and_ln196_3_fu_1195_p2;
reg   [0:0] and_ln196_3_reg_1686;
wire   [0:0] or_ln196_1_fu_1225_p2;
reg   [0:0] or_ln196_1_reg_1691;
wire   [31:0] grp_fu_172_p0;
wire   [36:0] grp_fu_172_p1;
reg  signed [76:0] grp_fu_181_p0;
reg  signed [39:0] grp_fu_181_p1;
wire   [33:0] grp_fu_185_p1;
wire   [31:0] shl_ln_fu_206_p3;
wire   [67:0] grp_fu_172_p2;
wire   [35:0] zext_ln182_1_fu_237_p1;
wire   [35:0] z_fu_240_p2;
wire   [34:0] trunc_ln182_fu_245_p1;
wire   [0:0] tmp_92_fu_257_p3;
wire   [38:0] shl_ln1_fu_249_p3;
wire   [38:0] select_ln183_fu_265_p3;
wire   [75:0] shl_ln183_1_fu_273_p3;
wire   [76:0] zext_ln183_fu_281_p1;
wire  signed [77:0] sext_ln183_fu_291_p1;
wire   [0:0] or_ln183_fu_319_p2;
wire   [0:0] xor_ln183_fu_325_p2;
wire   [38:0] tmp_fu_337_p4;
wire   [0:0] and_ln183_1_fu_354_p2;
wire   [0:0] xor_ln183_1_fu_358_p2;
wire   [0:0] and_ln183_2_fu_364_p2;
wire   [0:0] or_ln183_1_fu_376_p2;
wire   [39:0] select_ln183_1_fu_369_p3;
wire   [39:0] y_fu_346_p3;
wire   [109:0] add_ln191_fu_402_p2;
wire  signed [38:0] sext_ln191_3_fu_433_p1;
wire   [38:0] zext_ln191_fu_436_p1;
wire   [38:0] b0_1_fu_439_p2;
wire  signed [39:0] sext_ln191_7_fu_445_p1;
wire   [0:0] tmp_98_fu_449_p3;
wire   [0:0] xor_ln191_fu_457_p2;
wire   [0:0] xor_ln191_1_fu_468_p2;
wire   [0:0] or_ln191_6_fu_473_p2;
wire   [0:0] and_ln191_fu_463_p2;
wire   [0:0] xor_ln191_2_fu_479_p2;
wire   [0:0] xor_ln191_3_fu_489_p2;
wire   [0:0] or_ln191_fu_495_p2;
wire   [0:0] xor_ln191_4_fu_484_p2;
wire   [0:0] and_ln191_2_fu_507_p2;
wire   [0:0] or_ln191_7_fu_513_p2;
wire   [0:0] xor_ln191_5_fu_519_p2;
wire   [0:0] and_ln191_1_fu_501_p2;
wire   [0:0] and_ln191_3_fu_525_p2;
wire   [0:0] or_ln191_1_fu_538_p2;
wire   [39:0] select_ln191_fu_530_p3;
wire   [3:0] tmp_4_fu_592_p4;
wire   [4:0] tmp_5_fu_608_p4;
wire   [39:0] zext_ln191_1_fu_637_p1;
wire   [39:0] b0_4_fu_640_p2;
wire   [0:0] tmp_102_fu_645_p3;
wire   [0:0] tmp_101_fu_630_p3;
wire   [0:0] xor_ln191_6_fu_653_p2;
wire   [0:0] and_ln191_4_fu_659_p2;
wire   [0:0] tmp_103_fu_665_p3;
wire   [0:0] xor_ln191_7_fu_678_p2;
wire   [0:0] and_ln191_5_fu_684_p2;
wire   [0:0] select_ln191_2_fu_672_p3;
wire   [0:0] xor_ln191_8_fu_701_p2;
wire   [0:0] or_ln191_2_fu_707_p2;
wire   [0:0] xor_ln191_9_fu_713_p2;
wire   [0:0] select_ln191_3_fu_689_p3;
wire   [0:0] and_ln191_6_fu_696_p2;
wire   [0:0] and_ln191_8_fu_724_p2;
wire   [0:0] or_ln191_8_fu_730_p2;
wire   [0:0] xor_ln191_10_fu_736_p2;
wire   [0:0] and_ln191_7_fu_718_p2;
wire   [0:0] and_ln191_9_fu_742_p2;
wire   [0:0] or_ln191_3_fu_755_p2;
wire   [39:0] select_ln191_4_fu_747_p3;
wire   [111:0] shl_ln191_1_fu_773_p3;
wire  signed [116:0] sext_ln191_6_fu_780_p1;
wire   [116:0] sub_ln191_fu_784_p2;
wire   [116:0] add_ln191_4_fu_790_p2;
wire   [0:0] tmp_105_fu_814_p3;
wire   [39:0] b0_6_fu_804_p4;
wire   [39:0] zext_ln191_2_fu_830_p1;
wire   [0:0] tmp_107_fu_840_p3;
wire   [0:0] tmp_106_fu_822_p3;
wire   [0:0] xor_ln191_11_fu_848_p2;
wire   [3:0] tmp_6_fu_868_p4;
wire   [4:0] tmp_7_fu_884_p4;
wire   [0:0] icmp_ln191_5_fu_900_p2;
wire   [0:0] tmp_108_fu_860_p3;
wire   [0:0] icmp_ln191_3_fu_878_p2;
wire   [0:0] xor_ln191_12_fu_914_p2;
wire   [0:0] and_ln191_11_fu_920_p2;
wire   [0:0] select_ln191_6_fu_906_p3;
wire   [0:0] xor_ln191_13_fu_934_p2;
wire   [0:0] or_ln191_4_fu_940_p2;
wire   [0:0] xor_ln191_14_fu_946_p2;
wire   [0:0] select_ln191_7_fu_926_p3;
wire   [0:0] and_ln191_12_fu_964_p2;
wire   [0:0] or_ln191_9_fu_968_p2;
wire   [0:0] xor_ln191_15_fu_973_p2;
wire   [0:0] and_ln191_15_fu_979_p2;
wire   [0:0] or_ln191_5_fu_991_p2;
wire   [39:0] select_ln191_8_fu_984_p3;
wire   [75:0] shl_ln3_fu_1016_p3;
wire   [79:0] add_ln196_fu_1011_p2;
wire  signed [79:0] sext_ln196_1_fu_1023_p1;
wire   [79:0] sub_ln196_fu_1027_p2;
wire   [0:0] tmp_110_fu_1051_p3;
wire   [39:0] p_fu_1041_p4;
wire   [39:0] zext_ln196_fu_1067_p1;
wire   [0:0] tmp_112_fu_1077_p3;
wire   [0:0] tmp_111_fu_1059_p3;
wire   [0:0] xor_ln196_fu_1085_p2;
wire   [2:0] tmp_8_fu_1105_p4;
wire   [3:0] tmp_9_fu_1121_p4;
wire   [0:0] and_ln196_fu_1091_p2;
wire   [0:0] icmp_ln196_1_fu_1131_p2;
wire   [0:0] icmp_ln196_2_fu_1137_p2;
wire   [0:0] tmp_113_fu_1097_p3;
wire   [0:0] icmp_ln196_fu_1115_p2;
wire   [0:0] xor_ln196_1_fu_1151_p2;
wire   [0:0] and_ln196_1_fu_1157_p2;
wire   [0:0] select_ln196_fu_1143_p3;
wire   [0:0] xor_ln196_2_fu_1177_p2;
wire   [0:0] tmp_109_fu_1033_p3;
wire   [0:0] or_ln196_fu_1183_p2;
wire   [0:0] xor_ln196_3_fu_1189_p2;
wire   [0:0] select_ln196_1_fu_1163_p3;
wire   [0:0] and_ln196_2_fu_1171_p2;
wire   [0:0] and_ln196_4_fu_1201_p2;
wire   [0:0] or_ln196_2_fu_1207_p2;
wire   [0:0] xor_ln196_4_fu_1213_p2;
wire   [0:0] and_ln196_5_fu_1219_p2;
wire    ap_CS_fsm_state28;
wire   [39:0] select_ln196_2_fu_1231_p3;
wire   [39:0] p_2_fu_1238_p3;
wire   [3:0] tmp_114_fu_1250_p4;
wire   [0:0] tmp_116_fu_1284_p3;
wire   [31:0] trunc_ln2_fu_1274_p4;
wire   [31:0] zext_ln206_fu_1300_p1;
wire   [31:0] add_ln206_fu_1304_p2;
wire   [0:0] tmp_117_fu_1292_p3;
wire   [0:0] tmp_118_fu_1310_p3;
wire   [0:0] not_tmp_121_fu_1318_p2;
wire   [0:0] empty_fu_1324_p2;
wire   [0:0] tmp_115_fu_1266_p3;
wire   [0:0] xor_ln206_fu_1336_p2;
wire   [0:0] or_ln206_fu_1330_p2;
wire   [0:0] and_ln206_fu_1342_p2;
wire   [0:0] xor_ln206_1_fu_1348_p2;
wire   [0:0] icmp_ln198_fu_1244_p2;
wire   [0:0] or_ln198_fu_1376_p2;
wire   [0:0] icmp_ln202_fu_1260_p2;
wire   [0:0] xor_ln198_fu_1381_p2;
wire   [0:0] and_ln202_fu_1387_p2;
wire   [0:0] xor_ln173_fu_1398_p2;
wire   [0:0] or_ln202_2_fu_1413_p2;
wire   [0:0] or_ln202_1_fu_1409_p2;
wire   [0:0] or_ln202_3_fu_1419_p2;
wire   [0:0] or_ln206_1_fu_1354_p2;
wire   [0:0] xor_ln202_fu_1425_p2;
wire   [0:0] or_ln202_fu_1393_p2;
wire   [0:0] and_ln198_fu_1403_p2;
wire   [0:0] and_ln206_1_fu_1431_p2;
wire   [31:0] agg_result_3_fu_1447_p6;
wire   [31:0] agg_result_3_fu_1447_p8;
wire   [31:0] agg_result_3_fu_1447_p9;
wire   [2:0] agg_result_3_fu_1447_p10;
wire   [31:0] agg_result_3_fu_1447_p11;
reg   [27:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire   [67:0] grp_fu_172_p00;
wire  signed [2:0] agg_result_3_fu_1447_p1;
wire   [2:0] agg_result_3_fu_1447_p3;
wire   [2:0] agg_result_3_fu_1447_p5;
wire   [2:0] agg_result_3_fu_1447_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 28'd1;
end

uniform_move_operation_mul_32ns_37ns_68_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 37 ),
    .dout_WIDTH( 68 ))
mul_32ns_37ns_68_2_1_U151(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_172_p0),
    .din1(grp_fu_172_p1),
    .ce(1'b1),
    .dout(grp_fu_172_p2)
);

uniform_move_operation_mul_40s_40s_80_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 40 ),
    .dout_WIDTH( 80 ))
mul_40s_40s_80_2_1_U152(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b0_11_reg_1661),
    .din1(y_30_reg_1525),
    .ce(1'b1),
    .dout(grp_fu_177_p2)
);

uniform_move_operation_mul_77s_40s_117_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 77 ),
    .din1_WIDTH( 40 ),
    .dout_WIDTH( 117 ))
mul_77s_40s_117_5_1_U153(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_181_p0),
    .din1(grp_fu_181_p1),
    .ce(1'b1),
    .dout(grp_fu_181_p2)
);

uniform_move_operation_mul_77s_34ns_110_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 77 ),
    .din1_WIDTH( 34 ),
    .dout_WIDTH( 110 ))
mul_77s_34ns_110_5_1_U154(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(shl_ln2_fu_389_p3),
    .din1(grp_fu_185_p1),
    .ce(1'b1),
    .dout(grp_fu_185_p2)
);

(* dissolve_hierarchy = "yes" *) uniform_move_operation_sparsemux_9_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_9_3_32_1_1_U155(
    .din0(32'd2147483648),
    .din1(32'd0),
    .din2(agg_result_3_fu_1447_p6),
    .din3(agg_result_3_fu_1447_p8),
    .def(agg_result_3_fu_1447_p9),
    .sel(agg_result_3_fu_1447_p10),
    .dout(agg_result_3_fu_1447_p11)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln183_reg_1499[76 : 37] <= add_ln183_fu_285_p2[76 : 37];
        and_ln183_reg_1519 <= and_ln183_fu_331_p2;
        tmp_93_reg_1504 <= sext_ln183_fu_291_p1[32'd77];
        tmp_94_reg_1509 <= sext_ln183_fu_291_p1[32'd75];
        tmp_95_reg_1514 <= add_ln183_fu_285_p2[32'd76];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        add_ln191_2_reg_1580 <= add_ln191_2_fu_560_p2;
        b0_3_reg_1592 <= {{add_ln191_2_fu_560_p2[111:72]}};
        icmp_ln191_1_reg_1607 <= icmp_ln191_1_fu_618_p2;
        icmp_ln191_2_reg_1614 <= icmp_ln191_2_fu_624_p2;
        icmp_ln191_reg_1602 <= icmp_ln191_fu_602_p2;
        tmp_100_reg_1597 <= add_ln191_2_fu_560_p2[32'd71];
        tmp_99_reg_1586 <= add_ln191_2_fu_560_p2[32'd116];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        and_ln191_10_reg_1640 <= and_ln191_10_fu_854_p2;
        and_ln191_13_reg_1650 <= and_ln191_13_fu_952_p2;
        and_ln191_14_reg_1656 <= and_ln191_14_fu_958_p2;
        b0_7_reg_1635 <= b0_7_fu_834_p2;
        icmp_ln191_4_reg_1645 <= icmp_ln191_4_fu_894_p2;
        tmp_104_reg_1630 <= add_ln191_4_fu_790_p2[32'd116];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        and_ln196_3_reg_1686 <= and_ln196_3_fu_1195_p2;
        or_ln196_1_reg_1691 <= or_ln196_1_fu_1225_p2;
        p_1_reg_1681 <= p_1_fu_1071_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        b0_10_reg_1619 <= b0_10_fu_761_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        b0_11_reg_1661 <= b0_11_fu_996_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        b0_9_reg_1564 <= b0_9_fu_544_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        b0_reg_1554 <= {{add_ln191_fu_402_p2[109:72]}};
        tmp_96_reg_1545 <= add_ln191_fu_402_p2[32'd109];
        tmp_97_reg_1559 <= add_ln191_fu_402_p2[32'd71];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln173_reg_1471 <= icmp_ln173_fu_194_p2;
        icmp_ln177_reg_1478 <= icmp_ln177_fu_200_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        mul_ln191_reg_1540 <= grp_fu_185_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        mul_ln196_reg_1676 <= grp_fu_177_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state15))) begin
        reg_190 <= grp_fu_181_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        sext_ln191_1_reg_1570[116 : 37] <= sext_ln191_1_fu_552_p1[116 : 37];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        shl_ln2_reg_1530[76 : 37] <= shl_ln2_fu_389_p3[76 : 37];
        y_30_reg_1525 <= y_30_fu_381_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_91_reg_1494 <= grp_fu_172_p2[32'd31];
        trunc_ln_reg_1489 <= {{grp_fu_172_p2[67:32]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_181_p0 = sext_ln191_1_reg_1570;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_181_p0 = sext_ln191_1_fu_552_p1;
    end else begin
        grp_fu_181_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_181_p1 = sext_ln191_5_fu_769_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_181_p1 = sext_ln191_4_fu_556_p1;
    end else begin
        grp_fu_181_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln183_fu_285_p2 = ($signed(zext_ln183_fu_281_p1) + $signed(77'd146393360968959001624576));

assign add_ln191_2_fu_560_p2 = (reg_190 + 117'd54491716688964565116947385024512);

assign add_ln191_4_fu_790_p2 = ($signed(sub_ln191_fu_784_p2) + $signed(117'd166046658979047102308838767065038848));

assign add_ln191_fu_402_p2 = ($signed(mul_ln191_reg_1540) + $signed(110'd1253102711473790588673265330290688));

assign add_ln196_fu_1011_p2 = (mul_ln196_reg_1676 + 80'd871241517012524990464);

assign add_ln206_fu_1304_p2 = (trunc_ln2_fu_1274_p4 + zext_ln206_fu_1300_p1);

assign agg_result_3_fu_1447_p10 = {{{or_ln202_fu_1393_p2}, {and_ln198_fu_1403_p2}}, {and_ln206_1_fu_1431_p2}};

assign agg_result_3_fu_1447_p6 = ((and_ln206_fu_1342_p2[0:0] == 1'b1) ? add_ln206_fu_1304_p2 : 32'd4294967295);

assign agg_result_3_fu_1447_p8 = ((tmp_115_fu_1266_p3[0:0] == 1'b1) ? 32'd0 : add_ln206_fu_1304_p2);

assign agg_result_3_fu_1447_p9 = 'bx;

assign and_ln183_1_fu_354_p2 = (tmp_95_reg_1514 & tmp_94_reg_1509);

assign and_ln183_2_fu_364_p2 = (xor_ln183_1_fu_358_p2 & tmp_93_reg_1504);

assign and_ln183_fu_331_p2 = (xor_ln183_fu_325_p2 & or_ln183_fu_319_p2);

assign and_ln191_10_fu_854_p2 = (xor_ln191_11_fu_848_p2 & tmp_106_fu_822_p3);

assign and_ln191_11_fu_920_p2 = (xor_ln191_12_fu_914_p2 & icmp_ln191_3_fu_878_p2);

assign and_ln191_12_fu_964_p2 = (icmp_ln191_4_reg_1645 & and_ln191_10_reg_1640);

assign and_ln191_13_fu_952_p2 = (xor_ln191_14_fu_946_p2 & or_ln191_4_fu_940_p2);

assign and_ln191_14_fu_958_p2 = (tmp_107_fu_840_p3 & select_ln191_7_fu_926_p3);

assign and_ln191_15_fu_979_p2 = (xor_ln191_15_fu_973_p2 & tmp_104_reg_1630);

assign and_ln191_1_fu_501_p2 = (xor_ln191_1_fu_468_p2 & or_ln191_fu_495_p2);

assign and_ln191_2_fu_507_p2 = (xor_ln191_4_fu_484_p2 & tmp_98_fu_449_p3);

assign and_ln191_3_fu_525_p2 = (xor_ln191_5_fu_519_p2 & tmp_96_reg_1545);

assign and_ln191_4_fu_659_p2 = (xor_ln191_6_fu_653_p2 & tmp_101_fu_630_p3);

assign and_ln191_5_fu_684_p2 = (xor_ln191_7_fu_678_p2 & icmp_ln191_reg_1602);

assign and_ln191_6_fu_696_p2 = (icmp_ln191_1_reg_1607 & and_ln191_4_fu_659_p2);

assign and_ln191_7_fu_718_p2 = (xor_ln191_9_fu_713_p2 & or_ln191_2_fu_707_p2);

assign and_ln191_8_fu_724_p2 = (tmp_102_fu_645_p3 & select_ln191_3_fu_689_p3);

assign and_ln191_9_fu_742_p2 = (xor_ln191_10_fu_736_p2 & tmp_99_reg_1586);

assign and_ln191_fu_463_p2 = (xor_ln191_fu_457_p2 & tmp_96_reg_1545);

assign and_ln196_1_fu_1157_p2 = (xor_ln196_1_fu_1151_p2 & icmp_ln196_fu_1115_p2);

assign and_ln196_2_fu_1171_p2 = (icmp_ln196_1_fu_1131_p2 & and_ln196_fu_1091_p2);

assign and_ln196_3_fu_1195_p2 = (xor_ln196_3_fu_1189_p2 & or_ln196_fu_1183_p2);

assign and_ln196_4_fu_1201_p2 = (tmp_112_fu_1077_p3 & select_ln196_1_fu_1163_p3);

assign and_ln196_5_fu_1219_p2 = (xor_ln196_4_fu_1213_p2 & tmp_109_fu_1033_p3);

assign and_ln196_fu_1091_p2 = (xor_ln196_fu_1085_p2 & tmp_111_fu_1059_p3);

assign and_ln198_fu_1403_p2 = (xor_ln173_fu_1398_p2 & or_ln198_fu_1376_p2);

assign and_ln202_fu_1387_p2 = (xor_ln198_fu_1381_p2 & icmp_ln202_fu_1260_p2);

assign and_ln206_1_fu_1431_p2 = (xor_ln202_fu_1425_p2 & or_ln206_1_fu_1354_p2);

assign and_ln206_fu_1342_p2 = (xor_ln206_fu_1336_p2 & empty_fu_1324_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = agg_result_3_fu_1447_p11;

assign b0_10_fu_761_p3 = ((or_ln191_3_fu_755_p2[0:0] == 1'b1) ? select_ln191_4_fu_747_p3 : b0_4_fu_640_p2);

assign b0_11_fu_996_p3 = ((or_ln191_5_fu_991_p2[0:0] == 1'b1) ? select_ln191_8_fu_984_p3 : b0_7_reg_1635);

assign b0_1_fu_439_p2 = ($signed(sext_ln191_3_fu_433_p1) + $signed(zext_ln191_fu_436_p1));

assign b0_4_fu_640_p2 = (b0_3_reg_1592 + zext_ln191_1_fu_637_p1);

assign b0_6_fu_804_p4 = {{add_ln191_4_fu_790_p2[111:72]}};

assign b0_7_fu_834_p2 = (b0_6_fu_804_p4 + zext_ln191_2_fu_830_p1);

assign b0_9_fu_544_p3 = ((or_ln191_1_fu_538_p2[0:0] == 1'b1) ? select_ln191_fu_530_p3 : sext_ln191_7_fu_445_p1);

assign empty_fu_1324_p2 = (tmp_118_fu_1310_p3 | not_tmp_121_fu_1318_p2);

assign grp_fu_172_p0 = grp_fu_172_p00;

assign grp_fu_172_p00 = shl_ln_fu_206_p3;

assign grp_fu_172_p1 = 68'd44291637041;

assign grp_fu_185_p1 = 110'd4679461253;

assign icmp_ln173_fu_194_p2 = ((x == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln177_fu_200_p2 = ((x > 8'd24) ? 1'b1 : 1'b0);

assign icmp_ln191_1_fu_618_p2 = ((tmp_5_fu_608_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln191_2_fu_624_p2 = ((tmp_5_fu_608_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln191_3_fu_878_p2 = ((tmp_6_fu_868_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln191_4_fu_894_p2 = ((tmp_7_fu_884_p4 == 5'd31) ? 1'b1 : 1'b0);

assign icmp_ln191_5_fu_900_p2 = ((tmp_7_fu_884_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln191_fu_602_p2 = ((tmp_4_fu_592_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln196_1_fu_1131_p2 = ((tmp_9_fu_1121_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln196_2_fu_1137_p2 = ((tmp_9_fu_1121_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln196_fu_1115_p2 = ((tmp_8_fu_1105_p4 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln198_fu_1244_p2 = (($signed(p_2_fu_1238_p3) < $signed(40'd1)) ? 1'b1 : 1'b0);

assign icmp_ln202_fu_1260_p2 = (($signed(tmp_114_fu_1250_p4) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign not_tmp_121_fu_1318_p2 = (tmp_117_fu_1292_p3 ^ 1'd1);

assign or_ln183_1_fu_376_p2 = (and_ln183_reg_1519 | and_ln183_2_fu_364_p2);

assign or_ln183_fu_319_p2 = (tmp_95_fu_311_p3 | tmp_94_fu_303_p3);

assign or_ln191_1_fu_538_p2 = (and_ln191_3_fu_525_p2 | and_ln191_1_fu_501_p2);

assign or_ln191_2_fu_707_p2 = (xor_ln191_8_fu_701_p2 | tmp_102_fu_645_p3);

assign or_ln191_3_fu_755_p2 = (and_ln191_9_fu_742_p2 | and_ln191_7_fu_718_p2);

assign or_ln191_4_fu_940_p2 = (xor_ln191_13_fu_934_p2 | tmp_107_fu_840_p3);

assign or_ln191_5_fu_991_p2 = (and_ln191_15_fu_979_p2 | and_ln191_13_reg_1650);

assign or_ln191_6_fu_473_p2 = (xor_ln191_1_fu_468_p2 | tmp_98_fu_449_p3);

assign or_ln191_7_fu_513_p2 = (and_ln191_fu_463_p2 | and_ln191_2_fu_507_p2);

assign or_ln191_8_fu_730_p2 = (and_ln191_8_fu_724_p2 | and_ln191_6_fu_696_p2);

assign or_ln191_9_fu_968_p2 = (and_ln191_14_reg_1656 | and_ln191_12_fu_964_p2);

assign or_ln191_fu_495_p2 = (xor_ln191_3_fu_489_p2 | tmp_98_fu_449_p3);

assign or_ln196_1_fu_1225_p2 = (and_ln196_5_fu_1219_p2 | and_ln196_3_fu_1195_p2);

assign or_ln196_2_fu_1207_p2 = (and_ln196_4_fu_1201_p2 | and_ln196_2_fu_1171_p2);

assign or_ln196_fu_1183_p2 = (xor_ln196_2_fu_1177_p2 | tmp_112_fu_1077_p3);

assign or_ln198_fu_1376_p2 = (icmp_ln198_fu_1244_p2 | icmp_ln177_reg_1478);

assign or_ln202_1_fu_1409_p2 = (icmp_ln177_reg_1478 | icmp_ln173_reg_1471);

assign or_ln202_2_fu_1413_p2 = (icmp_ln202_fu_1260_p2 | icmp_ln198_fu_1244_p2);

assign or_ln202_3_fu_1419_p2 = (or_ln202_2_fu_1413_p2 | or_ln202_1_fu_1409_p2);

assign or_ln202_fu_1393_p2 = (icmp_ln173_reg_1471 | and_ln202_fu_1387_p2);

assign or_ln206_1_fu_1354_p2 = (xor_ln206_1_fu_1348_p2 | and_ln206_fu_1342_p2);

assign or_ln206_fu_1330_p2 = (tmp_115_fu_1266_p3 | empty_fu_1324_p2);

assign p_1_fu_1071_p2 = (p_fu_1041_p4 + zext_ln196_fu_1067_p1);

assign p_2_fu_1238_p3 = ((or_ln196_1_reg_1691[0:0] == 1'b1) ? select_ln196_2_fu_1231_p3 : p_1_reg_1681);

assign p_fu_1041_p4 = {{sub_ln196_fu_1027_p2[75:36]}};

assign select_ln183_1_fu_369_p3 = ((and_ln183_reg_1519[0:0] == 1'b1) ? 40'd549755813887 : 40'd549755813888);

assign select_ln183_fu_265_p3 = ((tmp_92_fu_257_p3[0:0] == 1'b1) ? 39'd549755813887 : shl_ln1_fu_249_p3);

assign select_ln191_2_fu_672_p3 = ((and_ln191_4_fu_659_p2[0:0] == 1'b1) ? icmp_ln191_1_reg_1607 : icmp_ln191_2_reg_1614);

assign select_ln191_3_fu_689_p3 = ((and_ln191_4_fu_659_p2[0:0] == 1'b1) ? and_ln191_5_fu_684_p2 : icmp_ln191_1_reg_1607);

assign select_ln191_4_fu_747_p3 = ((and_ln191_7_fu_718_p2[0:0] == 1'b1) ? 40'd549755813887 : 40'd549755813888);

assign select_ln191_6_fu_906_p3 = ((and_ln191_10_fu_854_p2[0:0] == 1'b1) ? icmp_ln191_4_fu_894_p2 : icmp_ln191_5_fu_900_p2);

assign select_ln191_7_fu_926_p3 = ((and_ln191_10_fu_854_p2[0:0] == 1'b1) ? and_ln191_11_fu_920_p2 : icmp_ln191_4_fu_894_p2);

assign select_ln191_8_fu_984_p3 = ((and_ln191_13_reg_1650[0:0] == 1'b1) ? 40'd549755813887 : 40'd549755813888);

assign select_ln191_fu_530_p3 = ((and_ln191_1_fu_501_p2[0:0] == 1'b1) ? 40'd549755813887 : 40'd549755813888);

assign select_ln196_1_fu_1163_p3 = ((and_ln196_fu_1091_p2[0:0] == 1'b1) ? and_ln196_1_fu_1157_p2 : icmp_ln196_1_fu_1131_p2);

assign select_ln196_2_fu_1231_p3 = ((and_ln196_3_reg_1686[0:0] == 1'b1) ? 40'd549755813887 : 40'd549755813888);

assign select_ln196_fu_1143_p3 = ((and_ln196_fu_1091_p2[0:0] == 1'b1) ? icmp_ln196_1_fu_1131_p2 : icmp_ln196_2_fu_1137_p2);

assign sext_ln183_fu_291_p1 = add_ln183_fu_285_p2;

assign sext_ln191_1_fu_552_p1 = shl_ln2_reg_1530;

assign sext_ln191_3_fu_433_p1 = $signed(b0_reg_1554);

assign sext_ln191_4_fu_556_p1 = b0_9_reg_1564;

assign sext_ln191_5_fu_769_p1 = b0_10_reg_1619;

assign sext_ln191_6_fu_780_p1 = $signed(shl_ln191_1_fu_773_p3);

assign sext_ln191_7_fu_445_p1 = $signed(b0_1_fu_439_p2);

assign sext_ln196_1_fu_1023_p1 = $signed(shl_ln3_fu_1016_p3);

assign shl_ln183_1_fu_273_p3 = {{select_ln183_fu_265_p3}, {37'd0}};

assign shl_ln191_1_fu_773_p3 = {{b0_9_reg_1564}, {72'd0}};

assign shl_ln1_fu_249_p3 = {{trunc_ln182_fu_245_p1}, {4'd0}};

assign shl_ln2_fu_389_p3 = {{y_30_fu_381_p3}, {37'd0}};

assign shl_ln3_fu_1016_p3 = {{b0_10_reg_1619}, {36'd0}};

assign shl_ln_fu_206_p3 = {{x}, {24'd0}};

assign sub_ln191_fu_784_p2 = ($signed(reg_190) - $signed(sext_ln191_6_fu_780_p1));

assign sub_ln196_fu_1027_p2 = ($signed(add_ln196_fu_1011_p2) - $signed(sext_ln196_1_fu_1023_p1));

assign tmp_101_fu_630_p3 = add_ln191_2_reg_1580[32'd111];

assign tmp_102_fu_645_p3 = b0_4_fu_640_p2[32'd39];

assign tmp_103_fu_665_p3 = add_ln191_2_reg_1580[32'd112];

assign tmp_104_fu_796_p3 = add_ln191_4_fu_790_p2[32'd116];

assign tmp_105_fu_814_p3 = add_ln191_4_fu_790_p2[32'd71];

assign tmp_106_fu_822_p3 = add_ln191_4_fu_790_p2[32'd111];

assign tmp_107_fu_840_p3 = b0_7_fu_834_p2[32'd39];

assign tmp_108_fu_860_p3 = add_ln191_4_fu_790_p2[32'd112];

assign tmp_109_fu_1033_p3 = sub_ln196_fu_1027_p2[32'd79];

assign tmp_110_fu_1051_p3 = sub_ln196_fu_1027_p2[32'd35];

assign tmp_111_fu_1059_p3 = sub_ln196_fu_1027_p2[32'd75];

assign tmp_112_fu_1077_p3 = p_1_fu_1071_p2[32'd39];

assign tmp_113_fu_1097_p3 = sub_ln196_fu_1027_p2[32'd76];

assign tmp_114_fu_1250_p4 = {{p_2_fu_1238_p3[39:36]}};

assign tmp_115_fu_1266_p3 = p_2_fu_1238_p3[32'd39];

assign tmp_116_fu_1284_p3 = p_2_fu_1238_p3[32'd4];

assign tmp_117_fu_1292_p3 = p_2_fu_1238_p3[32'd36];

assign tmp_118_fu_1310_p3 = add_ln206_fu_1304_p2[32'd31];

assign tmp_4_fu_592_p4 = {{add_ln191_2_fu_560_p2[116:113]}};

assign tmp_5_fu_608_p4 = {{add_ln191_2_fu_560_p2[116:112]}};

assign tmp_6_fu_868_p4 = {{add_ln191_4_fu_790_p2[116:113]}};

assign tmp_7_fu_884_p4 = {{add_ln191_4_fu_790_p2[116:112]}};

assign tmp_8_fu_1105_p4 = {{sub_ln196_fu_1027_p2[79:77]}};

assign tmp_92_fu_257_p3 = z_fu_240_p2[32'd35];

assign tmp_93_fu_295_p3 = sext_ln183_fu_291_p1[32'd77];

assign tmp_94_fu_303_p3 = sext_ln183_fu_291_p1[32'd75];

assign tmp_95_fu_311_p3 = add_ln183_fu_285_p2[32'd76];

assign tmp_98_fu_449_p3 = sext_ln191_7_fu_445_p1[32'd39];

assign tmp_9_fu_1121_p4 = {{sub_ln196_fu_1027_p2[79:76]}};

assign tmp_fu_337_p4 = {{add_ln183_reg_1499[75:37]}};

assign trunc_ln182_fu_245_p1 = z_fu_240_p2[34:0];

assign trunc_ln2_fu_1274_p4 = {{p_2_fu_1238_p3[36:5]}};

assign xor_ln173_fu_1398_p2 = (icmp_ln173_reg_1471 ^ 1'd1);

assign xor_ln183_1_fu_358_p2 = (1'd1 ^ and_ln183_1_fu_354_p2);

assign xor_ln183_fu_325_p2 = (tmp_93_fu_295_p3 ^ 1'd1);

assign xor_ln191_10_fu_736_p2 = (or_ln191_8_fu_730_p2 ^ 1'd1);

assign xor_ln191_11_fu_848_p2 = (tmp_107_fu_840_p3 ^ 1'd1);

assign xor_ln191_12_fu_914_p2 = (tmp_108_fu_860_p3 ^ 1'd1);

assign xor_ln191_13_fu_934_p2 = (select_ln191_6_fu_906_p3 ^ 1'd1);

assign xor_ln191_14_fu_946_p2 = (tmp_104_fu_796_p3 ^ 1'd1);

assign xor_ln191_15_fu_973_p2 = (or_ln191_9_fu_968_p2 ^ 1'd1);

assign xor_ln191_1_fu_468_p2 = (tmp_96_reg_1545 ^ 1'd1);

assign xor_ln191_2_fu_479_p2 = (tmp_96_reg_1545 ^ or_ln191_6_fu_473_p2);

assign xor_ln191_3_fu_489_p2 = (xor_ln191_2_fu_479_p2 ^ 1'd1);

assign xor_ln191_4_fu_484_p2 = (tmp_96_reg_1545 ^ and_ln191_fu_463_p2);

assign xor_ln191_5_fu_519_p2 = (or_ln191_7_fu_513_p2 ^ 1'd1);

assign xor_ln191_6_fu_653_p2 = (tmp_102_fu_645_p3 ^ 1'd1);

assign xor_ln191_7_fu_678_p2 = (tmp_103_fu_665_p3 ^ 1'd1);

assign xor_ln191_8_fu_701_p2 = (select_ln191_2_fu_672_p3 ^ 1'd1);

assign xor_ln191_9_fu_713_p2 = (tmp_99_reg_1586 ^ 1'd1);

assign xor_ln191_fu_457_p2 = (tmp_98_fu_449_p3 ^ 1'd1);

assign xor_ln196_1_fu_1151_p2 = (tmp_113_fu_1097_p3 ^ 1'd1);

assign xor_ln196_2_fu_1177_p2 = (select_ln196_fu_1143_p3 ^ 1'd1);

assign xor_ln196_3_fu_1189_p2 = (tmp_109_fu_1033_p3 ^ 1'd1);

assign xor_ln196_4_fu_1213_p2 = (or_ln196_2_fu_1207_p2 ^ 1'd1);

assign xor_ln196_fu_1085_p2 = (tmp_112_fu_1077_p3 ^ 1'd1);

assign xor_ln198_fu_1381_p2 = (or_ln198_fu_1376_p2 ^ 1'd1);

assign xor_ln202_fu_1425_p2 = (or_ln202_3_fu_1419_p2 ^ 1'd1);

assign xor_ln206_1_fu_1348_p2 = (or_ln206_fu_1330_p2 ^ 1'd1);

assign xor_ln206_fu_1336_p2 = (tmp_115_fu_1266_p3 ^ 1'd1);

assign y_30_fu_381_p3 = ((or_ln183_1_fu_376_p2[0:0] == 1'b1) ? select_ln183_1_fu_369_p3 : y_fu_346_p3);

assign y_fu_346_p3 = {{tmp_fu_337_p4}, {1'd0}};

assign z_fu_240_p2 = (trunc_ln_reg_1489 + zext_ln182_1_fu_237_p1);

assign zext_ln182_1_fu_237_p1 = tmp_91_reg_1494;

assign zext_ln183_fu_281_p1 = shl_ln183_1_fu_273_p3;

assign zext_ln191_1_fu_637_p1 = tmp_100_reg_1597;

assign zext_ln191_2_fu_830_p1 = tmp_105_fu_814_p3;

assign zext_ln191_fu_436_p1 = tmp_97_reg_1559;

assign zext_ln196_fu_1067_p1 = tmp_110_fu_1051_p3;

assign zext_ln206_fu_1300_p1 = tmp_116_fu_1284_p3;

always @ (posedge ap_clk) begin
    add_ln183_reg_1499[36:0] <= 37'b0000000000000000000000000000000000000;
    shl_ln2_reg_1530[36:0] <= 37'b0000000000000000000000000000000000000;
    sext_ln191_1_reg_1570[36:0] <= 37'b0000000000000000000000000000000000000;
end

endmodule //uniform_move_operation_chebyshev_g
