// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module local_spin_flip_operation_spin_value (
        ap_ready,
        b,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [0:0] b;
output  [8:0] ap_return;
input   ap_rst;

assign ap_ready = 1'b1;

assign ap_return = ((b[0:0] == 1'b1) ? 9'd255 : 9'd256);

endmodule //local_spin_flip_operation_spin_value
