// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module local_spin_flip_operation_selected_field (
        ap_ready,
        h_0_val,
        h_1_val,
        h_2_val,
        h_3_val,
        h_4_val,
        h_5_val,
        h_6_val,
        h_7_val,
        flip_mask,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [8:0] h_0_val;
input  [8:0] h_1_val;
input  [8:0] h_2_val;
input  [8:0] h_3_val;
input  [8:0] h_4_val;
input  [8:0] h_5_val;
input  [8:0] h_6_val;
input  [8:0] h_7_val;
input  [7:0] flip_mask;
output  [8:0] ap_return;
input   ap_rst;

wire   [0:0] tmp_18_fu_146_p3;
wire   [0:0] tmp_17_fu_138_p3;
wire   [0:0] tmp_16_fu_130_p3;
wire   [0:0] tmp_15_fu_122_p3;
wire   [0:0] tmp_14_fu_114_p3;
wire   [0:0] tmp_13_fu_106_p3;
wire   [0:0] tmp_fu_98_p3;
wire   [0:0] trunc_ln135_fu_94_p1;
wire   [0:0] or_ln135_fu_162_p2;
wire   [8:0] select_ln135_fu_154_p3;
wire   [8:0] select_ln135_1_fu_168_p3;
wire   [0:0] or_ln135_1_fu_176_p2;
wire   [0:0] or_ln135_2_fu_190_p2;
wire   [8:0] select_ln135_2_fu_182_p3;
wire   [8:0] select_ln135_3_fu_196_p3;
wire   [0:0] or_ln135_3_fu_204_p2;
wire   [0:0] or_ln135_4_fu_218_p2;
wire   [8:0] select_ln135_4_fu_210_p3;
wire   [8:0] select_ln135_5_fu_224_p3;
wire   [0:0] or_ln135_5_fu_232_p2;
wire   [0:0] or_ln135_6_fu_246_p2;
wire   [8:0] select_ln135_6_fu_238_p3;

assign ap_ready = 1'b1;

assign or_ln135_1_fu_176_p2 = (tmp_16_fu_130_p3 | tmp_15_fu_122_p3);

assign or_ln135_2_fu_190_p2 = (tmp_14_fu_114_p3 | tmp_13_fu_106_p3);

assign or_ln135_3_fu_204_p2 = (trunc_ln135_fu_94_p1 | tmp_fu_98_p3);

assign or_ln135_4_fu_218_p2 = (or_ln135_fu_162_p2 | or_ln135_1_fu_176_p2);

assign or_ln135_5_fu_232_p2 = (or_ln135_3_fu_204_p2 | or_ln135_2_fu_190_p2);

assign or_ln135_6_fu_246_p2 = (or_ln135_5_fu_232_p2 | or_ln135_4_fu_218_p2);

assign or_ln135_fu_162_p2 = (tmp_18_fu_146_p3 | tmp_17_fu_138_p3);

assign select_ln135_1_fu_168_p3 = ((tmp_16_fu_130_p3[0:0] == 1'b1) ? h_5_val : h_4_val);

assign select_ln135_2_fu_182_p3 = ((tmp_14_fu_114_p3[0:0] == 1'b1) ? h_3_val : h_2_val);

assign select_ln135_3_fu_196_p3 = ((tmp_fu_98_p3[0:0] == 1'b1) ? h_1_val : h_0_val);

assign select_ln135_4_fu_210_p3 = ((or_ln135_fu_162_p2[0:0] == 1'b1) ? select_ln135_fu_154_p3 : select_ln135_1_fu_168_p3);

assign select_ln135_5_fu_224_p3 = ((or_ln135_2_fu_190_p2[0:0] == 1'b1) ? select_ln135_2_fu_182_p3 : select_ln135_3_fu_196_p3);

assign select_ln135_6_fu_238_p3 = ((or_ln135_4_fu_218_p2[0:0] == 1'b1) ? select_ln135_4_fu_210_p3 : select_ln135_5_fu_224_p3);

assign select_ln135_fu_154_p3 = ((tmp_18_fu_146_p3[0:0] == 1'b1) ? h_7_val : h_6_val);

assign tmp_13_fu_106_p3 = flip_mask[32'd2];

assign tmp_14_fu_114_p3 = flip_mask[32'd3];

assign tmp_15_fu_122_p3 = flip_mask[32'd4];

assign tmp_16_fu_130_p3 = flip_mask[32'd5];

assign tmp_17_fu_138_p3 = flip_mask[32'd6];

assign tmp_18_fu_146_p3 = flip_mask[32'd7];

assign tmp_fu_98_p3 = flip_mask[32'd1];

assign trunc_ln135_fu_94_p1 = flip_mask[0:0];

assign ap_return = ((or_ln135_6_fu_246_p2[0:0] == 1'b1) ? select_ln135_6_fu_238_p3 : 9'd0);

endmodule //local_spin_flip_operation_selected_field
