// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module local_spin_flip_operation_positive_part (
        ap_ready,
        delta_over_alpha,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [8:0] delta_over_alpha;
output  [7:0] ap_return;
input   ap_rst;

wire   [0:0] tmp_fu_20_p3;
wire   [7:0] trunc_ln220_fu_16_p1;

assign ap_ready = 1'b1;

assign tmp_fu_20_p3 = delta_over_alpha[32'd8];

assign trunc_ln220_fu_16_p1 = delta_over_alpha[7:0];

assign ap_return = ((tmp_fu_20_p3[0:0] == 1'b1) ? 8'd0 : trunc_ln220_fu_16_p1);

endmodule //local_spin_flip_operation_positive_part
