// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module local_spin_flip_operation_tree_sum_3_s (
        ap_ready,
        x_0_val,
        x_1_val,
        x_2_val,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [8:0] x_0_val;
input  [8:0] x_1_val;
input  [8:0] x_2_val;
output  [8:0] ap_return;
input   ap_rst;

wire    tmp_3_tree_sum_2_s_fu_42_ap_ready;
wire   [8:0] tmp_3_tree_sum_2_s_fu_42_x_0_val;
wire   [8:0] tmp_3_tree_sum_2_s_fu_42_ap_return;
wire  signed [8:0] sext_ln104_fu_49_p0;
wire  signed [8:0] sext_ln104_11_fu_53_p0;
wire  signed [8:0] add_ln104_fu_57_p0;
wire  signed [8:0] add_ln104_fu_57_p1;
wire  signed [9:0] sext_ln104_11_fu_53_p1;
wire  signed [9:0] sext_ln104_fu_49_p1;
wire   [9:0] add_ln104_11_fu_63_p2;
wire   [8:0] add_ln104_fu_57_p2;
wire   [0:0] tmp_fu_69_p3;
wire   [0:0] tmp_11_fu_77_p3;
wire   [0:0] xor_ln104_fu_85_p2;
wire   [0:0] and_ln104_fu_91_p2;
wire   [0:0] xor_ln104_11_fu_97_p2;
wire   [8:0] select_ln104_fu_103_p3;

local_spin_flip_operation_tree_sum_2_s tmp_3_tree_sum_2_s_fu_42(
    .ap_ready(tmp_3_tree_sum_2_s_fu_42_ap_ready),
    .x_0_val(tmp_3_tree_sum_2_s_fu_42_x_0_val),
    .x_1_val(x_2_val),
    .ap_return(tmp_3_tree_sum_2_s_fu_42_ap_return),
    .ap_rst(ap_rst)
);

assign add_ln104_11_fu_63_p2 = ($signed(sext_ln104_11_fu_53_p1) + $signed(sext_ln104_fu_49_p1));

assign add_ln104_fu_57_p2 = ($signed(add_ln104_fu_57_p0) + $signed(add_ln104_fu_57_p1));

assign and_ln104_fu_91_p2 = (xor_ln104_fu_85_p2 & tmp_11_fu_77_p3);

assign ap_ready = 1'b1;

assign select_ln104_fu_103_p3 = ((and_ln104_fu_91_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign sext_ln104_11_fu_53_p1 = sext_ln104_11_fu_53_p0;

assign sext_ln104_fu_49_p1 = sext_ln104_fu_49_p0;

assign tmp_11_fu_77_p3 = add_ln104_fu_57_p2[32'd8];

assign tmp_fu_69_p3 = add_ln104_11_fu_63_p2[32'd9];

assign xor_ln104_11_fu_97_p2 = (tmp_fu_69_p3 ^ tmp_11_fu_77_p3);

assign xor_ln104_fu_85_p2 = (tmp_fu_69_p3 ^ 1'd1);

assign add_ln104_fu_57_p0 = x_1_val;

assign add_ln104_fu_57_p1 = x_0_val;

assign ap_return = tmp_3_tree_sum_2_s_fu_42_ap_return;

assign sext_ln104_11_fu_53_p0 = x_1_val;

assign sext_ln104_fu_49_p0 = x_0_val;

assign tmp_3_tree_sum_2_s_fu_42_x_0_val = ((xor_ln104_11_fu_97_p2[0:0] == 1'b1) ? select_ln104_fu_103_p3 : add_ln104_fu_57_p2);

endmodule //local_spin_flip_operation_tree_sum_3_s
