// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="local_spin_flip_operation_local_spin_flip_operation,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu19p-fsva3824-2-e,HLS_INPUT_CLOCK=3.333000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.392500,HLS_SYN_LAT=56,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=4447,HLS_SYN_LUT=9589,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module local_spin_flip_operation (
        ap_clk,
        ap_rst,
        h_0,
        h_1,
        h_2,
        h_3,
        h_4,
        h_5,
        h_6,
        h_7,
        J_edges_0,
        J_edges_1,
        J_edges_2,
        J_edges_3,
        J_edges_4,
        J_edges_5,
        J_edges_6,
        J_edges_7,
        J_edges_8,
        J_edges_9,
        J_edges_10,
        J_edges_11,
        J_edges_12,
        J_edges_13,
        J_edges_14,
        J_edges_15,
        J_edges_16,
        J_edges_17,
        J_edges_18,
        J_edges_19,
        J_edges_20,
        J_edges_21,
        J_edges_22,
        J_edges_23,
        J_edges_24,
        J_edges_25,
        J_edges_26,
        J_edges_27,
        spins,
        flip_mask,
        delta_x,
        accept_prob
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input  [8:0] h_0;
input  [8:0] h_1;
input  [8:0] h_2;
input  [8:0] h_3;
input  [8:0] h_4;
input  [8:0] h_5;
input  [8:0] h_6;
input  [8:0] h_7;
input  [8:0] J_edges_0;
input  [8:0] J_edges_1;
input  [8:0] J_edges_2;
input  [8:0] J_edges_3;
input  [8:0] J_edges_4;
input  [8:0] J_edges_5;
input  [8:0] J_edges_6;
input  [8:0] J_edges_7;
input  [8:0] J_edges_8;
input  [8:0] J_edges_9;
input  [8:0] J_edges_10;
input  [8:0] J_edges_11;
input  [8:0] J_edges_12;
input  [8:0] J_edges_13;
input  [8:0] J_edges_14;
input  [8:0] J_edges_15;
input  [8:0] J_edges_16;
input  [8:0] J_edges_17;
input  [8:0] J_edges_18;
input  [8:0] J_edges_19;
input  [8:0] J_edges_20;
input  [8:0] J_edges_21;
input  [8:0] J_edges_22;
input  [8:0] J_edges_23;
input  [8:0] J_edges_24;
input  [8:0] J_edges_25;
input  [8:0] J_edges_26;
input  [8:0] J_edges_27;
input  [7:0] spins;
input  [7:0] flip_mask;
output  [8:0] delta_x;
output  [31:0] accept_prob;

reg   [7:0] flip_mask_read_reg_452;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] spins_read_reg_457;
reg   [8:0] h_0_read_reg_462;
reg   [8:0] h_1_read_reg_467;
reg   [8:0] h_2_read_reg_472;
reg   [8:0] h_3_read_reg_477;
reg   [8:0] h_4_read_reg_482;
reg   [8:0] h_5_read_reg_487;
reg   [8:0] h_6_read_reg_492;
reg   [8:0] h_7_read_reg_497;
reg   [8:0] J_edges_0_read_reg_502;
reg   [8:0] J_edges_1_read_reg_507;
reg   [8:0] J_edges_2_read_reg_512;
reg   [8:0] J_edges_3_read_reg_517;
reg   [8:0] J_edges_4_read_reg_522;
reg   [8:0] J_edges_5_read_reg_527;
reg   [8:0] J_edges_6_read_reg_532;
reg   [8:0] J_edges_7_read_reg_537;
reg   [8:0] J_edges_8_read_reg_542;
reg   [8:0] J_edges_9_read_reg_547;
reg   [8:0] J_edges_10_read_reg_552;
reg   [8:0] J_edges_11_read_reg_557;
reg   [8:0] J_edges_12_read_reg_562;
reg   [8:0] J_edges_13_read_reg_567;
reg   [8:0] J_edges_14_read_reg_572;
reg   [8:0] J_edges_15_read_reg_577;
reg   [8:0] J_edges_16_read_reg_582;
reg   [8:0] J_edges_17_read_reg_587;
reg   [8:0] J_edges_18_read_reg_592;
reg   [8:0] J_edges_19_read_reg_597;
reg   [8:0] J_edges_20_read_reg_602;
reg   [8:0] J_edges_21_read_reg_607;
reg   [8:0] J_edges_22_read_reg_612;
reg   [8:0] J_edges_23_read_reg_617;
reg   [8:0] J_edges_24_read_reg_622;
reg   [8:0] J_edges_25_read_reg_627;
reg   [8:0] J_edges_26_read_reg_632;
reg   [8:0] J_edges_27_read_reg_637;
wire   [8:0] grp_local_delta_over_alpha_fu_356_ap_return;
reg   [8:0] delta_over_alpha_reg_642;
wire    ap_CS_fsm_state2;
wire   [7:0] x_positive_part_fu_436_ap_return;
reg   [7:0] x_reg_647;
wire    ap_CS_fsm_state3;
wire    grp_local_delta_over_alpha_fu_356_ap_start;
wire    grp_local_delta_over_alpha_fu_356_ap_done;
wire    grp_local_delta_over_alpha_fu_356_ap_idle;
wire    grp_local_delta_over_alpha_fu_356_ap_ready;
wire    x_positive_part_fu_436_ap_ready;
wire    grp_chebyshev_g_fu_441_ap_start;
wire    grp_chebyshev_g_fu_441_ap_done;
wire    grp_chebyshev_g_fu_441_ap_idle;
wire    grp_chebyshev_g_fu_441_ap_ready;
wire   [31:0] grp_chebyshev_g_fu_441_ap_return;
reg    grp_local_delta_over_alpha_fu_356_ap_start_reg;
reg    grp_chebyshev_g_fu_441_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [4:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_local_delta_over_alpha_fu_356_ap_start_reg = 1'b0;
#0 grp_chebyshev_g_fu_441_ap_start_reg = 1'b0;
end

local_spin_flip_operation_local_delta_over_alpha grp_local_delta_over_alpha_fu_356(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_local_delta_over_alpha_fu_356_ap_start),
    .ap_done(grp_local_delta_over_alpha_fu_356_ap_done),
    .ap_idle(grp_local_delta_over_alpha_fu_356_ap_idle),
    .ap_ready(grp_local_delta_over_alpha_fu_356_ap_ready),
    .h_0_val1(h_0_read_reg_462),
    .h_1_val2(h_1_read_reg_467),
    .h_2_val3(h_2_read_reg_472),
    .h_3_val4(h_3_read_reg_477),
    .h_4_val5(h_4_read_reg_482),
    .h_5_val6(h_5_read_reg_487),
    .h_6_val7(h_6_read_reg_492),
    .h_7_val8(h_7_read_reg_497),
    .J_edges_0_val16(J_edges_0_read_reg_502),
    .J_edges_1_val24(J_edges_1_read_reg_507),
    .J_edges_2_val32(J_edges_2_read_reg_512),
    .J_edges_3_val40(J_edges_3_read_reg_517),
    .J_edges_4_val48(J_edges_4_read_reg_522),
    .J_edges_5_val56(J_edges_5_read_reg_527),
    .J_edges_6_val64(J_edges_6_read_reg_532),
    .J_edges_7_val72(J_edges_7_read_reg_537),
    .J_edges_8_val80(J_edges_8_read_reg_542),
    .J_edges_9_val88(J_edges_9_read_reg_547),
    .J_edges_10_val96(J_edges_10_read_reg_552),
    .J_edges_11_val104(J_edges_11_read_reg_557),
    .J_edges_12_val112(J_edges_12_read_reg_562),
    .J_edges_13_val120(J_edges_13_read_reg_567),
    .J_edges_14_val128(J_edges_14_read_reg_572),
    .J_edges_15_val136(J_edges_15_read_reg_577),
    .J_edges_16_val144(J_edges_16_read_reg_582),
    .J_edges_17_val152(J_edges_17_read_reg_587),
    .J_edges_18_val160(J_edges_18_read_reg_592),
    .J_edges_19_val168(J_edges_19_read_reg_597),
    .J_edges_20_val176(J_edges_20_read_reg_602),
    .J_edges_21_val184(J_edges_21_read_reg_607),
    .J_edges_22_val192(J_edges_22_read_reg_612),
    .J_edges_23_val200(J_edges_23_read_reg_617),
    .J_edges_24_val208(J_edges_24_read_reg_622),
    .J_edges_25_val216(J_edges_25_read_reg_627),
    .J_edges_26_val224(J_edges_26_read_reg_632),
    .J_edges_27_val232(J_edges_27_read_reg_637),
    .spins(spins_read_reg_457),
    .flip_mask(flip_mask_read_reg_452),
    .ap_return(grp_local_delta_over_alpha_fu_356_ap_return)
);

local_spin_flip_operation_positive_part x_positive_part_fu_436(
    .ap_ready(x_positive_part_fu_436_ap_ready),
    .delta_over_alpha(delta_over_alpha_reg_642),
    .ap_return(x_positive_part_fu_436_ap_return),
    .ap_rst(ap_rst)
);

local_spin_flip_operation_chebyshev_g grp_chebyshev_g_fu_441(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_chebyshev_g_fu_441_ap_start),
    .ap_done(grp_chebyshev_g_fu_441_ap_done),
    .ap_idle(grp_chebyshev_g_fu_441_ap_idle),
    .ap_ready(grp_chebyshev_g_fu_441_ap_ready),
    .x(x_reg_647),
    .ap_return(grp_chebyshev_g_fu_441_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_chebyshev_g_fu_441_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_chebyshev_g_fu_441_ap_start_reg <= 1'b1;
        end else if ((grp_chebyshev_g_fu_441_ap_ready == 1'b1)) begin
            grp_chebyshev_g_fu_441_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_local_delta_over_alpha_fu_356_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            grp_local_delta_over_alpha_fu_356_ap_start_reg <= 1'b1;
        end else if ((grp_local_delta_over_alpha_fu_356_ap_ready == 1'b1)) begin
            grp_local_delta_over_alpha_fu_356_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        J_edges_0_read_reg_502 <= J_edges_0;
        J_edges_10_read_reg_552 <= J_edges_10;
        J_edges_11_read_reg_557 <= J_edges_11;
        J_edges_12_read_reg_562 <= J_edges_12;
        J_edges_13_read_reg_567 <= J_edges_13;
        J_edges_14_read_reg_572 <= J_edges_14;
        J_edges_15_read_reg_577 <= J_edges_15;
        J_edges_16_read_reg_582 <= J_edges_16;
        J_edges_17_read_reg_587 <= J_edges_17;
        J_edges_18_read_reg_592 <= J_edges_18;
        J_edges_19_read_reg_597 <= J_edges_19;
        J_edges_1_read_reg_507 <= J_edges_1;
        J_edges_20_read_reg_602 <= J_edges_20;
        J_edges_21_read_reg_607 <= J_edges_21;
        J_edges_22_read_reg_612 <= J_edges_22;
        J_edges_23_read_reg_617 <= J_edges_23;
        J_edges_24_read_reg_622 <= J_edges_24;
        J_edges_25_read_reg_627 <= J_edges_25;
        J_edges_26_read_reg_632 <= J_edges_26;
        J_edges_27_read_reg_637 <= J_edges_27;
        J_edges_2_read_reg_512 <= J_edges_2;
        J_edges_3_read_reg_517 <= J_edges_3;
        J_edges_4_read_reg_522 <= J_edges_4;
        J_edges_5_read_reg_527 <= J_edges_5;
        J_edges_6_read_reg_532 <= J_edges_6;
        J_edges_7_read_reg_537 <= J_edges_7;
        J_edges_8_read_reg_542 <= J_edges_8;
        J_edges_9_read_reg_547 <= J_edges_9;
        flip_mask_read_reg_452 <= flip_mask;
        h_0_read_reg_462 <= h_0;
        h_1_read_reg_467 <= h_1;
        h_2_read_reg_472 <= h_2;
        h_3_read_reg_477 <= h_3;
        h_4_read_reg_482 <= h_4;
        h_5_read_reg_487 <= h_5;
        h_6_read_reg_492 <= h_6;
        h_7_read_reg_497 <= h_7;
        spins_read_reg_457 <= spins;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        delta_over_alpha_reg_642 <= grp_local_delta_over_alpha_fu_356_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_reg_647 <= x_positive_part_fu_436_ap_return;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if ((grp_local_delta_over_alpha_fu_356_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_chebyshev_g_fu_441_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_local_delta_over_alpha_fu_356_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_chebyshev_g_fu_441_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign accept_prob = grp_chebyshev_g_fu_441_ap_return;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign delta_x = x_positive_part_fu_436_ap_return;

assign grp_chebyshev_g_fu_441_ap_start = grp_chebyshev_g_fu_441_ap_start_reg;

assign grp_local_delta_over_alpha_fu_356_ap_start = grp_local_delta_over_alpha_fu_356_ap_start_reg;

endmodule //local_spin_flip_operation
