#pragma once

// Generated by make_exp_cheby.py.
// n = 10
// beta = 4
// alpha = (2/sqrt(pi))*n^(3/2) = 3.56824823230554244e+01
// lambda = beta*alpha = 1.42729929292221698e+02
// Coefficients approximate exp(-lambda*x) on x in [0,1].

static const int POLY_DEGREE = 12;

static const poly_t CHEB_COEFFS[POLY_DEGREE + 1] = {
    poly_t(4.73078967411226722e-02), // c[0]
    poly_t(-9.39505371229757830e-02), // c[1]
    poly_t(9.19828338054946293e-02), // c[2]
    poly_t(-8.87949073675838862e-02), // c[3]
    poly_t(8.45174136676520166e-02), // c[4]
    poly_t(-7.93205201427866907e-02), // c[5]
    poly_t(7.34026432006411600e-02), // c[6]
    poly_t(-6.69778850307871654e-02), // c[7]
    poly_t(6.02632771954746196e-02), // c[8]
    poly_t(-5.34668794567075903e-02), // c[9]
    poly_t(4.67776146579372484e-02), // c[10]
    poly_t(-4.03574734926183398e-02), // c[11]
    poly_t(3.43364340136196253e-02) // c[12]
};
