#pragma once

// Generated by make_exp_cheby.py.
// n = 20
// beta = 100
// alpha = (2/sqrt(pi))*n^(3/2) = 1.00925300880806404e+02
// lambda = beta*alpha = 1.00925300880806408e+04
// Coefficients approximate exp(-lambda*x) on x in [0,1].

static const int POLY_DEGREE = 12;

static const poly_t CHEB_COEFFS[POLY_DEGREE + 1] = {
    poly_t(5.61611246493641091e-03), // c[0]
    poly_t(-1.12311119501339006e-02), // c[1]
    poly_t(1.12277736726153765e-02), // c[2]
    poly_t(-1.12222120817562949e-02), // c[3]
    poly_t(1.12144304827704305e-02), // c[4]
    poly_t(-1.12044334983725097e-02), // c[5]
    poly_t(1.11922270642012770e-02), // c[6]
    poly_t(-1.11778184229457764e-02), // c[7]
    poly_t(1.11612161171829351e-02), // c[8]
    poly_t(-1.11424299809364073e-02), // c[9]
    poly_t(1.11214711299683355e-02), // c[10]
    poly_t(-1.10983519508174658e-02), // c[11]
    poly_t(1.10730860885987128e-02) // c[12]
};
