#!/usr/bin/env python3
import argparse
import numpy as np
from scipy.special import ive

def cheb_coeffs_exp_neg(lam: float, polynomial_degree: int) -> np.ndarray:
    # Chebyshev series of exp(-lam*x) on x in [0,1].
    # With y=2x-1, exp(-lam*x)=exp(-lam/2) exp(-(lam/2)y).
    k = np.arange(polynomial_degree + 1)
    a = lam / 2.0
    c = 2.0 * ((-1.0) ** k) * ive(k, a)
    c[0] /= 2.0
    return c

def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--n", type=int, required=True)
    p.add_argument("--beta", type=float, required=True)
    p.add_argument("--degree", type=int, default=12, help="Polynomial degree.")
    p.add_argument("--out", type=str, default="exp_cheby.hpp")
    args = p.parse_args()

    alpha = 2.0 / np.sqrt(np.pi) * args.n ** 1.5
    lam = args.beta * alpha
    polynomial_degree = args.degree
    coeffs = cheb_coeffs_exp_neg(lam, polynomial_degree)

    with open(args.out, "w") as f:
        f.write("#pragma once\n\n")
        f.write("// Generated by make_exp_cheby.py.\n")
        f.write(f"// n = {args.n}\n")
        f.write(f"// beta = {args.beta:.17g}\n")
        f.write(f"// alpha = (2/sqrt(pi))*n^(3/2) = {alpha:.17e}\n")
        f.write(f"// lambda = beta*alpha = {lam:.17e}\n")
        f.write("// Coefficients approximate exp(-lambda*x) on x in [0,1].\n\n")
        f.write(f"static const int POLY_DEGREE = {polynomial_degree};\n\n")
        f.write("static const poly_t CHEB_COEFFS[POLY_DEGREE + 1] = {\n")
        for i, c in enumerate(coeffs):
            comma = "," if i < polynomial_degree else ""
            f.write(f"    poly_t({c:.17e}){comma} // c[{i}]\n")
        f.write("};\n")

if __name__ == "__main__":
    main()
