#!/usr/bin/env python3
import argparse
import numpy as np
from scipy.special import ive

def cheb_coeffs_exp_tail(tau: float, polynomial_degree: int) -> np.ndarray:
    # Chebyshev series of exp(-u) on u in [0,tau].
    # With y=2u/tau-1, exp(-u)=exp(-tau/2) exp(-(tau/2)y).
    k = np.arange(polynomial_degree + 1)
    a = tau / 2.0
    c = 2.0 * ((-1.0) ** k) * ive(k, a)
    c[0] /= 2.0
    return c

def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--n", type=int, required=True)
    p.add_argument("--beta", type=float, required=True)
    p.add_argument("--degree", type=int, default=12, help="Polynomial degree.")
    p.add_argument("--eps-op", type=float, default=1e-4, help="Total operation error budget.")
    p.add_argument("--out", type=str, default="exp_cheby.hpp")
    args = p.parse_args()

    alpha = 2.0 / np.sqrt(np.pi) * args.n ** 1.5
    lam = args.beta * alpha
    eps_tail = args.eps_op / 2.0
    tau = np.log(1.0 / eps_tail)
    x_cut = tau / lam
    inv_x_cut = lam / tau

    coeffs = cheb_coeffs_exp_tail(tau, args.degree)

    with open(args.out, "w") as f:
        f.write("#pragma once\n\n")
        f.write("// Generated by make_exp_cheby.py.\n")
        f.write("// Piecewise approximation:\n")
        f.write("//   g(x)=1 for x<=0,\n")
        f.write("//   g(x)=p_d(2*x/x_cut-1) for 0<x<x_cut,\n")
        f.write("//   g(x)=0 for x>=x_cut.\n")
        f.write(f"// n = {args.n}\n")
        f.write(f"// beta = {args.beta:.17g}\n")
        f.write(f"// degree = {args.degree}\n")
        f.write(f"// eps_op = {args.eps_op:.17e}\n")
        f.write(f"// eps_tail = eps_op/2 = {eps_tail:.17e}\n")
        f.write(f"// alpha = (2/sqrt(pi))*n^(3/2) = {alpha:.17e}\n")
        f.write(f"// lambda = beta*alpha = {lam:.17e}\n")
        f.write(f"// tau = log(1/eps_tail) = {tau:.17e}\n")
        f.write(f"// x_cut = tau/lambda = {x_cut:.17e}\n\n")
        f.write(f"static const int POLY_DEGREE = {args.degree};\n")
        f.write(f"static const delta_t EXP_X_CUT = delta_t({x_cut:.17e});\n")
        f.write(f"static const poly_t EXP_INV_X_CUT = poly_t({inv_x_cut:.17e});\n\n")
        f.write("// Coefficients approximate exp(-u) on u in [0,tau], with y=2u/tau-1.\n")
        f.write("static const poly_t CHEB_COEFFS[POLY_DEGREE + 1] = {\n")
        for i, c in enumerate(coeffs):
            comma = "," if i < args.degree else ""
            f.write(f"    poly_t({c:.17e}){comma} // c[{i}]\n")
        f.write("};\n")

if __name__ == "__main__":
    main()
