// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module uniform_move_operation_positive_part (
        ap_ready,
        delta_over_alpha,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [8:0] delta_over_alpha;
output  [7:0] ap_return;
input   ap_rst;

wire   [0:0] icmp_ln159_fu_18_p2;
wire   [7:0] trunc_ln157_fu_14_p1;

assign ap_ready = 1'b1;

assign trunc_ln157_fu_14_p1 = delta_over_alpha[7:0];

assign ap_return = ((icmp_ln159_fu_18_p2[0:0] == 1'b1) ? trunc_ln157_fu_14_p1 : 8'd0);

assign icmp_ln159_fu_18_p2 = (($signed(delta_over_alpha) > $signed(9'd0)) ? 1'b1 : 1'b0);

endmodule //uniform_move_operation_positive_part
