// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module uniform_move_operation_tree_sum_9_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_0_val,
        x_1_val,
        x_2_val,
        x_3_val,
        x_4_val,
        x_5_val,
        x_6_val,
        x_7_val,
        x_8_val,
        ap_return
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] x_0_val;
input  [8:0] x_1_val;
input  [8:0] x_2_val;
input  [8:0] x_3_val;
input  [8:0] x_4_val;
input  [8:0] x_5_val;
input  [8:0] x_6_val;
input  [8:0] x_7_val;
input  [8:0] x_8_val;
output  [8:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[8:0] ap_return;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [8:0] y_fu_162_p3;
reg   [8:0] y_reg_380;
wire   [8:0] y_1_fu_232_p3;
reg   [8:0] y_1_reg_385;
wire   [8:0] y_2_fu_302_p3;
reg   [8:0] y_2_reg_390;
wire   [8:0] y_3_fu_372_p3;
reg   [8:0] y_3_reg_395;
wire    ap_CS_fsm_state2;
wire    grp_tree_sum_5_s_fu_90_ap_start;
wire    grp_tree_sum_5_s_fu_90_ap_done;
wire    grp_tree_sum_5_s_fu_90_ap_idle;
wire    grp_tree_sum_5_s_fu_90_ap_ready;
wire   [8:0] grp_tree_sum_5_s_fu_90_ap_return;
reg    grp_tree_sum_5_s_fu_90_ap_start_reg;
wire    ap_CS_fsm_state3;
wire  signed [8:0] sext_ln90_fu_100_p0;
wire  signed [8:0] sext_ln90_1_fu_104_p0;
wire  signed [8:0] add_ln90_fu_108_p0;
wire  signed [8:0] add_ln90_fu_108_p1;
wire  signed [9:0] sext_ln90_1_fu_104_p1;
wire  signed [9:0] sext_ln90_fu_100_p1;
wire   [9:0] add_ln90_1_fu_114_p2;
wire   [8:0] add_ln90_fu_108_p2;
wire   [0:0] tmp_fu_120_p3;
wire   [0:0] tmp_2_fu_128_p3;
wire   [0:0] xor_ln90_fu_136_p2;
wire   [0:0] and_ln90_fu_142_p2;
wire   [0:0] xor_ln90_1_fu_148_p2;
wire   [8:0] select_ln90_fu_154_p3;
wire  signed [8:0] sext_ln90_2_fu_170_p0;
wire  signed [8:0] sext_ln90_3_fu_174_p0;
wire  signed [8:0] add_ln90_2_fu_178_p0;
wire  signed [8:0] add_ln90_2_fu_178_p1;
wire  signed [9:0] sext_ln90_3_fu_174_p1;
wire  signed [9:0] sext_ln90_2_fu_170_p1;
wire   [9:0] add_ln90_3_fu_184_p2;
wire   [8:0] add_ln90_2_fu_178_p2;
wire   [0:0] tmp_3_fu_190_p3;
wire   [0:0] tmp_4_fu_198_p3;
wire   [0:0] xor_ln90_2_fu_206_p2;
wire   [0:0] and_ln90_1_fu_212_p2;
wire   [0:0] xor_ln90_3_fu_218_p2;
wire   [8:0] select_ln90_2_fu_224_p3;
wire  signed [8:0] sext_ln90_4_fu_240_p0;
wire  signed [8:0] sext_ln90_5_fu_244_p0;
wire  signed [8:0] add_ln90_4_fu_248_p0;
wire  signed [8:0] add_ln90_4_fu_248_p1;
wire  signed [9:0] sext_ln90_5_fu_244_p1;
wire  signed [9:0] sext_ln90_4_fu_240_p1;
wire   [9:0] add_ln90_5_fu_254_p2;
wire   [8:0] add_ln90_4_fu_248_p2;
wire   [0:0] tmp_5_fu_260_p3;
wire   [0:0] tmp_6_fu_268_p3;
wire   [0:0] xor_ln90_4_fu_276_p2;
wire   [0:0] and_ln90_2_fu_282_p2;
wire   [0:0] xor_ln90_5_fu_288_p2;
wire   [8:0] select_ln90_4_fu_294_p3;
wire  signed [8:0] sext_ln90_6_fu_310_p0;
wire  signed [8:0] sext_ln90_7_fu_314_p0;
wire  signed [8:0] add_ln90_6_fu_318_p0;
wire  signed [8:0] add_ln90_6_fu_318_p1;
wire  signed [9:0] sext_ln90_7_fu_314_p1;
wire  signed [9:0] sext_ln90_6_fu_310_p1;
wire   [9:0] add_ln90_7_fu_324_p2;
wire   [8:0] add_ln90_6_fu_318_p2;
wire   [0:0] tmp_7_fu_330_p3;
wire   [0:0] tmp_8_fu_338_p3;
wire   [0:0] xor_ln90_6_fu_346_p2;
wire   [0:0] and_ln90_3_fu_352_p2;
wire   [0:0] xor_ln90_7_fu_358_p2;
wire   [8:0] select_ln90_6_fu_364_p3;
reg   [8:0] ap_return_preg;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_tree_sum_5_s_fu_90_ap_start_reg = 1'b0;
#0 ap_return_preg = 9'd0;
end

uniform_move_operation_tree_sum_5_s grp_tree_sum_5_s_fu_90(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tree_sum_5_s_fu_90_ap_start),
    .ap_done(grp_tree_sum_5_s_fu_90_ap_done),
    .ap_idle(grp_tree_sum_5_s_fu_90_ap_idle),
    .ap_ready(grp_tree_sum_5_s_fu_90_ap_ready),
    .x_0_val(y_reg_380),
    .x_1_val(y_1_reg_385),
    .x_2_val(y_2_reg_390),
    .x_3_val(y_3_reg_395),
    .x_4_val(x_8_val),
    .ap_return(grp_tree_sum_5_s_fu_90_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 9'd0;
    end else begin
        if (((grp_tree_sum_5_s_fu_90_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_return_preg <= grp_tree_sum_5_s_fu_90_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tree_sum_5_s_fu_90_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_tree_sum_5_s_fu_90_ap_start_reg <= 1'b1;
        end else if ((grp_tree_sum_5_s_fu_90_ap_ready == 1'b1)) begin
            grp_tree_sum_5_s_fu_90_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        y_1_reg_385 <= y_1_fu_232_p3;
        y_2_reg_390 <= y_2_fu_302_p3;
        y_3_reg_395 <= y_3_fu_372_p3;
        y_reg_380 <= y_fu_162_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_tree_sum_5_s_fu_90_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_tree_sum_5_s_fu_90_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_tree_sum_5_s_fu_90_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_tree_sum_5_s_fu_90_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_return = grp_tree_sum_5_s_fu_90_ap_return;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_tree_sum_5_s_fu_90_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln90_1_fu_114_p2 = ($signed(sext_ln90_1_fu_104_p1) + $signed(sext_ln90_fu_100_p1));

assign add_ln90_2_fu_178_p0 = x_3_val;

assign add_ln90_2_fu_178_p1 = x_2_val;

assign add_ln90_2_fu_178_p2 = ($signed(add_ln90_2_fu_178_p0) + $signed(add_ln90_2_fu_178_p1));

assign add_ln90_3_fu_184_p2 = ($signed(sext_ln90_3_fu_174_p1) + $signed(sext_ln90_2_fu_170_p1));

assign add_ln90_4_fu_248_p0 = x_5_val;

assign add_ln90_4_fu_248_p1 = x_4_val;

assign add_ln90_4_fu_248_p2 = ($signed(add_ln90_4_fu_248_p0) + $signed(add_ln90_4_fu_248_p1));

assign add_ln90_5_fu_254_p2 = ($signed(sext_ln90_5_fu_244_p1) + $signed(sext_ln90_4_fu_240_p1));

assign add_ln90_6_fu_318_p0 = x_7_val;

assign add_ln90_6_fu_318_p1 = x_6_val;

assign add_ln90_6_fu_318_p2 = ($signed(add_ln90_6_fu_318_p0) + $signed(add_ln90_6_fu_318_p1));

assign add_ln90_7_fu_324_p2 = ($signed(sext_ln90_7_fu_314_p1) + $signed(sext_ln90_6_fu_310_p1));

assign add_ln90_fu_108_p0 = x_1_val;

assign add_ln90_fu_108_p1 = x_0_val;

assign add_ln90_fu_108_p2 = ($signed(add_ln90_fu_108_p0) + $signed(add_ln90_fu_108_p1));

assign and_ln90_1_fu_212_p2 = (xor_ln90_2_fu_206_p2 & tmp_4_fu_198_p3);

assign and_ln90_2_fu_282_p2 = (xor_ln90_4_fu_276_p2 & tmp_6_fu_268_p3);

assign and_ln90_3_fu_352_p2 = (xor_ln90_6_fu_346_p2 & tmp_8_fu_338_p3);

assign and_ln90_fu_142_p2 = (xor_ln90_fu_136_p2 & tmp_2_fu_128_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign grp_tree_sum_5_s_fu_90_ap_start = grp_tree_sum_5_s_fu_90_ap_start_reg;

assign select_ln90_2_fu_224_p3 = ((and_ln90_1_fu_212_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_4_fu_294_p3 = ((and_ln90_2_fu_282_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_6_fu_364_p3 = ((and_ln90_3_fu_352_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_fu_154_p3 = ((and_ln90_fu_142_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign sext_ln90_1_fu_104_p0 = x_1_val;

assign sext_ln90_1_fu_104_p1 = sext_ln90_1_fu_104_p0;

assign sext_ln90_2_fu_170_p0 = x_2_val;

assign sext_ln90_2_fu_170_p1 = sext_ln90_2_fu_170_p0;

assign sext_ln90_3_fu_174_p0 = x_3_val;

assign sext_ln90_3_fu_174_p1 = sext_ln90_3_fu_174_p0;

assign sext_ln90_4_fu_240_p0 = x_4_val;

assign sext_ln90_4_fu_240_p1 = sext_ln90_4_fu_240_p0;

assign sext_ln90_5_fu_244_p0 = x_5_val;

assign sext_ln90_5_fu_244_p1 = sext_ln90_5_fu_244_p0;

assign sext_ln90_6_fu_310_p0 = x_6_val;

assign sext_ln90_6_fu_310_p1 = sext_ln90_6_fu_310_p0;

assign sext_ln90_7_fu_314_p0 = x_7_val;

assign sext_ln90_7_fu_314_p1 = sext_ln90_7_fu_314_p0;

assign sext_ln90_fu_100_p0 = x_0_val;

assign sext_ln90_fu_100_p1 = sext_ln90_fu_100_p0;

assign tmp_2_fu_128_p3 = add_ln90_fu_108_p2[32'd8];

assign tmp_3_fu_190_p3 = add_ln90_3_fu_184_p2[32'd9];

assign tmp_4_fu_198_p3 = add_ln90_2_fu_178_p2[32'd8];

assign tmp_5_fu_260_p3 = add_ln90_5_fu_254_p2[32'd9];

assign tmp_6_fu_268_p3 = add_ln90_4_fu_248_p2[32'd8];

assign tmp_7_fu_330_p3 = add_ln90_7_fu_324_p2[32'd9];

assign tmp_8_fu_338_p3 = add_ln90_6_fu_318_p2[32'd8];

assign tmp_fu_120_p3 = add_ln90_1_fu_114_p2[32'd9];

assign xor_ln90_1_fu_148_p2 = (tmp_fu_120_p3 ^ tmp_2_fu_128_p3);

assign xor_ln90_2_fu_206_p2 = (tmp_3_fu_190_p3 ^ 1'd1);

assign xor_ln90_3_fu_218_p2 = (tmp_4_fu_198_p3 ^ tmp_3_fu_190_p3);

assign xor_ln90_4_fu_276_p2 = (tmp_5_fu_260_p3 ^ 1'd1);

assign xor_ln90_5_fu_288_p2 = (tmp_6_fu_268_p3 ^ tmp_5_fu_260_p3);

assign xor_ln90_6_fu_346_p2 = (tmp_7_fu_330_p3 ^ 1'd1);

assign xor_ln90_7_fu_358_p2 = (tmp_8_fu_338_p3 ^ tmp_7_fu_330_p3);

assign xor_ln90_fu_136_p2 = (tmp_fu_120_p3 ^ 1'd1);

assign y_1_fu_232_p3 = ((xor_ln90_3_fu_218_p2[0:0] == 1'b1) ? select_ln90_2_fu_224_p3 : add_ln90_2_fu_178_p2);

assign y_2_fu_302_p3 = ((xor_ln90_5_fu_288_p2[0:0] == 1'b1) ? select_ln90_4_fu_294_p3 : add_ln90_4_fu_248_p2);

assign y_3_fu_372_p3 = ((xor_ln90_7_fu_358_p2[0:0] == 1'b1) ? select_ln90_6_fu_364_p3 : add_ln90_6_fu_318_p2);

assign y_fu_162_p3 = ((xor_ln90_1_fu_148_p2[0:0] == 1'b1) ? select_ln90_fu_154_p3 : add_ln90_fu_108_p2);

endmodule //uniform_move_operation_tree_sum_9_s
