// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module uniform_move_operation_field_delta_term (
        ap_ready,
        a,
        spin_i,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [8:0] a;
input  [0:0] spin_i;
output  [8:0] ap_return;
input   ap_rst;

wire  signed [8:0] sext_ln105_fu_34_p0;
wire  signed [9:0] sext_ln105_fu_34_p1;
wire   [9:0] sub_ln105_fu_38_p2;
wire   [0:0] tmp_fu_48_p3;
wire   [0:0] tmp_67_fu_56_p3;
wire   [0:0] xor_ln105_fu_64_p2;
wire   [0:0] xor_ln105_1_fu_76_p2;
wire   [0:0] xor_ln105_2_fu_88_p2;
wire   [0:0] and_ln105_fu_70_p2;
wire   [0:0] xor_ln105_3_fu_94_p2;
wire   [8:0] neg_x_fu_44_p1;
wire   [0:0] and_ln105_1_fu_82_p2;
wire   [0:0] or_ln105_fu_100_p2;
wire   [8:0] select_ln105_fu_106_p3;
wire   [8:0] select_ln105_1_fu_114_p3;
wire   [8:0] select_ln105_2_fu_122_p3;
wire  signed [8:0] select_ln106_fu_130_p2;

assign and_ln105_1_fu_82_p2 = (xor_ln105_1_fu_76_p2 & tmp_fu_48_p3);

assign and_ln105_fu_70_p2 = (xor_ln105_fu_64_p2 & tmp_67_fu_56_p3);

assign ap_ready = 1'b1;

assign neg_x_fu_44_p1 = sub_ln105_fu_38_p2[8:0];

assign or_ln105_fu_100_p2 = (xor_ln105_3_fu_94_p2 | and_ln105_fu_70_p2);

assign select_ln105_1_fu_114_p3 = ((and_ln105_1_fu_82_p2[0:0] == 1'b1) ? 9'd256 : neg_x_fu_44_p1);

assign select_ln105_2_fu_122_p3 = ((or_ln105_fu_100_p2[0:0] == 1'b1) ? select_ln105_fu_106_p3 : select_ln105_1_fu_114_p3);

assign select_ln105_fu_106_p3 = ((xor_ln105_2_fu_88_p2[0:0] == 1'b1) ? 9'd255 : neg_x_fu_44_p1);

assign sext_ln105_fu_34_p1 = sext_ln105_fu_34_p0;

assign sub_ln105_fu_38_p2 = ($signed(10'd0) - $signed(sext_ln105_fu_34_p1));

assign tmp_67_fu_56_p3 = sub_ln105_fu_38_p2[32'd8];

assign tmp_fu_48_p3 = sub_ln105_fu_38_p2[32'd9];

assign xor_ln105_1_fu_76_p2 = (tmp_67_fu_56_p3 ^ 1'd1);

assign xor_ln105_2_fu_88_p2 = (tmp_fu_48_p3 ^ tmp_67_fu_56_p3);

assign xor_ln105_3_fu_94_p2 = (xor_ln105_2_fu_88_p2 ^ 1'd1);

assign xor_ln105_fu_64_p2 = (tmp_fu_48_p3 ^ 1'd1);

assign ap_return = ((spin_i[0:0] == 1'b1) ? select_ln105_2_fu_122_p3 : select_ln106_fu_130_p2);

assign select_ln106_fu_130_p2 = a;

assign sext_ln105_fu_34_p0 = a;

endmodule //uniform_move_operation_field_delta_term
