// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module uniform_move_operation_pair_delta_term (
        ap_ready,
        Jij,
        spin_i,
        spin_j,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [8:0] Jij;
input  [0:0] spin_i;
input  [0:0] spin_j;
output  [8:0] ap_return;
input   ap_rst;

wire  signed [8:0] sext_ln114_fu_42_p0;
wire  signed [9:0] sext_ln114_fu_42_p1;
wire   [9:0] sub_ln114_fu_46_p2;
wire   [0:0] tmp_fu_56_p3;
wire   [0:0] tmp_66_fu_64_p3;
wire   [0:0] xor_ln114_fu_72_p2;
wire   [0:0] xor_ln114_1_fu_84_p2;
wire   [0:0] xor_ln114_2_fu_96_p2;
wire   [0:0] and_ln114_fu_78_p2;
wire   [0:0] xor_ln114_3_fu_102_p2;
wire   [8:0] neg_x_fu_52_p1;
wire   [0:0] and_ln114_1_fu_90_p2;
wire   [0:0] or_ln114_fu_108_p2;
wire   [8:0] select_ln114_fu_114_p3;
wire   [8:0] select_ln114_1_fu_122_p3;
wire   [0:0] xor_ln115_fu_138_p2;
wire  signed [8:0] select_ln115_fu_144_p1;
wire   [8:0] select_ln114_2_fu_130_p3;

assign and_ln114_1_fu_90_p2 = (xor_ln114_1_fu_84_p2 & tmp_fu_56_p3);

assign and_ln114_fu_78_p2 = (xor_ln114_fu_72_p2 & tmp_66_fu_64_p3);

assign ap_ready = 1'b1;

assign neg_x_fu_52_p1 = sub_ln114_fu_46_p2[8:0];

assign or_ln114_fu_108_p2 = (xor_ln114_3_fu_102_p2 | and_ln114_fu_78_p2);

assign select_ln114_1_fu_122_p3 = ((and_ln114_1_fu_90_p2[0:0] == 1'b1) ? 9'd256 : neg_x_fu_52_p1);

assign select_ln114_2_fu_130_p3 = ((or_ln114_fu_108_p2[0:0] == 1'b1) ? select_ln114_fu_114_p3 : select_ln114_1_fu_122_p3);

assign select_ln114_fu_114_p3 = ((xor_ln114_2_fu_96_p2[0:0] == 1'b1) ? 9'd255 : neg_x_fu_52_p1);

assign sext_ln114_fu_42_p1 = sext_ln114_fu_42_p0;

assign sub_ln114_fu_46_p2 = ($signed(10'd0) - $signed(sext_ln114_fu_42_p1));

assign tmp_66_fu_64_p3 = sub_ln114_fu_46_p2[32'd8];

assign tmp_fu_56_p3 = sub_ln114_fu_46_p2[32'd9];

assign xor_ln114_1_fu_84_p2 = (tmp_66_fu_64_p3 ^ 1'd1);

assign xor_ln114_2_fu_96_p2 = (tmp_fu_56_p3 ^ tmp_66_fu_64_p3);

assign xor_ln114_3_fu_102_p2 = (xor_ln114_2_fu_96_p2 ^ 1'd1);

assign xor_ln114_fu_72_p2 = (tmp_fu_56_p3 ^ 1'd1);

assign xor_ln115_fu_138_p2 = (spin_j ^ spin_i);

assign ap_return = ((xor_ln115_fu_138_p2[0:0] == 1'b1) ? select_ln115_fu_144_p1 : select_ln114_2_fu_130_p3);

assign select_ln115_fu_144_p1 = Jij;

assign sext_ln114_fu_42_p0 = Jij;

endmodule //uniform_move_operation_pair_delta_term
