// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module uniform_move_operation_edge_index (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        i,
        j,
        ap_return
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [2:0] i;
input  [2:0] j;
output  [6:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] a_fu_32_p3;
reg   [2:0] a_reg_103;
wire   [2:0] b_fu_40_p3;
reg   [2:0] b_reg_109;
wire   [0:0] icmp_ln66_fu_26_p2;
wire    ap_CS_fsm_state2;
wire   [3:0] zext_ln66_1_fu_51_p1;
wire  signed [3:0] xor_ln68_fu_57_p2;
wire   [3:0] mul_ln68_fu_67_p0;
wire   [2:0] mul_ln68_fu_67_p1;
wire   [6:0] mul_ln68_fu_67_p2;
wire   [5:0] trunc_ln_fu_73_p4;
wire   [6:0] zext_ln68_1_fu_83_p1;
wire  signed [6:0] sext_ln68_fu_87_p1;
wire   [6:0] add_ln68_fu_91_p2;
wire   [6:0] zext_ln67_fu_54_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire   [6:0] mul_ln68_fu_67_p00;
wire   [6:0] mul_ln68_fu_67_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

uniform_move_operation_mul_4ns_3ns_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
mul_4ns_3ns_7_1_1_U3(
    .din0(mul_ln68_fu_67_p0),
    .din1(mul_ln68_fu_67_p1),
    .dout(mul_ln68_fu_67_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        a_reg_103 <= a_fu_32_p3;
        b_reg_109 <= b_fu_40_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_fu_32_p3 = ((icmp_ln66_fu_26_p2[0:0] == 1'b1) ? i : j);

assign add_ln68_fu_91_p2 = ($signed(zext_ln68_1_fu_83_p1) + $signed(sext_ln68_fu_87_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_return = (add_ln68_fu_91_p2 + zext_ln67_fu_54_p1);

assign b_fu_40_p3 = ((icmp_ln66_fu_26_p2[0:0] == 1'b1) ? j : i);

assign icmp_ln66_fu_26_p2 = ((i < j) ? 1'b1 : 1'b0);

assign mul_ln68_fu_67_p0 = mul_ln68_fu_67_p00;

assign mul_ln68_fu_67_p00 = $unsigned(xor_ln68_fu_57_p2);

assign mul_ln68_fu_67_p1 = mul_ln68_fu_67_p10;

assign mul_ln68_fu_67_p10 = a_reg_103;

assign sext_ln68_fu_87_p1 = xor_ln68_fu_57_p2;

assign trunc_ln_fu_73_p4 = {{mul_ln68_fu_67_p2[6:1]}};

assign xor_ln68_fu_57_p2 = (zext_ln66_1_fu_51_p1 ^ 4'd15);

assign zext_ln66_1_fu_51_p1 = a_reg_103;

assign zext_ln67_fu_54_p1 = b_reg_109;

assign zext_ln68_1_fu_83_p1 = trunc_ln_fu_73_p4;

endmodule //uniform_move_operation_edge_index
