// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module uniform_move_operation_tree_sum_18_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_0_val,
        x_1_val,
        x_2_val,
        x_3_val,
        x_4_val,
        x_5_val,
        x_6_val,
        x_7_val,
        x_8_val,
        x_9_val,
        x_10_val,
        x_11_val,
        x_12_val,
        x_13_val,
        x_14_val,
        x_15_val,
        x_16_val,
        x_17_val,
        ap_return
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] x_0_val;
input  [8:0] x_1_val;
input  [8:0] x_2_val;
input  [8:0] x_3_val;
input  [8:0] x_4_val;
input  [8:0] x_5_val;
input  [8:0] x_6_val;
input  [8:0] x_7_val;
input  [8:0] x_8_val;
input  [8:0] x_9_val;
input  [8:0] x_10_val;
input  [8:0] x_11_val;
input  [8:0] x_12_val;
input  [8:0] x_13_val;
input  [8:0] x_14_val;
input  [8:0] x_15_val;
input  [8:0] x_16_val;
input  [8:0] x_17_val;
output  [8:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[8:0] ap_return;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [8:0] y_fu_237_p3;
reg   [8:0] y_reg_805;
wire   [8:0] y_22_fu_307_p3;
reg   [8:0] y_22_reg_810;
wire   [8:0] y_23_fu_377_p3;
reg   [8:0] y_23_reg_815;
wire   [8:0] y_24_fu_447_p3;
reg   [8:0] y_24_reg_820;
wire   [8:0] y_25_fu_517_p3;
reg   [8:0] y_25_reg_825;
wire   [8:0] y_26_fu_587_p3;
reg   [8:0] y_26_reg_830;
wire   [8:0] y_27_fu_657_p3;
reg   [8:0] y_27_reg_835;
wire   [8:0] y_28_fu_727_p3;
reg   [8:0] y_28_reg_840;
wire   [8:0] y_29_fu_797_p3;
reg   [8:0] y_29_reg_845;
wire    grp_tree_sum_9_s_fu_162_ap_start;
wire    grp_tree_sum_9_s_fu_162_ap_done;
wire    grp_tree_sum_9_s_fu_162_ap_idle;
wire    grp_tree_sum_9_s_fu_162_ap_ready;
wire   [8:0] grp_tree_sum_9_s_fu_162_ap_return;
reg    grp_tree_sum_9_s_fu_162_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire  signed [8:0] sext_ln90_fu_175_p0;
wire  signed [8:0] sext_ln90_48_fu_179_p0;
wire  signed [8:0] add_ln90_fu_183_p0;
wire  signed [8:0] add_ln90_fu_183_p1;
wire  signed [9:0] sext_ln90_48_fu_179_p1;
wire  signed [9:0] sext_ln90_fu_175_p1;
wire   [9:0] add_ln90_48_fu_189_p2;
wire   [8:0] add_ln90_fu_183_p2;
wire   [0:0] tmp_fu_195_p3;
wire   [0:0] tmp_49_fu_203_p3;
wire   [0:0] xor_ln90_fu_211_p2;
wire   [0:0] and_ln90_fu_217_p2;
wire   [0:0] xor_ln90_48_fu_223_p2;
wire   [8:0] select_ln90_fu_229_p3;
wire  signed [8:0] sext_ln90_49_fu_245_p0;
wire  signed [8:0] sext_ln90_50_fu_249_p0;
wire  signed [8:0] add_ln90_49_fu_253_p0;
wire  signed [8:0] add_ln90_49_fu_253_p1;
wire  signed [9:0] sext_ln90_50_fu_249_p1;
wire  signed [9:0] sext_ln90_49_fu_245_p1;
wire   [9:0] add_ln90_50_fu_259_p2;
wire   [8:0] add_ln90_49_fu_253_p2;
wire   [0:0] tmp_50_fu_265_p3;
wire   [0:0] tmp_51_fu_273_p3;
wire   [0:0] xor_ln90_49_fu_281_p2;
wire   [0:0] and_ln90_22_fu_287_p2;
wire   [0:0] xor_ln90_50_fu_293_p2;
wire   [8:0] select_ln90_49_fu_299_p3;
wire  signed [8:0] sext_ln90_51_fu_315_p0;
wire  signed [8:0] sext_ln90_52_fu_319_p0;
wire  signed [8:0] add_ln90_51_fu_323_p0;
wire  signed [8:0] add_ln90_51_fu_323_p1;
wire  signed [9:0] sext_ln90_52_fu_319_p1;
wire  signed [9:0] sext_ln90_51_fu_315_p1;
wire   [9:0] add_ln90_52_fu_329_p2;
wire   [8:0] add_ln90_51_fu_323_p2;
wire   [0:0] tmp_52_fu_335_p3;
wire   [0:0] tmp_53_fu_343_p3;
wire   [0:0] xor_ln90_51_fu_351_p2;
wire   [0:0] and_ln90_23_fu_357_p2;
wire   [0:0] xor_ln90_52_fu_363_p2;
wire   [8:0] select_ln90_51_fu_369_p3;
wire  signed [8:0] sext_ln90_53_fu_385_p0;
wire  signed [8:0] sext_ln90_54_fu_389_p0;
wire  signed [8:0] add_ln90_53_fu_393_p0;
wire  signed [8:0] add_ln90_53_fu_393_p1;
wire  signed [9:0] sext_ln90_54_fu_389_p1;
wire  signed [9:0] sext_ln90_53_fu_385_p1;
wire   [9:0] add_ln90_54_fu_399_p2;
wire   [8:0] add_ln90_53_fu_393_p2;
wire   [0:0] tmp_54_fu_405_p3;
wire   [0:0] tmp_55_fu_413_p3;
wire   [0:0] xor_ln90_53_fu_421_p2;
wire   [0:0] and_ln90_24_fu_427_p2;
wire   [0:0] xor_ln90_54_fu_433_p2;
wire   [8:0] select_ln90_53_fu_439_p3;
wire  signed [8:0] sext_ln90_55_fu_455_p0;
wire  signed [8:0] sext_ln90_56_fu_459_p0;
wire  signed [8:0] add_ln90_55_fu_463_p0;
wire  signed [8:0] add_ln90_55_fu_463_p1;
wire  signed [9:0] sext_ln90_56_fu_459_p1;
wire  signed [9:0] sext_ln90_55_fu_455_p1;
wire   [9:0] add_ln90_56_fu_469_p2;
wire   [8:0] add_ln90_55_fu_463_p2;
wire   [0:0] tmp_56_fu_475_p3;
wire   [0:0] tmp_57_fu_483_p3;
wire   [0:0] xor_ln90_55_fu_491_p2;
wire   [0:0] and_ln90_25_fu_497_p2;
wire   [0:0] xor_ln90_56_fu_503_p2;
wire   [8:0] select_ln90_55_fu_509_p3;
wire  signed [8:0] sext_ln90_57_fu_525_p0;
wire  signed [8:0] sext_ln90_58_fu_529_p0;
wire  signed [8:0] add_ln90_57_fu_533_p0;
wire  signed [8:0] add_ln90_57_fu_533_p1;
wire  signed [9:0] sext_ln90_58_fu_529_p1;
wire  signed [9:0] sext_ln90_57_fu_525_p1;
wire   [9:0] add_ln90_58_fu_539_p2;
wire   [8:0] add_ln90_57_fu_533_p2;
wire   [0:0] tmp_58_fu_545_p3;
wire   [0:0] tmp_59_fu_553_p3;
wire   [0:0] xor_ln90_57_fu_561_p2;
wire   [0:0] and_ln90_26_fu_567_p2;
wire   [0:0] xor_ln90_58_fu_573_p2;
wire   [8:0] select_ln90_57_fu_579_p3;
wire  signed [8:0] sext_ln90_59_fu_595_p0;
wire  signed [8:0] sext_ln90_60_fu_599_p0;
wire  signed [8:0] add_ln90_59_fu_603_p0;
wire  signed [8:0] add_ln90_59_fu_603_p1;
wire  signed [9:0] sext_ln90_60_fu_599_p1;
wire  signed [9:0] sext_ln90_59_fu_595_p1;
wire   [9:0] add_ln90_60_fu_609_p2;
wire   [8:0] add_ln90_59_fu_603_p2;
wire   [0:0] tmp_60_fu_615_p3;
wire   [0:0] tmp_61_fu_623_p3;
wire   [0:0] xor_ln90_59_fu_631_p2;
wire   [0:0] and_ln90_27_fu_637_p2;
wire   [0:0] xor_ln90_60_fu_643_p2;
wire   [8:0] select_ln90_59_fu_649_p3;
wire  signed [8:0] sext_ln90_61_fu_665_p0;
wire  signed [8:0] sext_ln90_62_fu_669_p0;
wire  signed [8:0] add_ln90_61_fu_673_p0;
wire  signed [8:0] add_ln90_61_fu_673_p1;
wire  signed [9:0] sext_ln90_62_fu_669_p1;
wire  signed [9:0] sext_ln90_61_fu_665_p1;
wire   [9:0] add_ln90_62_fu_679_p2;
wire   [8:0] add_ln90_61_fu_673_p2;
wire   [0:0] tmp_62_fu_685_p3;
wire   [0:0] tmp_63_fu_693_p3;
wire   [0:0] xor_ln90_61_fu_701_p2;
wire   [0:0] and_ln90_28_fu_707_p2;
wire   [0:0] xor_ln90_62_fu_713_p2;
wire   [8:0] select_ln90_61_fu_719_p3;
wire  signed [8:0] sext_ln90_63_fu_735_p0;
wire  signed [8:0] sext_ln90_64_fu_739_p0;
wire  signed [8:0] add_ln90_63_fu_743_p0;
wire  signed [8:0] add_ln90_63_fu_743_p1;
wire  signed [9:0] sext_ln90_64_fu_739_p1;
wire  signed [9:0] sext_ln90_63_fu_735_p1;
wire   [9:0] add_ln90_64_fu_749_p2;
wire   [8:0] add_ln90_63_fu_743_p2;
wire   [0:0] tmp_64_fu_755_p3;
wire   [0:0] tmp_65_fu_763_p3;
wire   [0:0] xor_ln90_63_fu_771_p2;
wire   [0:0] and_ln90_29_fu_777_p2;
wire   [0:0] xor_ln90_64_fu_783_p2;
wire   [8:0] select_ln90_63_fu_789_p3;
reg   [8:0] ap_return_preg;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_tree_sum_9_s_fu_162_ap_start_reg = 1'b0;
#0 ap_return_preg = 9'd0;
end

uniform_move_operation_tree_sum_9_s grp_tree_sum_9_s_fu_162(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tree_sum_9_s_fu_162_ap_start),
    .ap_done(grp_tree_sum_9_s_fu_162_ap_done),
    .ap_idle(grp_tree_sum_9_s_fu_162_ap_idle),
    .ap_ready(grp_tree_sum_9_s_fu_162_ap_ready),
    .x_0_val(y_reg_805),
    .x_1_val(y_22_reg_810),
    .x_2_val(y_23_reg_815),
    .x_3_val(y_24_reg_820),
    .x_4_val(y_25_reg_825),
    .x_5_val(y_26_reg_830),
    .x_6_val(y_27_reg_835),
    .x_7_val(y_28_reg_840),
    .x_8_val(y_29_reg_845),
    .ap_return(grp_tree_sum_9_s_fu_162_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 9'd0;
    end else begin
        if (((grp_tree_sum_9_s_fu_162_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_return_preg <= grp_tree_sum_9_s_fu_162_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tree_sum_9_s_fu_162_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_tree_sum_9_s_fu_162_ap_start_reg <= 1'b1;
        end else if ((grp_tree_sum_9_s_fu_162_ap_ready == 1'b1)) begin
            grp_tree_sum_9_s_fu_162_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        y_22_reg_810 <= y_22_fu_307_p3;
        y_23_reg_815 <= y_23_fu_377_p3;
        y_24_reg_820 <= y_24_fu_447_p3;
        y_25_reg_825 <= y_25_fu_517_p3;
        y_26_reg_830 <= y_26_fu_587_p3;
        y_27_reg_835 <= y_27_fu_657_p3;
        y_28_reg_840 <= y_28_fu_727_p3;
        y_29_reg_845 <= y_29_fu_797_p3;
        y_reg_805 <= y_fu_237_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_tree_sum_9_s_fu_162_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_tree_sum_9_s_fu_162_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_tree_sum_9_s_fu_162_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_tree_sum_9_s_fu_162_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_return = grp_tree_sum_9_s_fu_162_ap_return;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_tree_sum_9_s_fu_162_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln90_48_fu_189_p2 = ($signed(sext_ln90_48_fu_179_p1) + $signed(sext_ln90_fu_175_p1));

assign add_ln90_49_fu_253_p0 = x_3_val;

assign add_ln90_49_fu_253_p1 = x_2_val;

assign add_ln90_49_fu_253_p2 = ($signed(add_ln90_49_fu_253_p0) + $signed(add_ln90_49_fu_253_p1));

assign add_ln90_50_fu_259_p2 = ($signed(sext_ln90_50_fu_249_p1) + $signed(sext_ln90_49_fu_245_p1));

assign add_ln90_51_fu_323_p0 = x_5_val;

assign add_ln90_51_fu_323_p1 = x_4_val;

assign add_ln90_51_fu_323_p2 = ($signed(add_ln90_51_fu_323_p0) + $signed(add_ln90_51_fu_323_p1));

assign add_ln90_52_fu_329_p2 = ($signed(sext_ln90_52_fu_319_p1) + $signed(sext_ln90_51_fu_315_p1));

assign add_ln90_53_fu_393_p0 = x_7_val;

assign add_ln90_53_fu_393_p1 = x_6_val;

assign add_ln90_53_fu_393_p2 = ($signed(add_ln90_53_fu_393_p0) + $signed(add_ln90_53_fu_393_p1));

assign add_ln90_54_fu_399_p2 = ($signed(sext_ln90_54_fu_389_p1) + $signed(sext_ln90_53_fu_385_p1));

assign add_ln90_55_fu_463_p0 = x_9_val;

assign add_ln90_55_fu_463_p1 = x_8_val;

assign add_ln90_55_fu_463_p2 = ($signed(add_ln90_55_fu_463_p0) + $signed(add_ln90_55_fu_463_p1));

assign add_ln90_56_fu_469_p2 = ($signed(sext_ln90_56_fu_459_p1) + $signed(sext_ln90_55_fu_455_p1));

assign add_ln90_57_fu_533_p0 = x_11_val;

assign add_ln90_57_fu_533_p1 = x_10_val;

assign add_ln90_57_fu_533_p2 = ($signed(add_ln90_57_fu_533_p0) + $signed(add_ln90_57_fu_533_p1));

assign add_ln90_58_fu_539_p2 = ($signed(sext_ln90_58_fu_529_p1) + $signed(sext_ln90_57_fu_525_p1));

assign add_ln90_59_fu_603_p0 = x_13_val;

assign add_ln90_59_fu_603_p1 = x_12_val;

assign add_ln90_59_fu_603_p2 = ($signed(add_ln90_59_fu_603_p0) + $signed(add_ln90_59_fu_603_p1));

assign add_ln90_60_fu_609_p2 = ($signed(sext_ln90_60_fu_599_p1) + $signed(sext_ln90_59_fu_595_p1));

assign add_ln90_61_fu_673_p0 = x_15_val;

assign add_ln90_61_fu_673_p1 = x_14_val;

assign add_ln90_61_fu_673_p2 = ($signed(add_ln90_61_fu_673_p0) + $signed(add_ln90_61_fu_673_p1));

assign add_ln90_62_fu_679_p2 = ($signed(sext_ln90_62_fu_669_p1) + $signed(sext_ln90_61_fu_665_p1));

assign add_ln90_63_fu_743_p0 = x_17_val;

assign add_ln90_63_fu_743_p1 = x_16_val;

assign add_ln90_63_fu_743_p2 = ($signed(add_ln90_63_fu_743_p0) + $signed(add_ln90_63_fu_743_p1));

assign add_ln90_64_fu_749_p2 = ($signed(sext_ln90_64_fu_739_p1) + $signed(sext_ln90_63_fu_735_p1));

assign add_ln90_fu_183_p0 = x_1_val;

assign add_ln90_fu_183_p1 = x_0_val;

assign add_ln90_fu_183_p2 = ($signed(add_ln90_fu_183_p0) + $signed(add_ln90_fu_183_p1));

assign and_ln90_22_fu_287_p2 = (xor_ln90_49_fu_281_p2 & tmp_51_fu_273_p3);

assign and_ln90_23_fu_357_p2 = (xor_ln90_51_fu_351_p2 & tmp_53_fu_343_p3);

assign and_ln90_24_fu_427_p2 = (xor_ln90_53_fu_421_p2 & tmp_55_fu_413_p3);

assign and_ln90_25_fu_497_p2 = (xor_ln90_55_fu_491_p2 & tmp_57_fu_483_p3);

assign and_ln90_26_fu_567_p2 = (xor_ln90_57_fu_561_p2 & tmp_59_fu_553_p3);

assign and_ln90_27_fu_637_p2 = (xor_ln90_59_fu_631_p2 & tmp_61_fu_623_p3);

assign and_ln90_28_fu_707_p2 = (xor_ln90_61_fu_701_p2 & tmp_63_fu_693_p3);

assign and_ln90_29_fu_777_p2 = (xor_ln90_63_fu_771_p2 & tmp_65_fu_763_p3);

assign and_ln90_fu_217_p2 = (xor_ln90_fu_211_p2 & tmp_49_fu_203_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign grp_tree_sum_9_s_fu_162_ap_start = grp_tree_sum_9_s_fu_162_ap_start_reg;

assign select_ln90_49_fu_299_p3 = ((and_ln90_22_fu_287_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_51_fu_369_p3 = ((and_ln90_23_fu_357_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_53_fu_439_p3 = ((and_ln90_24_fu_427_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_55_fu_509_p3 = ((and_ln90_25_fu_497_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_57_fu_579_p3 = ((and_ln90_26_fu_567_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_59_fu_649_p3 = ((and_ln90_27_fu_637_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_61_fu_719_p3 = ((and_ln90_28_fu_707_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_63_fu_789_p3 = ((and_ln90_29_fu_777_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln90_fu_229_p3 = ((and_ln90_fu_217_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign sext_ln90_48_fu_179_p0 = x_1_val;

assign sext_ln90_48_fu_179_p1 = sext_ln90_48_fu_179_p0;

assign sext_ln90_49_fu_245_p0 = x_2_val;

assign sext_ln90_49_fu_245_p1 = sext_ln90_49_fu_245_p0;

assign sext_ln90_50_fu_249_p0 = x_3_val;

assign sext_ln90_50_fu_249_p1 = sext_ln90_50_fu_249_p0;

assign sext_ln90_51_fu_315_p0 = x_4_val;

assign sext_ln90_51_fu_315_p1 = sext_ln90_51_fu_315_p0;

assign sext_ln90_52_fu_319_p0 = x_5_val;

assign sext_ln90_52_fu_319_p1 = sext_ln90_52_fu_319_p0;

assign sext_ln90_53_fu_385_p0 = x_6_val;

assign sext_ln90_53_fu_385_p1 = sext_ln90_53_fu_385_p0;

assign sext_ln90_54_fu_389_p0 = x_7_val;

assign sext_ln90_54_fu_389_p1 = sext_ln90_54_fu_389_p0;

assign sext_ln90_55_fu_455_p0 = x_8_val;

assign sext_ln90_55_fu_455_p1 = sext_ln90_55_fu_455_p0;

assign sext_ln90_56_fu_459_p0 = x_9_val;

assign sext_ln90_56_fu_459_p1 = sext_ln90_56_fu_459_p0;

assign sext_ln90_57_fu_525_p0 = x_10_val;

assign sext_ln90_57_fu_525_p1 = sext_ln90_57_fu_525_p0;

assign sext_ln90_58_fu_529_p0 = x_11_val;

assign sext_ln90_58_fu_529_p1 = sext_ln90_58_fu_529_p0;

assign sext_ln90_59_fu_595_p0 = x_12_val;

assign sext_ln90_59_fu_595_p1 = sext_ln90_59_fu_595_p0;

assign sext_ln90_60_fu_599_p0 = x_13_val;

assign sext_ln90_60_fu_599_p1 = sext_ln90_60_fu_599_p0;

assign sext_ln90_61_fu_665_p0 = x_14_val;

assign sext_ln90_61_fu_665_p1 = sext_ln90_61_fu_665_p0;

assign sext_ln90_62_fu_669_p0 = x_15_val;

assign sext_ln90_62_fu_669_p1 = sext_ln90_62_fu_669_p0;

assign sext_ln90_63_fu_735_p0 = x_16_val;

assign sext_ln90_63_fu_735_p1 = sext_ln90_63_fu_735_p0;

assign sext_ln90_64_fu_739_p0 = x_17_val;

assign sext_ln90_64_fu_739_p1 = sext_ln90_64_fu_739_p0;

assign sext_ln90_fu_175_p0 = x_0_val;

assign sext_ln90_fu_175_p1 = sext_ln90_fu_175_p0;

assign tmp_49_fu_203_p3 = add_ln90_fu_183_p2[32'd8];

assign tmp_50_fu_265_p3 = add_ln90_50_fu_259_p2[32'd9];

assign tmp_51_fu_273_p3 = add_ln90_49_fu_253_p2[32'd8];

assign tmp_52_fu_335_p3 = add_ln90_52_fu_329_p2[32'd9];

assign tmp_53_fu_343_p3 = add_ln90_51_fu_323_p2[32'd8];

assign tmp_54_fu_405_p3 = add_ln90_54_fu_399_p2[32'd9];

assign tmp_55_fu_413_p3 = add_ln90_53_fu_393_p2[32'd8];

assign tmp_56_fu_475_p3 = add_ln90_56_fu_469_p2[32'd9];

assign tmp_57_fu_483_p3 = add_ln90_55_fu_463_p2[32'd8];

assign tmp_58_fu_545_p3 = add_ln90_58_fu_539_p2[32'd9];

assign tmp_59_fu_553_p3 = add_ln90_57_fu_533_p2[32'd8];

assign tmp_60_fu_615_p3 = add_ln90_60_fu_609_p2[32'd9];

assign tmp_61_fu_623_p3 = add_ln90_59_fu_603_p2[32'd8];

assign tmp_62_fu_685_p3 = add_ln90_62_fu_679_p2[32'd9];

assign tmp_63_fu_693_p3 = add_ln90_61_fu_673_p2[32'd8];

assign tmp_64_fu_755_p3 = add_ln90_64_fu_749_p2[32'd9];

assign tmp_65_fu_763_p3 = add_ln90_63_fu_743_p2[32'd8];

assign tmp_fu_195_p3 = add_ln90_48_fu_189_p2[32'd9];

assign xor_ln90_48_fu_223_p2 = (tmp_fu_195_p3 ^ tmp_49_fu_203_p3);

assign xor_ln90_49_fu_281_p2 = (tmp_50_fu_265_p3 ^ 1'd1);

assign xor_ln90_50_fu_293_p2 = (tmp_51_fu_273_p3 ^ tmp_50_fu_265_p3);

assign xor_ln90_51_fu_351_p2 = (tmp_52_fu_335_p3 ^ 1'd1);

assign xor_ln90_52_fu_363_p2 = (tmp_53_fu_343_p3 ^ tmp_52_fu_335_p3);

assign xor_ln90_53_fu_421_p2 = (tmp_54_fu_405_p3 ^ 1'd1);

assign xor_ln90_54_fu_433_p2 = (tmp_55_fu_413_p3 ^ tmp_54_fu_405_p3);

assign xor_ln90_55_fu_491_p2 = (tmp_56_fu_475_p3 ^ 1'd1);

assign xor_ln90_56_fu_503_p2 = (tmp_57_fu_483_p3 ^ tmp_56_fu_475_p3);

assign xor_ln90_57_fu_561_p2 = (tmp_58_fu_545_p3 ^ 1'd1);

assign xor_ln90_58_fu_573_p2 = (tmp_59_fu_553_p3 ^ tmp_58_fu_545_p3);

assign xor_ln90_59_fu_631_p2 = (tmp_60_fu_615_p3 ^ 1'd1);

assign xor_ln90_60_fu_643_p2 = (tmp_61_fu_623_p3 ^ tmp_60_fu_615_p3);

assign xor_ln90_61_fu_701_p2 = (tmp_62_fu_685_p3 ^ 1'd1);

assign xor_ln90_62_fu_713_p2 = (tmp_63_fu_693_p3 ^ tmp_62_fu_685_p3);

assign xor_ln90_63_fu_771_p2 = (tmp_64_fu_755_p3 ^ 1'd1);

assign xor_ln90_64_fu_783_p2 = (tmp_65_fu_763_p3 ^ tmp_64_fu_755_p3);

assign xor_ln90_fu_211_p2 = (tmp_fu_195_p3 ^ 1'd1);

assign y_22_fu_307_p3 = ((xor_ln90_50_fu_293_p2[0:0] == 1'b1) ? select_ln90_49_fu_299_p3 : add_ln90_49_fu_253_p2);

assign y_23_fu_377_p3 = ((xor_ln90_52_fu_363_p2[0:0] == 1'b1) ? select_ln90_51_fu_369_p3 : add_ln90_51_fu_323_p2);

assign y_24_fu_447_p3 = ((xor_ln90_54_fu_433_p2[0:0] == 1'b1) ? select_ln90_53_fu_439_p3 : add_ln90_53_fu_393_p2);

assign y_25_fu_517_p3 = ((xor_ln90_56_fu_503_p2[0:0] == 1'b1) ? select_ln90_55_fu_509_p3 : add_ln90_55_fu_463_p2);

assign y_26_fu_587_p3 = ((xor_ln90_58_fu_573_p2[0:0] == 1'b1) ? select_ln90_57_fu_579_p3 : add_ln90_57_fu_533_p2);

assign y_27_fu_657_p3 = ((xor_ln90_60_fu_643_p2[0:0] == 1'b1) ? select_ln90_59_fu_649_p3 : add_ln90_59_fu_603_p2);

assign y_28_fu_727_p3 = ((xor_ln90_62_fu_713_p2[0:0] == 1'b1) ? select_ln90_61_fu_719_p3 : add_ln90_61_fu_673_p2);

assign y_29_fu_797_p3 = ((xor_ln90_64_fu_783_p2[0:0] == 1'b1) ? select_ln90_63_fu_789_p3 : add_ln90_63_fu_743_p2);

assign y_fu_237_p3 = ((xor_ln90_48_fu_223_p2[0:0] == 1'b1) ? select_ln90_fu_229_p3 : add_ln90_fu_183_p2);

endmodule //uniform_move_operation_tree_sum_18_s
