// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="uniform_move_operation_uniform_move_operation,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu19p-fsva3824-2-e,HLS_INPUT_CLOCK=3.333000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.425083,HLS_SYN_LAT=59,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=9513,HLS_SYN_LUT=24894,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module uniform_move_operation (
        ap_clk,
        ap_rst,
        h_0,
        h_1,
        h_2,
        h_3,
        h_4,
        h_5,
        h_6,
        h_7,
        J_edges_0,
        J_edges_1,
        J_edges_2,
        J_edges_3,
        J_edges_4,
        J_edges_5,
        J_edges_6,
        J_edges_7,
        J_edges_8,
        J_edges_9,
        J_edges_10,
        J_edges_11,
        J_edges_12,
        J_edges_13,
        J_edges_14,
        J_edges_15,
        J_edges_16,
        J_edges_17,
        J_edges_18,
        J_edges_19,
        J_edges_20,
        J_edges_21,
        J_edges_22,
        J_edges_23,
        J_edges_24,
        J_edges_25,
        J_edges_26,
        J_edges_27,
        new_spins,
        old_energy,
        new_energy,
        delta_x,
        accept_prob
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input  [8:0] h_0;
input  [8:0] h_1;
input  [8:0] h_2;
input  [8:0] h_3;
input  [8:0] h_4;
input  [8:0] h_5;
input  [8:0] h_6;
input  [8:0] h_7;
input  [8:0] J_edges_0;
input  [8:0] J_edges_1;
input  [8:0] J_edges_2;
input  [8:0] J_edges_3;
input  [8:0] J_edges_4;
input  [8:0] J_edges_5;
input  [8:0] J_edges_6;
input  [8:0] J_edges_7;
input  [8:0] J_edges_8;
input  [8:0] J_edges_9;
input  [8:0] J_edges_10;
input  [8:0] J_edges_11;
input  [8:0] J_edges_12;
input  [8:0] J_edges_13;
input  [8:0] J_edges_14;
input  [8:0] J_edges_15;
input  [8:0] J_edges_16;
input  [8:0] J_edges_17;
input  [8:0] J_edges_18;
input  [8:0] J_edges_19;
input  [8:0] J_edges_20;
input  [8:0] J_edges_21;
input  [8:0] J_edges_22;
input  [8:0] J_edges_23;
input  [8:0] J_edges_24;
input  [8:0] J_edges_25;
input  [8:0] J_edges_26;
input  [8:0] J_edges_27;
input  [7:0] new_spins;
input  [8:0] old_energy;
output  [8:0] new_energy;
output  [8:0] delta_x;
output  [31:0] accept_prob;

reg   [7:0] new_spins_read_reg_542;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [8:0] h_0_read_reg_547;
reg   [8:0] h_1_read_reg_552;
reg   [8:0] h_2_read_reg_557;
reg   [8:0] h_3_read_reg_562;
reg   [8:0] h_4_read_reg_567;
reg   [8:0] h_5_read_reg_572;
reg   [8:0] h_6_read_reg_577;
reg   [8:0] h_7_read_reg_582;
reg   [8:0] J_edges_0_read_reg_587;
reg   [8:0] J_edges_1_read_reg_592;
reg   [8:0] J_edges_2_read_reg_597;
reg   [8:0] J_edges_3_read_reg_602;
reg   [8:0] J_edges_4_read_reg_607;
reg   [8:0] J_edges_5_read_reg_612;
reg   [8:0] J_edges_6_read_reg_617;
reg   [8:0] J_edges_7_read_reg_622;
reg   [8:0] J_edges_8_read_reg_627;
reg   [8:0] J_edges_9_read_reg_632;
reg   [8:0] J_edges_10_read_reg_637;
reg   [8:0] J_edges_11_read_reg_642;
reg   [8:0] J_edges_12_read_reg_647;
reg   [8:0] J_edges_13_read_reg_652;
reg   [8:0] J_edges_14_read_reg_657;
reg   [8:0] J_edges_15_read_reg_662;
reg   [8:0] J_edges_16_read_reg_667;
reg   [8:0] J_edges_17_read_reg_672;
reg   [8:0] J_edges_18_read_reg_677;
reg   [8:0] J_edges_19_read_reg_682;
reg   [8:0] J_edges_20_read_reg_687;
reg   [8:0] J_edges_21_read_reg_692;
reg   [8:0] J_edges_22_read_reg_697;
reg   [8:0] J_edges_23_read_reg_702;
reg   [8:0] J_edges_24_read_reg_707;
reg   [8:0] J_edges_25_read_reg_712;
reg   [8:0] J_edges_26_read_reg_717;
reg   [8:0] J_edges_27_read_reg_722;
wire   [8:0] grp_dense_energy_over_alpha_fu_379_ap_return;
reg  signed [8:0] e_new_reg_727;
wire    ap_CS_fsm_state2;
wire   [7:0] x_positive_part_fu_458_ap_return;
reg   [7:0] x_reg_732;
wire    ap_CS_fsm_state3;
wire    grp_dense_energy_over_alpha_fu_379_ap_start;
wire    grp_dense_energy_over_alpha_fu_379_ap_done;
wire    grp_dense_energy_over_alpha_fu_379_ap_idle;
wire    grp_dense_energy_over_alpha_fu_379_ap_ready;
wire    x_positive_part_fu_458_ap_ready;
wire   [8:0] x_positive_part_fu_458_delta_over_alpha;
wire    grp_chebyshev_g_fu_463_ap_start;
wire    grp_chebyshev_g_fu_463_ap_done;
wire    grp_chebyshev_g_fu_463_ap_idle;
wire    grp_chebyshev_g_fu_463_ap_ready;
wire   [31:0] grp_chebyshev_g_fu_463_ap_return;
reg    grp_dense_energy_over_alpha_fu_379_ap_start_reg;
reg    grp_chebyshev_g_fu_463_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire  signed [9:0] sext_ln257_fu_469_p1;
wire  signed [9:0] sext_ln257_1_fu_472_p1;
wire   [9:0] sub_ln257_fu_476_p2;
wire   [0:0] tmp_fu_482_p3;
wire   [0:0] tmp_1_fu_494_p3;
wire   [0:0] xor_ln257_fu_502_p2;
wire   [0:0] and_ln257_fu_508_p2;
wire   [0:0] xor_ln257_1_fu_514_p2;
wire   [8:0] select_ln257_fu_520_p3;
wire   [8:0] delta_over_alpha_fu_490_p1;
reg   [4:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_dense_energy_over_alpha_fu_379_ap_start_reg = 1'b0;
#0 grp_chebyshev_g_fu_463_ap_start_reg = 1'b0;
end

uniform_move_operation_dense_energy_over_alpha grp_dense_energy_over_alpha_fu_379(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_energy_over_alpha_fu_379_ap_start),
    .ap_done(grp_dense_energy_over_alpha_fu_379_ap_done),
    .ap_idle(grp_dense_energy_over_alpha_fu_379_ap_idle),
    .ap_ready(grp_dense_energy_over_alpha_fu_379_ap_ready),
    .h_0_val(h_0_read_reg_547),
    .h_1_val(h_1_read_reg_552),
    .h_2_val(h_2_read_reg_557),
    .h_3_val(h_3_read_reg_562),
    .h_4_val(h_4_read_reg_567),
    .h_5_val(h_5_read_reg_572),
    .h_6_val(h_6_read_reg_577),
    .h_7_val(h_7_read_reg_582),
    .J_edges_0_val(J_edges_0_read_reg_587),
    .J_edges_1_val(J_edges_1_read_reg_592),
    .J_edges_2_val(J_edges_2_read_reg_597),
    .J_edges_3_val(J_edges_3_read_reg_602),
    .J_edges_4_val(J_edges_4_read_reg_607),
    .J_edges_5_val(J_edges_5_read_reg_612),
    .J_edges_6_val(J_edges_6_read_reg_617),
    .J_edges_7_val(J_edges_7_read_reg_622),
    .J_edges_8_val(J_edges_8_read_reg_627),
    .J_edges_9_val(J_edges_9_read_reg_632),
    .J_edges_10_val(J_edges_10_read_reg_637),
    .J_edges_11_val(J_edges_11_read_reg_642),
    .J_edges_12_val(J_edges_12_read_reg_647),
    .J_edges_13_val(J_edges_13_read_reg_652),
    .J_edges_14_val(J_edges_14_read_reg_657),
    .J_edges_15_val(J_edges_15_read_reg_662),
    .J_edges_16_val(J_edges_16_read_reg_667),
    .J_edges_17_val(J_edges_17_read_reg_672),
    .J_edges_18_val(J_edges_18_read_reg_677),
    .J_edges_19_val(J_edges_19_read_reg_682),
    .J_edges_20_val(J_edges_20_read_reg_687),
    .J_edges_21_val(J_edges_21_read_reg_692),
    .J_edges_22_val(J_edges_22_read_reg_697),
    .J_edges_23_val(J_edges_23_read_reg_702),
    .J_edges_24_val(J_edges_24_read_reg_707),
    .J_edges_25_val(J_edges_25_read_reg_712),
    .J_edges_26_val(J_edges_26_read_reg_717),
    .J_edges_27_val(J_edges_27_read_reg_722),
    .spins(new_spins_read_reg_542),
    .ap_return(grp_dense_energy_over_alpha_fu_379_ap_return)
);

uniform_move_operation_positive_part x_positive_part_fu_458(
    .ap_ready(x_positive_part_fu_458_ap_ready),
    .delta_over_alpha(x_positive_part_fu_458_delta_over_alpha),
    .ap_return(x_positive_part_fu_458_ap_return),
    .ap_rst(ap_rst)
);

uniform_move_operation_chebyshev_g grp_chebyshev_g_fu_463(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_chebyshev_g_fu_463_ap_start),
    .ap_done(grp_chebyshev_g_fu_463_ap_done),
    .ap_idle(grp_chebyshev_g_fu_463_ap_idle),
    .ap_ready(grp_chebyshev_g_fu_463_ap_ready),
    .x(x_reg_732),
    .ap_return(grp_chebyshev_g_fu_463_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_chebyshev_g_fu_463_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_chebyshev_g_fu_463_ap_start_reg <= 1'b1;
        end else if ((grp_chebyshev_g_fu_463_ap_ready == 1'b1)) begin
            grp_chebyshev_g_fu_463_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_energy_over_alpha_fu_379_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            grp_dense_energy_over_alpha_fu_379_ap_start_reg <= 1'b1;
        end else if ((grp_dense_energy_over_alpha_fu_379_ap_ready == 1'b1)) begin
            grp_dense_energy_over_alpha_fu_379_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        J_edges_0_read_reg_587 <= J_edges_0;
        J_edges_10_read_reg_637 <= J_edges_10;
        J_edges_11_read_reg_642 <= J_edges_11;
        J_edges_12_read_reg_647 <= J_edges_12;
        J_edges_13_read_reg_652 <= J_edges_13;
        J_edges_14_read_reg_657 <= J_edges_14;
        J_edges_15_read_reg_662 <= J_edges_15;
        J_edges_16_read_reg_667 <= J_edges_16;
        J_edges_17_read_reg_672 <= J_edges_17;
        J_edges_18_read_reg_677 <= J_edges_18;
        J_edges_19_read_reg_682 <= J_edges_19;
        J_edges_1_read_reg_592 <= J_edges_1;
        J_edges_20_read_reg_687 <= J_edges_20;
        J_edges_21_read_reg_692 <= J_edges_21;
        J_edges_22_read_reg_697 <= J_edges_22;
        J_edges_23_read_reg_702 <= J_edges_23;
        J_edges_24_read_reg_707 <= J_edges_24;
        J_edges_25_read_reg_712 <= J_edges_25;
        J_edges_26_read_reg_717 <= J_edges_26;
        J_edges_27_read_reg_722 <= J_edges_27;
        J_edges_2_read_reg_597 <= J_edges_2;
        J_edges_3_read_reg_602 <= J_edges_3;
        J_edges_4_read_reg_607 <= J_edges_4;
        J_edges_5_read_reg_612 <= J_edges_5;
        J_edges_6_read_reg_617 <= J_edges_6;
        J_edges_7_read_reg_622 <= J_edges_7;
        J_edges_8_read_reg_627 <= J_edges_8;
        J_edges_9_read_reg_632 <= J_edges_9;
        h_0_read_reg_547 <= h_0;
        h_1_read_reg_552 <= h_1;
        h_2_read_reg_557 <= h_2;
        h_3_read_reg_562 <= h_3;
        h_4_read_reg_567 <= h_4;
        h_5_read_reg_572 <= h_5;
        h_6_read_reg_577 <= h_6;
        h_7_read_reg_582 <= h_7;
        new_spins_read_reg_542 <= new_spins;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        e_new_reg_727 <= grp_dense_energy_over_alpha_fu_379_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_reg_732 <= x_positive_part_fu_458_ap_return;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_energy_over_alpha_fu_379_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_chebyshev_g_fu_463_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_dense_energy_over_alpha_fu_379_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_chebyshev_g_fu_463_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign accept_prob = grp_chebyshev_g_fu_463_ap_return;

assign and_ln257_fu_508_p2 = (xor_ln257_fu_502_p2 & tmp_1_fu_494_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign delta_over_alpha_fu_490_p1 = sub_ln257_fu_476_p2[8:0];

assign delta_x = x_positive_part_fu_458_ap_return;

assign grp_chebyshev_g_fu_463_ap_start = grp_chebyshev_g_fu_463_ap_start_reg;

assign grp_dense_energy_over_alpha_fu_379_ap_start = grp_dense_energy_over_alpha_fu_379_ap_start_reg;

assign new_energy = grp_dense_energy_over_alpha_fu_379_ap_return;

assign select_ln257_fu_520_p3 = ((and_ln257_fu_508_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign sext_ln257_1_fu_472_p1 = $signed(old_energy);

assign sext_ln257_fu_469_p1 = e_new_reg_727;

assign sub_ln257_fu_476_p2 = ($signed(sext_ln257_fu_469_p1) - $signed(sext_ln257_1_fu_472_p1));

assign tmp_1_fu_494_p3 = sub_ln257_fu_476_p2[32'd8];

assign tmp_fu_482_p3 = sub_ln257_fu_476_p2[32'd9];

assign x_positive_part_fu_458_delta_over_alpha = ((xor_ln257_1_fu_514_p2[0:0] == 1'b1) ? select_ln257_fu_520_p3 : delta_over_alpha_fu_490_p1);

assign xor_ln257_1_fu_514_p2 = (tmp_fu_482_p3 ^ tmp_1_fu_494_p3);

assign xor_ln257_fu_502_p2 = (tmp_fu_482_p3 ^ 1'd1);

endmodule //uniform_move_operation
