// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module local_spin_flip_operation_selected_coupling_for_j (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        J_edges_0_val,
        J_edges_1_val,
        J_edges_2_val,
        J_edges_3_val,
        J_edges_4_val,
        J_edges_5_val,
        J_edges_6_val,
        J_edges_7_val,
        J_edges_8_val,
        J_edges_9_val,
        J_edges_10_val,
        J_edges_11_val,
        J_edges_12_val,
        J_edges_13_val,
        J_edges_14_val,
        J_edges_15_val,
        J_edges_16_val,
        J_edges_17_val,
        J_edges_18_val,
        J_edges_19_val,
        J_edges_20_val,
        J_edges_21_val,
        J_edges_22_val,
        J_edges_23_val,
        J_edges_24_val,
        J_edges_25_val,
        J_edges_26_val,
        J_edges_27_val,
        flip_mask,
        j,
        ap_return
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] J_edges_0_val;
input  [8:0] J_edges_1_val;
input  [8:0] J_edges_2_val;
input  [8:0] J_edges_3_val;
input  [8:0] J_edges_4_val;
input  [8:0] J_edges_5_val;
input  [8:0] J_edges_6_val;
input  [8:0] J_edges_7_val;
input  [8:0] J_edges_8_val;
input  [8:0] J_edges_9_val;
input  [8:0] J_edges_10_val;
input  [8:0] J_edges_11_val;
input  [8:0] J_edges_12_val;
input  [8:0] J_edges_13_val;
input  [8:0] J_edges_14_val;
input  [8:0] J_edges_15_val;
input  [8:0] J_edges_16_val;
input  [8:0] J_edges_17_val;
input  [8:0] J_edges_18_val;
input  [8:0] J_edges_19_val;
input  [8:0] J_edges_20_val;
input  [8:0] J_edges_21_val;
input  [8:0] J_edges_22_val;
input  [8:0] J_edges_23_val;
input  [8:0] J_edges_24_val;
input  [8:0] J_edges_25_val;
input  [8:0] J_edges_26_val;
input  [8:0] J_edges_27_val;
input  [7:0] flip_mask;
input  [2:0] j;
output  [8:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[8:0] ap_return;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] grp_edge_index_fu_518_ap_return;
reg   [4:0] reg_532;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state16;
wire   [8:0] grp_fu_536_p59;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state13;
wire   [0:0] icmp_ln157_fu_644_p2;
reg   [0:0] icmp_ln157_reg_750;
wire   [0:0] trunc_ln157_fu_650_p1;
reg   [0:0] trunc_ln157_reg_905;
wire   [0:0] icmp_ln157_1_fu_654_p2;
reg   [0:0] icmp_ln157_1_reg_909;
wire   [0:0] tmp_fu_659_p3;
reg   [0:0] tmp_reg_913;
wire   [0:0] icmp_ln157_2_fu_666_p2;
reg   [0:0] icmp_ln157_2_reg_917;
wire   [0:0] tmp_19_fu_671_p3;
reg   [0:0] tmp_19_reg_921;
wire   [0:0] icmp_ln157_3_fu_678_p2;
reg   [0:0] icmp_ln157_3_reg_925;
wire   [0:0] tmp_20_fu_683_p3;
reg   [0:0] tmp_20_reg_929;
wire   [0:0] icmp_ln157_4_fu_690_p2;
reg   [0:0] icmp_ln157_4_reg_933;
wire   [0:0] tmp_21_fu_695_p3;
reg   [0:0] tmp_21_reg_937;
wire   [0:0] icmp_ln157_5_fu_702_p2;
reg   [0:0] icmp_ln157_5_reg_941;
wire   [0:0] tmp_22_fu_707_p3;
reg   [0:0] tmp_22_reg_945;
wire   [0:0] icmp_ln157_6_fu_714_p2;
reg   [0:0] icmp_ln157_6_reg_949;
wire   [0:0] tmp_23_fu_719_p3;
reg   [0:0] tmp_23_reg_953;
wire   [0:0] icmp_ln157_7_fu_726_p2;
reg   [0:0] icmp_ln157_7_reg_957;
wire   [0:0] tmp_24_fu_731_p3;
reg   [0:0] tmp_24_reg_961;
wire    grp_edge_index_fu_518_ap_ready;
reg   [2:0] grp_edge_index_fu_518_i;
reg   [8:0] agg_result_0_reg_342;
reg   [8:0] ap_phi_mux_agg_result_2_phi_fu_358_p4;
reg   [8:0] agg_result_2_reg_354;
reg   [8:0] agg_result_3_reg_367;
reg   [8:0] ap_phi_mux_agg_result_4_phi_fu_381_p4;
reg   [8:0] agg_result_4_reg_378;
reg   [8:0] agg_result_5_reg_390;
reg   [8:0] ap_phi_mux_agg_result_6_phi_fu_404_p4;
reg   [8:0] agg_result_6_reg_401;
reg   [8:0] agg_result_7_reg_413;
reg   [8:0] ap_phi_mux_agg_result_8_phi_fu_427_p4;
reg   [8:0] agg_result_8_reg_424;
reg   [8:0] agg_result_9_reg_436;
reg   [8:0] ap_phi_mux_agg_result_10_phi_fu_450_p4;
reg   [8:0] agg_result_10_reg_447;
reg   [8:0] agg_result_11_reg_459;
reg   [8:0] ap_phi_mux_agg_result_12_phi_fu_473_p4;
reg   [8:0] agg_result_12_reg_470;
reg   [8:0] agg_result_13_reg_482;
reg   [8:0] ap_phi_mux_agg_result_14_phi_fu_496_p4;
reg   [8:0] agg_result_14_reg_493;
reg   [8:0] ap_phi_mux_agg_result_1_phi_fu_508_p6;
reg   [8:0] agg_result_1_reg_505;
wire    ap_CS_fsm_state17;
wire   [8:0] grp_fu_536_p57;
reg   [8:0] ap_return_preg;
reg   [16:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire   [4:0] grp_fu_536_p1;
wire   [4:0] grp_fu_536_p3;
wire   [4:0] grp_fu_536_p5;
wire   [4:0] grp_fu_536_p7;
wire   [4:0] grp_fu_536_p9;
wire   [4:0] grp_fu_536_p11;
wire   [4:0] grp_fu_536_p13;
wire   [4:0] grp_fu_536_p15;
wire   [4:0] grp_fu_536_p17;
wire   [4:0] grp_fu_536_p19;
wire   [4:0] grp_fu_536_p21;
wire   [4:0] grp_fu_536_p23;
wire   [4:0] grp_fu_536_p25;
wire   [4:0] grp_fu_536_p27;
wire   [4:0] grp_fu_536_p29;
wire   [4:0] grp_fu_536_p31;
wire  signed [4:0] grp_fu_536_p33;
wire  signed [4:0] grp_fu_536_p35;
wire  signed [4:0] grp_fu_536_p37;
wire  signed [4:0] grp_fu_536_p39;
wire  signed [4:0] grp_fu_536_p41;
wire  signed [4:0] grp_fu_536_p43;
wire  signed [4:0] grp_fu_536_p45;
wire  signed [4:0] grp_fu_536_p47;
wire  signed [4:0] grp_fu_536_p49;
wire  signed [4:0] grp_fu_536_p51;
wire  signed [4:0] grp_fu_536_p53;
wire  signed [4:0] grp_fu_536_p55;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 ap_return_preg = 9'd0;
end

local_spin_flip_operation_edge_index grp_edge_index_fu_518(
    .ap_ready(grp_edge_index_fu_518_ap_ready),
    .i(grp_edge_index_fu_518_i),
    .j(j),
    .ap_return(grp_edge_index_fu_518_ap_return),
    .ap_rst(ap_rst)
);

(* dissolve_hierarchy = "yes" *) local_spin_flip_operation_sparsemux_57_5_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 9 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 9 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 9 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 9 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 9 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 9 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 9 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 9 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 9 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 9 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 9 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 9 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 9 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 9 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 9 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 9 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 9 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 9 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 9 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 9 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 9 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 9 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 9 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 9 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 9 ),
    .CASE25( 5'h19 ),
    .din25_WIDTH( 9 ),
    .CASE26( 5'h1A ),
    .din26_WIDTH( 9 ),
    .CASE27( 5'h1B ),
    .din27_WIDTH( 9 ),
    .def_WIDTH( 9 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 9 ))
sparsemux_57_5_9_1_1_U14(
    .din0(J_edges_0_val),
    .din1(J_edges_1_val),
    .din2(J_edges_2_val),
    .din3(J_edges_3_val),
    .din4(J_edges_4_val),
    .din5(J_edges_5_val),
    .din6(J_edges_6_val),
    .din7(J_edges_7_val),
    .din8(J_edges_8_val),
    .din9(J_edges_9_val),
    .din10(J_edges_10_val),
    .din11(J_edges_11_val),
    .din12(J_edges_12_val),
    .din13(J_edges_13_val),
    .din14(J_edges_14_val),
    .din15(J_edges_15_val),
    .din16(J_edges_16_val),
    .din17(J_edges_17_val),
    .din18(J_edges_18_val),
    .din19(J_edges_19_val),
    .din20(J_edges_20_val),
    .din21(J_edges_21_val),
    .din22(J_edges_22_val),
    .din23(J_edges_23_val),
    .din24(J_edges_24_val),
    .din25(J_edges_25_val),
    .din26(J_edges_26_val),
    .din27(J_edges_27_val),
    .def(grp_fu_536_p57),
    .sel(reg_532),
    .dout(grp_fu_536_p59)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 9'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            ap_return_preg <= ap_phi_mux_agg_result_1_phi_fu_508_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln157_fu_650_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln157_reg_750 == 1'd0))) begin
        agg_result_0_reg_342 <= 9'd0;
    end else if (((trunc_ln157_reg_905 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        agg_result_0_reg_342 <= grp_fu_536_p59;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & ((((((icmp_ln157_5_reg_941 == 1'd0) & (icmp_ln157_3_reg_925 == 1'd1)) | ((icmp_ln157_5_reg_941 == 1'd0) & (icmp_ln157_4_reg_933 == 1'd0))) | ((icmp_ln157_5_reg_941 == 1'd0) & (icmp_ln157_2_reg_917 == 1'd1))) | ((icmp_ln157_5_reg_941 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd1))) | ((icmp_ln157_5_reg_941 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        agg_result_10_reg_447 <= agg_result_9_reg_436;
    end else if (((icmp_ln157_4_reg_933 == 1'd1) & (icmp_ln157_3_reg_925 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        agg_result_10_reg_447 <= agg_result_7_reg_413;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (((((((tmp_22_fu_707_p3 == 1'd0) & (icmp_ln157_5_reg_941 == 1'd0)) | ((tmp_22_fu_707_p3 == 1'd0) & (icmp_ln157_4_reg_933 == 1'd1))) | ((tmp_22_fu_707_p3 == 1'd0) & (icmp_ln157_3_reg_925 == 1'd1))) | ((tmp_22_fu_707_p3 == 1'd0) & (icmp_ln157_2_reg_917 == 1'd1))) | ((tmp_22_fu_707_p3 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd1))) | ((tmp_22_fu_707_p3 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        agg_result_11_reg_459 <= ap_phi_mux_agg_result_10_phi_fu_450_p4;
    end else if (((tmp_22_reg_945 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        agg_result_11_reg_459 <= grp_fu_536_p59;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln157_5_reg_941 == 1'd1) & (icmp_ln157_4_reg_933 == 1'd0) & (1'b1 == ap_CS_fsm_state12))) begin
        agg_result_12_reg_470 <= agg_result_9_reg_436;
    end else if (((1'b1 == ap_CS_fsm_state14) & (((((((icmp_ln157_6_reg_949 == 1'd0) & (icmp_ln157_5_reg_941 == 1'd0)) | ((icmp_ln157_6_reg_949 == 1'd0) & (icmp_ln157_4_reg_933 == 1'd1))) | ((icmp_ln157_6_reg_949 == 1'd0) & (icmp_ln157_3_reg_925 == 1'd1))) | ((icmp_ln157_6_reg_949 == 1'd0) & (icmp_ln157_2_reg_917 == 1'd1))) | ((icmp_ln157_6_reg_949 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd1))) | ((icmp_ln157_6_reg_949 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        agg_result_12_reg_470 <= agg_result_11_reg_459;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & ((((((((tmp_23_fu_719_p3 == 1'd0) & (icmp_ln157_5_reg_941 == 1'd1)) | ((tmp_23_fu_719_p3 == 1'd0) & (icmp_ln157_6_reg_949 == 1'd0))) | ((tmp_23_fu_719_p3 == 1'd0) & (icmp_ln157_4_reg_933 == 1'd1))) | ((tmp_23_fu_719_p3 == 1'd0) & (icmp_ln157_3_reg_925 == 1'd1))) | ((tmp_23_fu_719_p3 == 1'd0) & (icmp_ln157_2_reg_917 == 1'd1))) | ((tmp_23_fu_719_p3 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd1))) | ((tmp_23_fu_719_p3 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        agg_result_13_reg_482 <= ap_phi_mux_agg_result_12_phi_fu_473_p4;
    end else if (((tmp_23_reg_953 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        agg_result_13_reg_482 <= grp_fu_536_p59;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) & ((((((((icmp_ln157_7_reg_957 == 1'd0) & (icmp_ln157_5_reg_941 == 1'd1)) | ((icmp_ln157_7_reg_957 == 1'd0) & (icmp_ln157_6_reg_949 == 1'd0))) | ((icmp_ln157_7_reg_957 == 1'd0) & (icmp_ln157_4_reg_933 == 1'd1))) | ((icmp_ln157_7_reg_957 == 1'd0) & (icmp_ln157_3_reg_925 == 1'd1))) | ((icmp_ln157_7_reg_957 == 1'd0) & (icmp_ln157_2_reg_917 == 1'd1))) | ((icmp_ln157_7_reg_957 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd1))) | ((icmp_ln157_7_reg_957 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        agg_result_14_reg_493 <= agg_result_13_reg_482;
    end else if (((icmp_ln157_6_reg_949 == 1'd1) & (icmp_ln157_5_reg_941 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        agg_result_14_reg_493 <= agg_result_11_reg_459;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln157_7_reg_957 == 1'd1) & (icmp_ln157_6_reg_949 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        agg_result_1_reg_505 <= agg_result_13_reg_482;
    end else if (((1'b1 == ap_CS_fsm_state16) & (((((((((tmp_24_fu_731_p3 == 1'd0) & (icmp_ln157_7_reg_957 == 1'd0)) | ((tmp_24_fu_731_p3 == 1'd0) & (icmp_ln157_6_reg_949 == 1'd1))) | ((tmp_24_fu_731_p3 == 1'd0) & (icmp_ln157_5_reg_941 == 1'd1))) | ((tmp_24_fu_731_p3 == 1'd0) & (icmp_ln157_4_reg_933 == 1'd1))) | ((tmp_24_fu_731_p3 == 1'd0) & (icmp_ln157_3_reg_925 == 1'd1))) | ((tmp_24_fu_731_p3 == 1'd0) & (icmp_ln157_2_reg_917 == 1'd1))) | ((tmp_24_fu_731_p3 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd1))) | ((tmp_24_fu_731_p3 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        agg_result_1_reg_505 <= ap_phi_mux_agg_result_14_phi_fu_496_p4;
    end else if (((1'b1 == ap_CS_fsm_state17) & (((((((((tmp_24_reg_961 == 1'd1) & (icmp_ln157_7_reg_957 == 1'd0)) | ((tmp_24_reg_961 == 1'd1) & (icmp_ln157_6_reg_949 == 1'd1))) | ((tmp_24_reg_961 == 1'd1) & (icmp_ln157_5_reg_941 == 1'd1))) | ((tmp_24_reg_961 == 1'd1) & (icmp_ln157_4_reg_933 == 1'd1))) | ((tmp_24_reg_961 == 1'd1) & (icmp_ln157_3_reg_925 == 1'd1))) | ((tmp_24_reg_961 == 1'd1) & (icmp_ln157_2_reg_917 == 1'd1))) | ((tmp_24_reg_961 == 1'd1) & (icmp_ln157_1_reg_909 == 1'd1))) | ((tmp_24_reg_961 == 1'd1) & (icmp_ln157_reg_750 == 1'd1))))) begin
        agg_result_1_reg_505 <= grp_fu_536_p59;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln157_1_reg_909 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln157_reg_750 == 1'd0))) begin
        agg_result_2_reg_354 <= agg_result_0_reg_342;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln157_reg_750 == 1'd1))) begin
        agg_result_2_reg_354 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (((tmp_fu_659_p3 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd0)) | ((tmp_fu_659_p3 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        agg_result_3_reg_367 <= ap_phi_mux_agg_result_2_phi_fu_358_p4;
    end else if (((tmp_reg_913 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        agg_result_3_reg_367 <= grp_fu_536_p59;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln157_1_reg_909 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln157_reg_750 == 1'd0))) begin
        agg_result_4_reg_378 <= agg_result_0_reg_342;
    end else if (((1'b1 == ap_CS_fsm_state6) & (((icmp_ln157_2_reg_917 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd0)) | ((icmp_ln157_2_reg_917 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        agg_result_4_reg_378 <= agg_result_3_reg_367;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & ((((tmp_19_fu_671_p3 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd1)) | ((tmp_19_fu_671_p3 == 1'd0) & (icmp_ln157_2_reg_917 == 1'd0))) | ((tmp_19_fu_671_p3 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        agg_result_5_reg_390 <= ap_phi_mux_agg_result_4_phi_fu_381_p4;
    end else if (((tmp_19_reg_921 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        agg_result_5_reg_390 <= grp_fu_536_p59;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((((icmp_ln157_3_reg_925 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd1)) | ((icmp_ln157_3_reg_925 == 1'd0) & (icmp_ln157_2_reg_917 == 1'd0))) | ((icmp_ln157_3_reg_925 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        agg_result_6_reg_401 <= agg_result_5_reg_390;
    end else if (((icmp_ln157_2_reg_917 == 1'd1) & (icmp_ln157_1_reg_909 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        agg_result_6_reg_401 <= agg_result_3_reg_367;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (((((tmp_20_fu_683_p3 == 1'd0) & (icmp_ln157_3_reg_925 == 1'd0)) | ((tmp_20_fu_683_p3 == 1'd0) & (icmp_ln157_2_reg_917 == 1'd1))) | ((tmp_20_fu_683_p3 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd1))) | ((tmp_20_fu_683_p3 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        agg_result_7_reg_413 <= ap_phi_mux_agg_result_6_phi_fu_404_p4;
    end else if (((tmp_20_reg_929 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        agg_result_7_reg_413 <= grp_fu_536_p59;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln157_3_reg_925 == 1'd1) & (icmp_ln157_2_reg_917 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        agg_result_8_reg_424 <= agg_result_5_reg_390;
    end else if (((1'b1 == ap_CS_fsm_state10) & (((((icmp_ln157_4_reg_933 == 1'd0) & (icmp_ln157_3_reg_925 == 1'd0)) | ((icmp_ln157_4_reg_933 == 1'd0) & (icmp_ln157_2_reg_917 == 1'd1))) | ((icmp_ln157_4_reg_933 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd1))) | ((icmp_ln157_4_reg_933 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        agg_result_8_reg_424 <= agg_result_7_reg_413;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & ((((((tmp_21_fu_695_p3 == 1'd0) & (icmp_ln157_3_reg_925 == 1'd1)) | ((tmp_21_fu_695_p3 == 1'd0) & (icmp_ln157_4_reg_933 == 1'd0))) | ((tmp_21_fu_695_p3 == 1'd0) & (icmp_ln157_2_reg_917 == 1'd1))) | ((tmp_21_fu_695_p3 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd1))) | ((tmp_21_fu_695_p3 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        agg_result_9_reg_436 <= ap_phi_mux_agg_result_8_phi_fu_427_p4;
    end else if (((tmp_21_reg_937 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        agg_result_9_reg_436 <= grp_fu_536_p59;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln157_1_reg_909 <= icmp_ln157_1_fu_654_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        icmp_ln157_2_reg_917 <= icmp_ln157_2_fu_666_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        icmp_ln157_3_reg_925 <= icmp_ln157_3_fu_678_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        icmp_ln157_4_reg_933 <= icmp_ln157_4_fu_690_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        icmp_ln157_5_reg_941 <= icmp_ln157_5_fu_702_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        icmp_ln157_6_reg_949 <= icmp_ln157_6_fu_714_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        icmp_ln157_7_reg_957 <= icmp_ln157_7_fu_726_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln157_reg_750 <= icmp_ln157_fu_644_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12))) begin
        reg_532 <= grp_edge_index_fu_518_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_19_reg_921 <= flip_mask[32'd2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_20_reg_929 <= flip_mask[32'd3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tmp_21_reg_937 <= flip_mask[32'd4];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tmp_22_reg_945 <= flip_mask[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        tmp_23_reg_953 <= flip_mask[32'd6];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        tmp_24_reg_961 <= flip_mask[32'd7];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_reg_913 <= flip_mask[32'd1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln157_reg_905 <= trunc_ln157_fu_650_p1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & ((((((icmp_ln157_5_reg_941 == 1'd0) & (icmp_ln157_3_reg_925 == 1'd1)) | ((icmp_ln157_5_reg_941 == 1'd0) & (icmp_ln157_4_reg_933 == 1'd0))) | ((icmp_ln157_5_reg_941 == 1'd0) & (icmp_ln157_2_reg_917 == 1'd1))) | ((icmp_ln157_5_reg_941 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd1))) | ((icmp_ln157_5_reg_941 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        ap_phi_mux_agg_result_10_phi_fu_450_p4 = agg_result_9_reg_436;
    end else begin
        ap_phi_mux_agg_result_10_phi_fu_450_p4 = agg_result_10_reg_447;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) & (((((((icmp_ln157_6_reg_949 == 1'd0) & (icmp_ln157_5_reg_941 == 1'd0)) | ((icmp_ln157_6_reg_949 == 1'd0) & (icmp_ln157_4_reg_933 == 1'd1))) | ((icmp_ln157_6_reg_949 == 1'd0) & (icmp_ln157_3_reg_925 == 1'd1))) | ((icmp_ln157_6_reg_949 == 1'd0) & (icmp_ln157_2_reg_917 == 1'd1))) | ((icmp_ln157_6_reg_949 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd1))) | ((icmp_ln157_6_reg_949 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        ap_phi_mux_agg_result_12_phi_fu_473_p4 = agg_result_11_reg_459;
    end else begin
        ap_phi_mux_agg_result_12_phi_fu_473_p4 = agg_result_12_reg_470;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & ((((((((icmp_ln157_7_reg_957 == 1'd0) & (icmp_ln157_5_reg_941 == 1'd1)) | ((icmp_ln157_7_reg_957 == 1'd0) & (icmp_ln157_6_reg_949 == 1'd0))) | ((icmp_ln157_7_reg_957 == 1'd0) & (icmp_ln157_4_reg_933 == 1'd1))) | ((icmp_ln157_7_reg_957 == 1'd0) & (icmp_ln157_3_reg_925 == 1'd1))) | ((icmp_ln157_7_reg_957 == 1'd0) & (icmp_ln157_2_reg_917 == 1'd1))) | ((icmp_ln157_7_reg_957 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd1))) | ((icmp_ln157_7_reg_957 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        ap_phi_mux_agg_result_14_phi_fu_496_p4 = agg_result_13_reg_482;
    end else begin
        ap_phi_mux_agg_result_14_phi_fu_496_p4 = agg_result_14_reg_493;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (((((((((tmp_24_reg_961 == 1'd1) & (icmp_ln157_7_reg_957 == 1'd0)) | ((tmp_24_reg_961 == 1'd1) & (icmp_ln157_6_reg_949 == 1'd1))) | ((tmp_24_reg_961 == 1'd1) & (icmp_ln157_5_reg_941 == 1'd1))) | ((tmp_24_reg_961 == 1'd1) & (icmp_ln157_4_reg_933 == 1'd1))) | ((tmp_24_reg_961 == 1'd1) & (icmp_ln157_3_reg_925 == 1'd1))) | ((tmp_24_reg_961 == 1'd1) & (icmp_ln157_2_reg_917 == 1'd1))) | ((tmp_24_reg_961 == 1'd1) & (icmp_ln157_1_reg_909 == 1'd1))) | ((tmp_24_reg_961 == 1'd1) & (icmp_ln157_reg_750 == 1'd1))))) begin
        ap_phi_mux_agg_result_1_phi_fu_508_p6 = grp_fu_536_p59;
    end else begin
        ap_phi_mux_agg_result_1_phi_fu_508_p6 = agg_result_1_reg_505;
    end
end

always @ (*) begin
    if (((icmp_ln157_1_reg_909 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln157_reg_750 == 1'd0))) begin
        ap_phi_mux_agg_result_2_phi_fu_358_p4 = agg_result_0_reg_342;
    end else begin
        ap_phi_mux_agg_result_2_phi_fu_358_p4 = agg_result_2_reg_354;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (((icmp_ln157_2_reg_917 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd0)) | ((icmp_ln157_2_reg_917 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        ap_phi_mux_agg_result_4_phi_fu_381_p4 = agg_result_3_reg_367;
    end else begin
        ap_phi_mux_agg_result_4_phi_fu_381_p4 = agg_result_4_reg_378;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((((icmp_ln157_3_reg_925 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd1)) | ((icmp_ln157_3_reg_925 == 1'd0) & (icmp_ln157_2_reg_917 == 1'd0))) | ((icmp_ln157_3_reg_925 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        ap_phi_mux_agg_result_6_phi_fu_404_p4 = agg_result_5_reg_390;
    end else begin
        ap_phi_mux_agg_result_6_phi_fu_404_p4 = agg_result_6_reg_401;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) & (((((icmp_ln157_4_reg_933 == 1'd0) & (icmp_ln157_3_reg_925 == 1'd0)) | ((icmp_ln157_4_reg_933 == 1'd0) & (icmp_ln157_2_reg_917 == 1'd1))) | ((icmp_ln157_4_reg_933 == 1'd0) & (icmp_ln157_1_reg_909 == 1'd1))) | ((icmp_ln157_4_reg_933 == 1'd0) & (icmp_ln157_reg_750 == 1'd1))))) begin
        ap_phi_mux_agg_result_8_phi_fu_427_p4 = agg_result_7_reg_413;
    end else begin
        ap_phi_mux_agg_result_8_phi_fu_427_p4 = agg_result_8_reg_424;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ap_return = ap_phi_mux_agg_result_1_phi_fu_508_p6;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & (((((((((tmp_24_fu_731_p3 == 1'd1) & (icmp_ln157_7_reg_957 == 1'd0)) | ((tmp_24_fu_731_p3 == 1'd1) & (icmp_ln157_6_reg_949 == 1'd1))) | ((tmp_24_fu_731_p3 == 1'd1) & (icmp_ln157_5_reg_941 == 1'd1))) | ((tmp_24_fu_731_p3 == 1'd1) & (icmp_ln157_4_reg_933 == 1'd1))) | ((tmp_24_fu_731_p3 == 1'd1) & (icmp_ln157_3_reg_925 == 1'd1))) | ((tmp_24_fu_731_p3 == 1'd1) & (icmp_ln157_2_reg_917 == 1'd1))) | ((tmp_24_fu_731_p3 == 1'd1) & (icmp_ln157_1_reg_909 == 1'd1))) | ((tmp_24_fu_731_p3 == 1'd1) & (icmp_ln157_reg_750 == 1'd1))))) begin
        grp_edge_index_fu_518_i = 3'd7;
    end else if (((1'b1 == ap_CS_fsm_state14) & ((((((((tmp_23_fu_719_p3 == 1'd1) & (icmp_ln157_5_reg_941 == 1'd1)) | ((tmp_23_fu_719_p3 == 1'd1) & (icmp_ln157_6_reg_949 == 1'd0))) | ((tmp_23_fu_719_p3 == 1'd1) & (icmp_ln157_4_reg_933 == 1'd1))) | ((tmp_23_fu_719_p3 == 1'd1) & (icmp_ln157_3_reg_925 == 1'd1))) | ((tmp_23_fu_719_p3 == 1'd1) & (icmp_ln157_2_reg_917 == 1'd1))) | ((tmp_23_fu_719_p3 == 1'd1) & (icmp_ln157_1_reg_909 == 1'd1))) | ((tmp_23_fu_719_p3 == 1'd1) & (icmp_ln157_reg_750 == 1'd1))))) begin
        grp_edge_index_fu_518_i = 3'd6;
    end else if (((1'b1 == ap_CS_fsm_state12) & (((((((tmp_22_fu_707_p3 == 1'd1) & (icmp_ln157_5_reg_941 == 1'd0)) | ((tmp_22_fu_707_p3 == 1'd1) & (icmp_ln157_4_reg_933 == 1'd1))) | ((tmp_22_fu_707_p3 == 1'd1) & (icmp_ln157_3_reg_925 == 1'd1))) | ((tmp_22_fu_707_p3 == 1'd1) & (icmp_ln157_2_reg_917 == 1'd1))) | ((tmp_22_fu_707_p3 == 1'd1) & (icmp_ln157_1_reg_909 == 1'd1))) | ((tmp_22_fu_707_p3 == 1'd1) & (icmp_ln157_reg_750 == 1'd1))))) begin
        grp_edge_index_fu_518_i = 3'd5;
    end else if (((1'b1 == ap_CS_fsm_state10) & ((((((tmp_21_fu_695_p3 == 1'd1) & (icmp_ln157_3_reg_925 == 1'd1)) | ((tmp_21_fu_695_p3 == 1'd1) & (icmp_ln157_4_reg_933 == 1'd0))) | ((tmp_21_fu_695_p3 == 1'd1) & (icmp_ln157_2_reg_917 == 1'd1))) | ((tmp_21_fu_695_p3 == 1'd1) & (icmp_ln157_1_reg_909 == 1'd1))) | ((tmp_21_fu_695_p3 == 1'd1) & (icmp_ln157_reg_750 == 1'd1))))) begin
        grp_edge_index_fu_518_i = 3'd4;
    end else if (((1'b1 == ap_CS_fsm_state8) & (((((tmp_20_fu_683_p3 == 1'd1) & (icmp_ln157_3_reg_925 == 1'd0)) | ((tmp_20_fu_683_p3 == 1'd1) & (icmp_ln157_2_reg_917 == 1'd1))) | ((tmp_20_fu_683_p3 == 1'd1) & (icmp_ln157_1_reg_909 == 1'd1))) | ((tmp_20_fu_683_p3 == 1'd1) & (icmp_ln157_reg_750 == 1'd1))))) begin
        grp_edge_index_fu_518_i = 3'd3;
    end else if (((1'b1 == ap_CS_fsm_state6) & ((((tmp_19_fu_671_p3 == 1'd1) & (icmp_ln157_1_reg_909 == 1'd1)) | ((tmp_19_fu_671_p3 == 1'd1) & (icmp_ln157_2_reg_917 == 1'd0))) | ((tmp_19_fu_671_p3 == 1'd1) & (icmp_ln157_reg_750 == 1'd1))))) begin
        grp_edge_index_fu_518_i = 3'd2;
    end else if (((1'b1 == ap_CS_fsm_state4) & (((tmp_fu_659_p3 == 1'd1) & (icmp_ln157_1_reg_909 == 1'd0)) | ((tmp_fu_659_p3 == 1'd1) & (icmp_ln157_reg_750 == 1'd1))))) begin
        grp_edge_index_fu_518_i = 3'd1;
    end else if (((trunc_ln157_fu_650_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln157_reg_750 == 1'd0))) begin
        grp_edge_index_fu_518_i = 3'd0;
    end else begin
        grp_edge_index_fu_518_i = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln157_reg_750 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & ((icmp_ln157_1_reg_909 == 1'd0) | (icmp_ln157_reg_750 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & ((icmp_ln157_reg_750 == 1'd1) | ((icmp_ln157_2_reg_917 == 1'd0) | (icmp_ln157_1_reg_909 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & ((icmp_ln157_reg_750 == 1'd1) | ((icmp_ln157_1_reg_909 == 1'd1) | ((icmp_ln157_3_reg_925 == 1'd0) | (icmp_ln157_2_reg_917 == 1'd1)))))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & ((icmp_ln157_reg_750 == 1'd1) | ((icmp_ln157_1_reg_909 == 1'd1) | ((icmp_ln157_2_reg_917 == 1'd1) | ((icmp_ln157_4_reg_933 == 1'd0) | (icmp_ln157_3_reg_925 == 1'd1))))))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & ((icmp_ln157_reg_750 == 1'd1) | ((icmp_ln157_1_reg_909 == 1'd1) | ((icmp_ln157_2_reg_917 == 1'd1) | ((icmp_ln157_3_reg_925 == 1'd1) | ((icmp_ln157_5_reg_941 == 1'd0) | (icmp_ln157_4_reg_933 == 1'd1)))))))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & ((icmp_ln157_reg_750 == 1'd1) | ((icmp_ln157_1_reg_909 == 1'd1) | ((icmp_ln157_2_reg_917 == 1'd1) | ((icmp_ln157_3_reg_925 == 1'd1) | ((icmp_ln157_4_reg_933 == 1'd1) | ((icmp_ln157_6_reg_949 == 1'd0) | (icmp_ln157_5_reg_941 == 1'd1))))))))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_fu_536_p57 = 'bx;

assign icmp_ln157_1_fu_654_p2 = ((j == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln157_2_fu_666_p2 = ((j == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln157_3_fu_678_p2 = ((j == 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln157_4_fu_690_p2 = ((j == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln157_5_fu_702_p2 = ((j == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln157_6_fu_714_p2 = ((j == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln157_7_fu_726_p2 = ((j == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln157_fu_644_p2 = ((j == 3'd0) ? 1'b1 : 1'b0);

assign tmp_19_fu_671_p3 = flip_mask[32'd2];

assign tmp_20_fu_683_p3 = flip_mask[32'd3];

assign tmp_21_fu_695_p3 = flip_mask[32'd4];

assign tmp_22_fu_707_p3 = flip_mask[32'd5];

assign tmp_23_fu_719_p3 = flip_mask[32'd6];

assign tmp_24_fu_731_p3 = flip_mask[32'd7];

assign tmp_fu_659_p3 = flip_mask[32'd1];

assign trunc_ln157_fu_650_p1 = flip_mask[0:0];

endmodule //local_spin_flip_operation_selected_coupling_for_j
