// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module local_spin_flip_operation_edge_index (
        ap_ready,
        i,
        j,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [2:0] i;
input  [2:0] j;
output  [4:0] ap_return;
input   ap_rst;

wire   [0:0] icmp_ln68_fu_26_p2;
wire   [2:0] a_fu_32_p3;
wire   [2:0] b_fu_48_p3;
wire   [3:0] zext_ln68_fu_44_p1;
wire  signed [3:0] xor_ln70_fu_60_p2;
wire   [3:0] mul_ln70_fu_70_p0;
wire   [2:0] mul_ln70_fu_70_p1;
wire   [5:0] mul_ln70_fu_70_p2;
wire   [4:0] trunc_ln_fu_76_p4;
wire  signed [4:0] sext_ln70_fu_86_p1;
wire   [4:0] add_ln70_fu_90_p2;
wire   [4:0] zext_ln69_fu_56_p1;
wire   [5:0] mul_ln70_fu_70_p00;
wire   [5:0] mul_ln70_fu_70_p10;

local_spin_flip_operation_mul_4ns_3ns_6_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 6 ))
mul_4ns_3ns_6_1_1_U10(
    .din0(mul_ln70_fu_70_p0),
    .din1(mul_ln70_fu_70_p1),
    .dout(mul_ln70_fu_70_p2)
);

assign a_fu_32_p3 = ((icmp_ln68_fu_26_p2[0:0] == 1'b1) ? i : j);

assign add_ln70_fu_90_p2 = ($signed(trunc_ln_fu_76_p4) + $signed(sext_ln70_fu_86_p1));

assign ap_ready = 1'b1;

assign b_fu_48_p3 = ((icmp_ln68_fu_26_p2[0:0] == 1'b1) ? j : i);

assign mul_ln70_fu_70_p00 = $unsigned(xor_ln70_fu_60_p2);

assign mul_ln70_fu_70_p10 = a_fu_32_p3;

assign sext_ln70_fu_86_p1 = xor_ln70_fu_60_p2;

assign trunc_ln_fu_76_p4 = {{mul_ln70_fu_70_p2[5:1]}};

assign xor_ln70_fu_60_p2 = (zext_ln68_fu_44_p1 ^ 4'd15);

assign zext_ln68_fu_44_p1 = a_fu_32_p3;

assign zext_ln69_fu_56_p1 = b_fu_48_p3;

assign ap_return = (add_ln70_fu_90_p2 + zext_ln69_fu_56_p1);

assign icmp_ln68_fu_26_p2 = ((i < j) ? 1'b1 : 1'b0);

assign mul_ln70_fu_70_p0 = mul_ln70_fu_70_p00;

assign mul_ln70_fu_70_p1 = mul_ln70_fu_70_p10;

endmodule //local_spin_flip_operation_edge_index
