// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module local_spin_flip_operation_tree_sum_2_s (
        ap_ready,
        x_0_val,
        x_1_val,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [8:0] x_0_val;
input  [8:0] x_1_val;
output  [8:0] ap_return;
input   ap_rst;

wire  signed [8:0] sext_ln104_fu_32_p0;
wire  signed [8:0] sext_ln104_12_fu_36_p0;
wire  signed [8:0] add_ln104_fu_40_p0;
wire  signed [8:0] add_ln104_fu_40_p1;
wire  signed [9:0] sext_ln104_12_fu_36_p1;
wire  signed [9:0] sext_ln104_fu_32_p1;
wire   [9:0] add_ln104_12_fu_46_p2;
wire   [8:0] add_ln104_fu_40_p2;
wire   [0:0] tmp_fu_52_p3;
wire   [0:0] tmp_12_fu_60_p3;
wire   [0:0] xor_ln104_fu_68_p2;
wire   [0:0] and_ln104_fu_74_p2;
wire   [0:0] xor_ln104_12_fu_80_p2;
wire   [8:0] select_ln104_fu_86_p3;

assign add_ln104_12_fu_46_p2 = ($signed(sext_ln104_12_fu_36_p1) + $signed(sext_ln104_fu_32_p1));

assign add_ln104_fu_40_p2 = ($signed(add_ln104_fu_40_p0) + $signed(add_ln104_fu_40_p1));

assign and_ln104_fu_74_p2 = (xor_ln104_fu_68_p2 & tmp_12_fu_60_p3);

assign ap_ready = 1'b1;

assign select_ln104_fu_86_p3 = ((and_ln104_fu_74_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign sext_ln104_12_fu_36_p1 = sext_ln104_12_fu_36_p0;

assign sext_ln104_fu_32_p1 = sext_ln104_fu_32_p0;

assign tmp_12_fu_60_p3 = add_ln104_fu_40_p2[32'd8];

assign tmp_fu_52_p3 = add_ln104_12_fu_46_p2[32'd9];

assign xor_ln104_12_fu_80_p2 = (tmp_fu_52_p3 ^ tmp_12_fu_60_p3);

assign xor_ln104_fu_68_p2 = (tmp_fu_52_p3 ^ 1'd1);

assign add_ln104_fu_40_p0 = x_1_val;

assign add_ln104_fu_40_p1 = x_0_val;

assign ap_return = ((xor_ln104_12_fu_80_p2[0:0] == 1'b1) ? select_ln104_fu_86_p3 : add_ln104_fu_40_p2);

assign sext_ln104_12_fu_36_p0 = x_1_val;

assign sext_ln104_fu_32_p0 = x_0_val;

endmodule //local_spin_flip_operation_tree_sum_2_s
