// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module local_spin_flip_operation_local_delta_over_alpha (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        h_0_val1,
        h_1_val2,
        h_2_val3,
        h_3_val4,
        h_4_val5,
        h_5_val6,
        h_6_val7,
        h_7_val8,
        J_edges_0_val16,
        J_edges_1_val24,
        J_edges_2_val32,
        J_edges_3_val40,
        J_edges_4_val48,
        J_edges_5_val56,
        J_edges_6_val64,
        J_edges_7_val72,
        J_edges_8_val80,
        J_edges_9_val88,
        J_edges_10_val96,
        J_edges_11_val104,
        J_edges_12_val112,
        J_edges_13_val120,
        J_edges_14_val128,
        J_edges_15_val136,
        J_edges_16_val144,
        J_edges_17_val152,
        J_edges_18_val160,
        J_edges_19_val168,
        J_edges_20_val176,
        J_edges_21_val184,
        J_edges_22_val192,
        J_edges_23_val200,
        J_edges_24_val208,
        J_edges_25_val216,
        J_edges_26_val224,
        J_edges_27_val232,
        spins,
        flip_mask,
        ap_return
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] h_0_val1;
input  [8:0] h_1_val2;
input  [8:0] h_2_val3;
input  [8:0] h_3_val4;
input  [8:0] h_4_val5;
input  [8:0] h_5_val6;
input  [8:0] h_6_val7;
input  [8:0] h_7_val8;
input  [8:0] J_edges_0_val16;
input  [8:0] J_edges_1_val24;
input  [8:0] J_edges_2_val32;
input  [8:0] J_edges_3_val40;
input  [8:0] J_edges_4_val48;
input  [8:0] J_edges_5_val56;
input  [8:0] J_edges_6_val64;
input  [8:0] J_edges_7_val72;
input  [8:0] J_edges_8_val80;
input  [8:0] J_edges_9_val88;
input  [8:0] J_edges_10_val96;
input  [8:0] J_edges_11_val104;
input  [8:0] J_edges_12_val112;
input  [8:0] J_edges_13_val120;
input  [8:0] J_edges_14_val128;
input  [8:0] J_edges_15_val136;
input  [8:0] J_edges_16_val144;
input  [8:0] J_edges_17_val152;
input  [8:0] J_edges_18_val160;
input  [8:0] J_edges_19_val168;
input  [8:0] J_edges_20_val176;
input  [8:0] J_edges_21_val184;
input  [8:0] J_edges_22_val192;
input  [8:0] J_edges_23_val200;
input  [8:0] J_edges_24_val208;
input  [8:0] J_edges_25_val216;
input  [8:0] J_edges_26_val224;
input  [8:0] J_edges_27_val232;
input  [7:0] spins;
input  [7:0] flip_mask;
output  [8:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [8:0] grp_selected_coupling_for_j_fu_376_ap_return;
reg  signed [8:0] selected_Jij_reg_2868;
wire    ap_CS_fsm_state2;
wire   [8:0] grp_selected_coupling_for_j_fu_440_ap_return;
reg  signed [8:0] selected_Jij_1_reg_2873;
wire   [8:0] grp_selected_coupling_for_j_fu_504_ap_return;
reg  signed [8:0] selected_Jij_2_reg_2878;
wire   [8:0] grp_selected_coupling_for_j_fu_568_ap_return;
reg  signed [8:0] selected_Jij_3_reg_2883;
wire   [8:0] grp_selected_coupling_for_j_fu_632_ap_return;
reg  signed [8:0] selected_Jij_4_reg_2888;
wire   [8:0] grp_selected_coupling_for_j_fu_696_ap_return;
reg  signed [8:0] selected_Jij_5_reg_2893;
wire   [8:0] grp_selected_coupling_for_j_fu_760_ap_return;
reg  signed [8:0] selected_Jij_6_reg_2898;
wire   [8:0] grp_selected_coupling_for_j_fu_824_ap_return;
reg  signed [8:0] selected_Jij_7_reg_2903;
reg   [0:0] tmp_reg_2908;
wire    ap_CS_fsm_state3;
reg   [8:0] trunc_ln_reg_2916;
reg   [0:0] tmp_25_reg_2921;
reg   [0:0] tmp_26_reg_2926;
reg   [0:0] tmp_29_reg_2932;
reg   [8:0] trunc_ln204_1_reg_2940;
reg   [0:0] tmp_30_reg_2945;
reg   [0:0] tmp_31_reg_2950;
reg   [0:0] tmp_34_reg_2956;
reg   [8:0] trunc_ln204_2_reg_2964;
reg   [0:0] tmp_35_reg_2969;
reg   [0:0] tmp_36_reg_2974;
reg   [0:0] tmp_39_reg_2980;
reg   [8:0] trunc_ln204_3_reg_2988;
reg   [0:0] tmp_40_reg_2993;
reg   [0:0] tmp_41_reg_2998;
reg   [0:0] tmp_44_reg_3004;
reg   [8:0] trunc_ln204_4_reg_3012;
reg   [0:0] tmp_45_reg_3017;
reg   [0:0] tmp_46_reg_3022;
reg   [0:0] tmp_49_reg_3028;
reg   [8:0] trunc_ln204_5_reg_3036;
reg   [0:0] tmp_50_reg_3041;
reg   [0:0] tmp_51_reg_3046;
reg   [0:0] tmp_54_reg_3052;
reg   [8:0] trunc_ln204_6_reg_3060;
reg   [0:0] tmp_55_reg_3065;
reg   [0:0] tmp_56_reg_3070;
reg   [0:0] tmp_59_reg_3076;
reg   [8:0] trunc_ln204_7_reg_3084;
reg   [0:0] tmp_60_reg_3089;
reg   [0:0] tmp_61_reg_3094;
wire   [0:0] selected_bit_fu_1411_p2;
reg   [0:0] selected_bit_reg_3100;
wire   [8:0] terms_selected_field_fu_928_ap_return;
reg   [8:0] terms_reg_3105;
wire    ap_CS_fsm_state4;
wire   [8:0] terms_1_fu_1523_p3;
reg   [8:0] terms_1_reg_3110;
wire   [8:0] terms_2_fu_1637_p3;
reg   [8:0] terms_2_reg_3115;
wire   [8:0] terms_3_fu_1751_p3;
reg   [8:0] terms_3_reg_3120;
wire   [8:0] terms_4_fu_1865_p3;
reg   [8:0] terms_4_reg_3125;
wire   [8:0] terms_5_fu_1979_p3;
reg   [8:0] terms_5_reg_3130;
wire   [8:0] terms_6_fu_2093_p3;
reg   [8:0] terms_6_reg_3135;
wire   [8:0] terms_7_fu_2207_p3;
reg   [8:0] terms_7_reg_3140;
wire   [8:0] terms_8_fu_2321_p3;
reg   [8:0] terms_8_reg_3145;
wire   [8:0] grp_tree_sum_9_s_fu_949_ap_return;
reg  signed [8:0] field_over_alpha_reg_3150;
wire    ap_CS_fsm_state6;
wire    grp_selected_coupling_for_j_fu_376_ap_start;
wire    grp_selected_coupling_for_j_fu_376_ap_done;
wire    grp_selected_coupling_for_j_fu_376_ap_idle;
wire    grp_selected_coupling_for_j_fu_376_ap_ready;
wire    grp_selected_coupling_for_j_fu_440_ap_start;
wire    grp_selected_coupling_for_j_fu_440_ap_done;
wire    grp_selected_coupling_for_j_fu_440_ap_idle;
wire    grp_selected_coupling_for_j_fu_440_ap_ready;
wire    grp_selected_coupling_for_j_fu_504_ap_start;
wire    grp_selected_coupling_for_j_fu_504_ap_done;
wire    grp_selected_coupling_for_j_fu_504_ap_idle;
wire    grp_selected_coupling_for_j_fu_504_ap_ready;
wire    grp_selected_coupling_for_j_fu_568_ap_start;
wire    grp_selected_coupling_for_j_fu_568_ap_done;
wire    grp_selected_coupling_for_j_fu_568_ap_idle;
wire    grp_selected_coupling_for_j_fu_568_ap_ready;
wire    grp_selected_coupling_for_j_fu_632_ap_start;
wire    grp_selected_coupling_for_j_fu_632_ap_done;
wire    grp_selected_coupling_for_j_fu_632_ap_idle;
wire    grp_selected_coupling_for_j_fu_632_ap_ready;
wire    grp_selected_coupling_for_j_fu_696_ap_start;
wire    grp_selected_coupling_for_j_fu_696_ap_done;
wire    grp_selected_coupling_for_j_fu_696_ap_idle;
wire    grp_selected_coupling_for_j_fu_696_ap_ready;
wire    grp_selected_coupling_for_j_fu_760_ap_start;
wire    grp_selected_coupling_for_j_fu_760_ap_done;
wire    grp_selected_coupling_for_j_fu_760_ap_idle;
wire    grp_selected_coupling_for_j_fu_760_ap_ready;
wire    grp_selected_coupling_for_j_fu_824_ap_start;
wire    grp_selected_coupling_for_j_fu_824_ap_done;
wire    grp_selected_coupling_for_j_fu_824_ap_idle;
wire    grp_selected_coupling_for_j_fu_824_ap_ready;
wire    ref_tmp4_assign_s_spin_value_fu_888_ap_ready;
wire   [0:0] ref_tmp4_assign_s_spin_value_fu_888_b;
wire  signed [8:0] ref_tmp4_assign_s_spin_value_fu_888_ap_return;
wire    ref_tmp4_assign_1_spin_value_fu_893_ap_ready;
wire   [0:0] ref_tmp4_assign_1_spin_value_fu_893_b;
wire  signed [8:0] ref_tmp4_assign_1_spin_value_fu_893_ap_return;
wire    ref_tmp4_assign_2_spin_value_fu_898_ap_ready;
wire   [0:0] ref_tmp4_assign_2_spin_value_fu_898_b;
wire  signed [8:0] ref_tmp4_assign_2_spin_value_fu_898_ap_return;
wire    ref_tmp4_assign_3_spin_value_fu_903_ap_ready;
wire   [0:0] ref_tmp4_assign_3_spin_value_fu_903_b;
wire  signed [8:0] ref_tmp4_assign_3_spin_value_fu_903_ap_return;
wire    ref_tmp4_assign_4_spin_value_fu_908_ap_ready;
wire   [0:0] ref_tmp4_assign_4_spin_value_fu_908_b;
wire  signed [8:0] ref_tmp4_assign_4_spin_value_fu_908_ap_return;
wire    ref_tmp4_assign_9_spin_value_fu_913_ap_ready;
wire   [0:0] ref_tmp4_assign_9_spin_value_fu_913_b;
wire  signed [8:0] ref_tmp4_assign_9_spin_value_fu_913_ap_return;
wire    ref_tmp4_assign_8_spin_value_fu_918_ap_ready;
wire   [0:0] ref_tmp4_assign_8_spin_value_fu_918_b;
wire  signed [8:0] ref_tmp4_assign_8_spin_value_fu_918_ap_return;
wire    ref_tmp4_assign_7_spin_value_fu_923_ap_ready;
wire   [0:0] ref_tmp4_assign_7_spin_value_fu_923_b;
wire  signed [8:0] ref_tmp4_assign_7_spin_value_fu_923_ap_return;
wire    terms_selected_field_fu_928_ap_ready;
wire    grp_tree_sum_9_s_fu_949_ap_start;
wire    grp_tree_sum_9_s_fu_949_ap_done;
wire    grp_tree_sum_9_s_fu_949_ap_idle;
wire    grp_tree_sum_9_s_fu_949_ap_ready;
reg    grp_selected_coupling_for_j_fu_376_ap_start_reg;
reg    grp_selected_coupling_for_j_fu_440_ap_start_reg;
reg    grp_selected_coupling_for_j_fu_504_ap_start_reg;
reg    grp_selected_coupling_for_j_fu_568_ap_start_reg;
reg    grp_selected_coupling_for_j_fu_632_ap_start_reg;
reg    grp_selected_coupling_for_j_fu_696_ap_start_reg;
reg    grp_selected_coupling_for_j_fu_760_ap_start_reg;
reg    grp_selected_coupling_for_j_fu_824_ap_start_reg;
reg    grp_tree_sum_9_s_fu_949_ap_start_reg;
wire    ap_CS_fsm_state5;
wire   [17:0] mul_ln204_fu_974_p2;
wire   [17:0] mul_ln204_1_fu_1030_p2;
wire   [17:0] mul_ln204_2_fu_1086_p2;
wire   [17:0] mul_ln204_3_fu_1142_p2;
wire   [17:0] mul_ln204_4_fu_1198_p2;
wire   [17:0] mul_ln204_5_fu_1254_p2;
wire   [17:0] mul_ln204_6_fu_1310_p2;
wire   [17:0] mul_ln204_7_fu_1366_p2;
wire   [7:0] and_ln212_fu_1406_p2;
wire   [8:0] zext_ln204_fu_1417_p1;
wire   [8:0] add_ln204_fu_1420_p2;
wire   [0:0] tmp_27_fu_1425_p3;
wire   [0:0] xor_ln204_fu_1433_p2;
wire   [0:0] and_ln204_fu_1439_p2;
wire   [0:0] xor_ln204_1_fu_1444_p2;
wire   [0:0] xor_ln204_2_fu_1463_p2;
wire   [0:0] select_ln204_fu_1449_p3;
wire   [0:0] xor_ln204_3_fu_1474_p2;
wire   [0:0] or_ln204_1_fu_1480_p2;
wire   [0:0] select_ln204_1_fu_1456_p3;
wire   [0:0] and_ln204_2_fu_1492_p2;
wire   [0:0] or_ln204_fu_1468_p2;
wire   [0:0] xor_ln204_4_fu_1498_p2;
wire   [0:0] and_ln204_1_fu_1486_p2;
wire   [0:0] and_ln204_3_fu_1504_p2;
wire   [0:0] or_ln204_2_fu_1517_p2;
wire   [8:0] select_ln204_2_fu_1509_p3;
wire   [8:0] zext_ln204_1_fu_1531_p1;
wire   [8:0] add_ln204_1_fu_1534_p2;
wire   [0:0] tmp_32_fu_1539_p3;
wire   [0:0] xor_ln204_5_fu_1547_p2;
wire   [0:0] and_ln204_4_fu_1553_p2;
wire   [0:0] xor_ln204_6_fu_1558_p2;
wire   [0:0] xor_ln204_7_fu_1577_p2;
wire   [0:0] select_ln204_4_fu_1563_p3;
wire   [0:0] xor_ln204_8_fu_1588_p2;
wire   [0:0] or_ln204_4_fu_1594_p2;
wire   [0:0] select_ln204_5_fu_1570_p3;
wire   [0:0] and_ln204_6_fu_1606_p2;
wire   [0:0] or_ln204_3_fu_1582_p2;
wire   [0:0] xor_ln204_9_fu_1612_p2;
wire   [0:0] and_ln204_5_fu_1600_p2;
wire   [0:0] and_ln204_7_fu_1618_p2;
wire   [0:0] or_ln204_5_fu_1631_p2;
wire   [8:0] select_ln204_6_fu_1623_p3;
wire   [8:0] zext_ln204_2_fu_1645_p1;
wire   [8:0] add_ln204_2_fu_1648_p2;
wire   [0:0] tmp_37_fu_1653_p3;
wire   [0:0] xor_ln204_10_fu_1661_p2;
wire   [0:0] and_ln204_8_fu_1667_p2;
wire   [0:0] xor_ln204_11_fu_1672_p2;
wire   [0:0] xor_ln204_12_fu_1691_p2;
wire   [0:0] select_ln204_8_fu_1677_p3;
wire   [0:0] xor_ln204_13_fu_1702_p2;
wire   [0:0] or_ln204_7_fu_1708_p2;
wire   [0:0] select_ln204_9_fu_1684_p3;
wire   [0:0] and_ln204_10_fu_1720_p2;
wire   [0:0] or_ln204_6_fu_1696_p2;
wire   [0:0] xor_ln204_14_fu_1726_p2;
wire   [0:0] and_ln204_9_fu_1714_p2;
wire   [0:0] and_ln204_11_fu_1732_p2;
wire   [0:0] or_ln204_8_fu_1745_p2;
wire   [8:0] select_ln204_10_fu_1737_p3;
wire   [8:0] zext_ln204_3_fu_1759_p1;
wire   [8:0] add_ln204_3_fu_1762_p2;
wire   [0:0] tmp_42_fu_1767_p3;
wire   [0:0] xor_ln204_15_fu_1775_p2;
wire   [0:0] and_ln204_12_fu_1781_p2;
wire   [0:0] xor_ln204_16_fu_1786_p2;
wire   [0:0] xor_ln204_17_fu_1805_p2;
wire   [0:0] select_ln204_12_fu_1791_p3;
wire   [0:0] xor_ln204_18_fu_1816_p2;
wire   [0:0] or_ln204_10_fu_1822_p2;
wire   [0:0] select_ln204_13_fu_1798_p3;
wire   [0:0] and_ln204_14_fu_1834_p2;
wire   [0:0] or_ln204_9_fu_1810_p2;
wire   [0:0] xor_ln204_19_fu_1840_p2;
wire   [0:0] and_ln204_13_fu_1828_p2;
wire   [0:0] and_ln204_15_fu_1846_p2;
wire   [0:0] or_ln204_11_fu_1859_p2;
wire   [8:0] select_ln204_14_fu_1851_p3;
wire   [8:0] zext_ln204_4_fu_1873_p1;
wire   [8:0] add_ln204_4_fu_1876_p2;
wire   [0:0] tmp_47_fu_1881_p3;
wire   [0:0] xor_ln204_20_fu_1889_p2;
wire   [0:0] and_ln204_16_fu_1895_p2;
wire   [0:0] xor_ln204_21_fu_1900_p2;
wire   [0:0] xor_ln204_22_fu_1919_p2;
wire   [0:0] select_ln204_16_fu_1905_p3;
wire   [0:0] xor_ln204_23_fu_1930_p2;
wire   [0:0] or_ln204_13_fu_1936_p2;
wire   [0:0] select_ln204_17_fu_1912_p3;
wire   [0:0] and_ln204_18_fu_1948_p2;
wire   [0:0] or_ln204_12_fu_1924_p2;
wire   [0:0] xor_ln204_24_fu_1954_p2;
wire   [0:0] and_ln204_17_fu_1942_p2;
wire   [0:0] and_ln204_19_fu_1960_p2;
wire   [0:0] or_ln204_14_fu_1973_p2;
wire   [8:0] select_ln204_18_fu_1965_p3;
wire   [8:0] zext_ln204_5_fu_1987_p1;
wire   [8:0] add_ln204_5_fu_1990_p2;
wire   [0:0] tmp_52_fu_1995_p3;
wire   [0:0] xor_ln204_25_fu_2003_p2;
wire   [0:0] and_ln204_20_fu_2009_p2;
wire   [0:0] xor_ln204_26_fu_2014_p2;
wire   [0:0] xor_ln204_27_fu_2033_p2;
wire   [0:0] select_ln204_20_fu_2019_p3;
wire   [0:0] xor_ln204_28_fu_2044_p2;
wire   [0:0] or_ln204_16_fu_2050_p2;
wire   [0:0] select_ln204_21_fu_2026_p3;
wire   [0:0] and_ln204_22_fu_2062_p2;
wire   [0:0] or_ln204_15_fu_2038_p2;
wire   [0:0] xor_ln204_29_fu_2068_p2;
wire   [0:0] and_ln204_21_fu_2056_p2;
wire   [0:0] and_ln204_23_fu_2074_p2;
wire   [0:0] or_ln204_17_fu_2087_p2;
wire   [8:0] select_ln204_22_fu_2079_p3;
wire   [8:0] zext_ln204_6_fu_2101_p1;
wire   [8:0] add_ln204_6_fu_2104_p2;
wire   [0:0] tmp_57_fu_2109_p3;
wire   [0:0] xor_ln204_30_fu_2117_p2;
wire   [0:0] and_ln204_24_fu_2123_p2;
wire   [0:0] xor_ln204_31_fu_2128_p2;
wire   [0:0] xor_ln204_32_fu_2147_p2;
wire   [0:0] select_ln204_24_fu_2133_p3;
wire   [0:0] xor_ln204_33_fu_2158_p2;
wire   [0:0] or_ln204_19_fu_2164_p2;
wire   [0:0] select_ln204_25_fu_2140_p3;
wire   [0:0] and_ln204_26_fu_2176_p2;
wire   [0:0] or_ln204_18_fu_2152_p2;
wire   [0:0] xor_ln204_34_fu_2182_p2;
wire   [0:0] and_ln204_25_fu_2170_p2;
wire   [0:0] and_ln204_27_fu_2188_p2;
wire   [0:0] or_ln204_20_fu_2201_p2;
wire   [8:0] select_ln204_26_fu_2193_p3;
wire   [8:0] zext_ln204_7_fu_2215_p1;
wire   [8:0] add_ln204_7_fu_2218_p2;
wire   [0:0] tmp_62_fu_2223_p3;
wire   [0:0] xor_ln204_35_fu_2231_p2;
wire   [0:0] and_ln204_28_fu_2237_p2;
wire   [0:0] xor_ln204_36_fu_2242_p2;
wire   [0:0] xor_ln204_37_fu_2261_p2;
wire   [0:0] select_ln204_28_fu_2247_p3;
wire   [0:0] xor_ln204_38_fu_2272_p2;
wire   [0:0] or_ln204_22_fu_2278_p2;
wire   [0:0] select_ln204_29_fu_2254_p3;
wire   [0:0] and_ln204_30_fu_2290_p2;
wire   [0:0] or_ln204_21_fu_2266_p2;
wire   [0:0] xor_ln204_39_fu_2296_p2;
wire   [0:0] and_ln204_29_fu_2284_p2;
wire   [0:0] and_ln204_31_fu_2302_p2;
wire   [0:0] or_ln204_23_fu_2315_p2;
wire   [8:0] select_ln204_30_fu_2307_p3;
wire    ap_CS_fsm_state7;
wire  signed [9:0] sext_ln209_fu_2329_p1;
wire   [9:0] sub_ln209_fu_2332_p2;
wire   [0:0] tmp_63_fu_2342_p3;
wire   [0:0] tmp_64_fu_2350_p3;
wire   [0:0] xor_ln209_fu_2358_p2;
wire   [0:0] xor_ln209_1_fu_2370_p2;
wire   [0:0] xor_ln209_2_fu_2382_p2;
wire   [0:0] and_ln209_fu_2364_p2;
wire   [0:0] xor_ln209_3_fu_2388_p2;
wire   [8:0] neg_field_over_alpha_fu_2338_p1;
wire   [0:0] and_ln209_1_fu_2376_p2;
wire   [0:0] or_ln209_fu_2394_p2;
wire   [8:0] select_ln209_fu_2400_p3;
wire   [8:0] select_ln209_1_fu_2408_p3;
wire   [8:0] select_ln209_2_fu_2416_p3;
wire   [8:0] signed_field_fu_2424_p3;
wire   [0:0] tmp_65_fu_2436_p3;
wire   [0:0] tmp_66_fu_2444_p3;
wire   [0:0] xor_ln214_fu_2452_p2;
wire   [0:0] xor_ln214_1_fu_2464_p2;
wire   [0:0] xor_ln214_2_fu_2476_p2;
wire   [0:0] and_ln214_fu_2458_p2;
wire   [0:0] xor_ln214_3_fu_2482_p2;
wire   [8:0] shl_ln214_fu_2430_p2;
wire   [0:0] and_ln214_1_fu_2470_p2;
wire   [0:0] or_ln214_fu_2488_p2;
wire   [8:0] select_ln214_fu_2494_p3;
wire   [8:0] select_ln214_1_fu_2502_p3;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_selected_coupling_for_j_fu_376_ap_start_reg = 1'b0;
#0 grp_selected_coupling_for_j_fu_440_ap_start_reg = 1'b0;
#0 grp_selected_coupling_for_j_fu_504_ap_start_reg = 1'b0;
#0 grp_selected_coupling_for_j_fu_568_ap_start_reg = 1'b0;
#0 grp_selected_coupling_for_j_fu_632_ap_start_reg = 1'b0;
#0 grp_selected_coupling_for_j_fu_696_ap_start_reg = 1'b0;
#0 grp_selected_coupling_for_j_fu_760_ap_start_reg = 1'b0;
#0 grp_selected_coupling_for_j_fu_824_ap_start_reg = 1'b0;
#0 grp_tree_sum_9_s_fu_949_ap_start_reg = 1'b0;
end

local_spin_flip_operation_selected_coupling_for_j grp_selected_coupling_for_j_fu_376(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_selected_coupling_for_j_fu_376_ap_start),
    .ap_done(grp_selected_coupling_for_j_fu_376_ap_done),
    .ap_idle(grp_selected_coupling_for_j_fu_376_ap_idle),
    .ap_ready(grp_selected_coupling_for_j_fu_376_ap_ready),
    .J_edges_0_val(J_edges_0_val16),
    .J_edges_1_val(J_edges_1_val24),
    .J_edges_2_val(J_edges_2_val32),
    .J_edges_3_val(J_edges_3_val40),
    .J_edges_4_val(J_edges_4_val48),
    .J_edges_5_val(J_edges_5_val56),
    .J_edges_6_val(J_edges_6_val64),
    .J_edges_7_val(J_edges_7_val72),
    .J_edges_8_val(J_edges_8_val80),
    .J_edges_9_val(J_edges_9_val88),
    .J_edges_10_val(J_edges_10_val96),
    .J_edges_11_val(J_edges_11_val104),
    .J_edges_12_val(J_edges_12_val112),
    .J_edges_13_val(J_edges_13_val120),
    .J_edges_14_val(J_edges_14_val128),
    .J_edges_15_val(J_edges_15_val136),
    .J_edges_16_val(J_edges_16_val144),
    .J_edges_17_val(J_edges_17_val152),
    .J_edges_18_val(J_edges_18_val160),
    .J_edges_19_val(J_edges_19_val168),
    .J_edges_20_val(J_edges_20_val176),
    .J_edges_21_val(J_edges_21_val184),
    .J_edges_22_val(J_edges_22_val192),
    .J_edges_23_val(J_edges_23_val200),
    .J_edges_24_val(J_edges_24_val208),
    .J_edges_25_val(J_edges_25_val216),
    .J_edges_26_val(J_edges_26_val224),
    .J_edges_27_val(J_edges_27_val232),
    .flip_mask(flip_mask),
    .j(3'd0),
    .ap_return(grp_selected_coupling_for_j_fu_376_ap_return)
);

local_spin_flip_operation_selected_coupling_for_j grp_selected_coupling_for_j_fu_440(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_selected_coupling_for_j_fu_440_ap_start),
    .ap_done(grp_selected_coupling_for_j_fu_440_ap_done),
    .ap_idle(grp_selected_coupling_for_j_fu_440_ap_idle),
    .ap_ready(grp_selected_coupling_for_j_fu_440_ap_ready),
    .J_edges_0_val(J_edges_0_val16),
    .J_edges_1_val(J_edges_1_val24),
    .J_edges_2_val(J_edges_2_val32),
    .J_edges_3_val(J_edges_3_val40),
    .J_edges_4_val(J_edges_4_val48),
    .J_edges_5_val(J_edges_5_val56),
    .J_edges_6_val(J_edges_6_val64),
    .J_edges_7_val(J_edges_7_val72),
    .J_edges_8_val(J_edges_8_val80),
    .J_edges_9_val(J_edges_9_val88),
    .J_edges_10_val(J_edges_10_val96),
    .J_edges_11_val(J_edges_11_val104),
    .J_edges_12_val(J_edges_12_val112),
    .J_edges_13_val(J_edges_13_val120),
    .J_edges_14_val(J_edges_14_val128),
    .J_edges_15_val(J_edges_15_val136),
    .J_edges_16_val(J_edges_16_val144),
    .J_edges_17_val(J_edges_17_val152),
    .J_edges_18_val(J_edges_18_val160),
    .J_edges_19_val(J_edges_19_val168),
    .J_edges_20_val(J_edges_20_val176),
    .J_edges_21_val(J_edges_21_val184),
    .J_edges_22_val(J_edges_22_val192),
    .J_edges_23_val(J_edges_23_val200),
    .J_edges_24_val(J_edges_24_val208),
    .J_edges_25_val(J_edges_25_val216),
    .J_edges_26_val(J_edges_26_val224),
    .J_edges_27_val(J_edges_27_val232),
    .flip_mask(flip_mask),
    .j(3'd1),
    .ap_return(grp_selected_coupling_for_j_fu_440_ap_return)
);

local_spin_flip_operation_selected_coupling_for_j grp_selected_coupling_for_j_fu_504(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_selected_coupling_for_j_fu_504_ap_start),
    .ap_done(grp_selected_coupling_for_j_fu_504_ap_done),
    .ap_idle(grp_selected_coupling_for_j_fu_504_ap_idle),
    .ap_ready(grp_selected_coupling_for_j_fu_504_ap_ready),
    .J_edges_0_val(J_edges_0_val16),
    .J_edges_1_val(J_edges_1_val24),
    .J_edges_2_val(J_edges_2_val32),
    .J_edges_3_val(J_edges_3_val40),
    .J_edges_4_val(J_edges_4_val48),
    .J_edges_5_val(J_edges_5_val56),
    .J_edges_6_val(J_edges_6_val64),
    .J_edges_7_val(J_edges_7_val72),
    .J_edges_8_val(J_edges_8_val80),
    .J_edges_9_val(J_edges_9_val88),
    .J_edges_10_val(J_edges_10_val96),
    .J_edges_11_val(J_edges_11_val104),
    .J_edges_12_val(J_edges_12_val112),
    .J_edges_13_val(J_edges_13_val120),
    .J_edges_14_val(J_edges_14_val128),
    .J_edges_15_val(J_edges_15_val136),
    .J_edges_16_val(J_edges_16_val144),
    .J_edges_17_val(J_edges_17_val152),
    .J_edges_18_val(J_edges_18_val160),
    .J_edges_19_val(J_edges_19_val168),
    .J_edges_20_val(J_edges_20_val176),
    .J_edges_21_val(J_edges_21_val184),
    .J_edges_22_val(J_edges_22_val192),
    .J_edges_23_val(J_edges_23_val200),
    .J_edges_24_val(J_edges_24_val208),
    .J_edges_25_val(J_edges_25_val216),
    .J_edges_26_val(J_edges_26_val224),
    .J_edges_27_val(J_edges_27_val232),
    .flip_mask(flip_mask),
    .j(3'd2),
    .ap_return(grp_selected_coupling_for_j_fu_504_ap_return)
);

local_spin_flip_operation_selected_coupling_for_j grp_selected_coupling_for_j_fu_568(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_selected_coupling_for_j_fu_568_ap_start),
    .ap_done(grp_selected_coupling_for_j_fu_568_ap_done),
    .ap_idle(grp_selected_coupling_for_j_fu_568_ap_idle),
    .ap_ready(grp_selected_coupling_for_j_fu_568_ap_ready),
    .J_edges_0_val(J_edges_0_val16),
    .J_edges_1_val(J_edges_1_val24),
    .J_edges_2_val(J_edges_2_val32),
    .J_edges_3_val(J_edges_3_val40),
    .J_edges_4_val(J_edges_4_val48),
    .J_edges_5_val(J_edges_5_val56),
    .J_edges_6_val(J_edges_6_val64),
    .J_edges_7_val(J_edges_7_val72),
    .J_edges_8_val(J_edges_8_val80),
    .J_edges_9_val(J_edges_9_val88),
    .J_edges_10_val(J_edges_10_val96),
    .J_edges_11_val(J_edges_11_val104),
    .J_edges_12_val(J_edges_12_val112),
    .J_edges_13_val(J_edges_13_val120),
    .J_edges_14_val(J_edges_14_val128),
    .J_edges_15_val(J_edges_15_val136),
    .J_edges_16_val(J_edges_16_val144),
    .J_edges_17_val(J_edges_17_val152),
    .J_edges_18_val(J_edges_18_val160),
    .J_edges_19_val(J_edges_19_val168),
    .J_edges_20_val(J_edges_20_val176),
    .J_edges_21_val(J_edges_21_val184),
    .J_edges_22_val(J_edges_22_val192),
    .J_edges_23_val(J_edges_23_val200),
    .J_edges_24_val(J_edges_24_val208),
    .J_edges_25_val(J_edges_25_val216),
    .J_edges_26_val(J_edges_26_val224),
    .J_edges_27_val(J_edges_27_val232),
    .flip_mask(flip_mask),
    .j(3'd3),
    .ap_return(grp_selected_coupling_for_j_fu_568_ap_return)
);

local_spin_flip_operation_selected_coupling_for_j grp_selected_coupling_for_j_fu_632(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_selected_coupling_for_j_fu_632_ap_start),
    .ap_done(grp_selected_coupling_for_j_fu_632_ap_done),
    .ap_idle(grp_selected_coupling_for_j_fu_632_ap_idle),
    .ap_ready(grp_selected_coupling_for_j_fu_632_ap_ready),
    .J_edges_0_val(J_edges_0_val16),
    .J_edges_1_val(J_edges_1_val24),
    .J_edges_2_val(J_edges_2_val32),
    .J_edges_3_val(J_edges_3_val40),
    .J_edges_4_val(J_edges_4_val48),
    .J_edges_5_val(J_edges_5_val56),
    .J_edges_6_val(J_edges_6_val64),
    .J_edges_7_val(J_edges_7_val72),
    .J_edges_8_val(J_edges_8_val80),
    .J_edges_9_val(J_edges_9_val88),
    .J_edges_10_val(J_edges_10_val96),
    .J_edges_11_val(J_edges_11_val104),
    .J_edges_12_val(J_edges_12_val112),
    .J_edges_13_val(J_edges_13_val120),
    .J_edges_14_val(J_edges_14_val128),
    .J_edges_15_val(J_edges_15_val136),
    .J_edges_16_val(J_edges_16_val144),
    .J_edges_17_val(J_edges_17_val152),
    .J_edges_18_val(J_edges_18_val160),
    .J_edges_19_val(J_edges_19_val168),
    .J_edges_20_val(J_edges_20_val176),
    .J_edges_21_val(J_edges_21_val184),
    .J_edges_22_val(J_edges_22_val192),
    .J_edges_23_val(J_edges_23_val200),
    .J_edges_24_val(J_edges_24_val208),
    .J_edges_25_val(J_edges_25_val216),
    .J_edges_26_val(J_edges_26_val224),
    .J_edges_27_val(J_edges_27_val232),
    .flip_mask(flip_mask),
    .j(3'd4),
    .ap_return(grp_selected_coupling_for_j_fu_632_ap_return)
);

local_spin_flip_operation_selected_coupling_for_j grp_selected_coupling_for_j_fu_696(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_selected_coupling_for_j_fu_696_ap_start),
    .ap_done(grp_selected_coupling_for_j_fu_696_ap_done),
    .ap_idle(grp_selected_coupling_for_j_fu_696_ap_idle),
    .ap_ready(grp_selected_coupling_for_j_fu_696_ap_ready),
    .J_edges_0_val(J_edges_0_val16),
    .J_edges_1_val(J_edges_1_val24),
    .J_edges_2_val(J_edges_2_val32),
    .J_edges_3_val(J_edges_3_val40),
    .J_edges_4_val(J_edges_4_val48),
    .J_edges_5_val(J_edges_5_val56),
    .J_edges_6_val(J_edges_6_val64),
    .J_edges_7_val(J_edges_7_val72),
    .J_edges_8_val(J_edges_8_val80),
    .J_edges_9_val(J_edges_9_val88),
    .J_edges_10_val(J_edges_10_val96),
    .J_edges_11_val(J_edges_11_val104),
    .J_edges_12_val(J_edges_12_val112),
    .J_edges_13_val(J_edges_13_val120),
    .J_edges_14_val(J_edges_14_val128),
    .J_edges_15_val(J_edges_15_val136),
    .J_edges_16_val(J_edges_16_val144),
    .J_edges_17_val(J_edges_17_val152),
    .J_edges_18_val(J_edges_18_val160),
    .J_edges_19_val(J_edges_19_val168),
    .J_edges_20_val(J_edges_20_val176),
    .J_edges_21_val(J_edges_21_val184),
    .J_edges_22_val(J_edges_22_val192),
    .J_edges_23_val(J_edges_23_val200),
    .J_edges_24_val(J_edges_24_val208),
    .J_edges_25_val(J_edges_25_val216),
    .J_edges_26_val(J_edges_26_val224),
    .J_edges_27_val(J_edges_27_val232),
    .flip_mask(flip_mask),
    .j(3'd5),
    .ap_return(grp_selected_coupling_for_j_fu_696_ap_return)
);

local_spin_flip_operation_selected_coupling_for_j grp_selected_coupling_for_j_fu_760(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_selected_coupling_for_j_fu_760_ap_start),
    .ap_done(grp_selected_coupling_for_j_fu_760_ap_done),
    .ap_idle(grp_selected_coupling_for_j_fu_760_ap_idle),
    .ap_ready(grp_selected_coupling_for_j_fu_760_ap_ready),
    .J_edges_0_val(J_edges_0_val16),
    .J_edges_1_val(J_edges_1_val24),
    .J_edges_2_val(J_edges_2_val32),
    .J_edges_3_val(J_edges_3_val40),
    .J_edges_4_val(J_edges_4_val48),
    .J_edges_5_val(J_edges_5_val56),
    .J_edges_6_val(J_edges_6_val64),
    .J_edges_7_val(J_edges_7_val72),
    .J_edges_8_val(J_edges_8_val80),
    .J_edges_9_val(J_edges_9_val88),
    .J_edges_10_val(J_edges_10_val96),
    .J_edges_11_val(J_edges_11_val104),
    .J_edges_12_val(J_edges_12_val112),
    .J_edges_13_val(J_edges_13_val120),
    .J_edges_14_val(J_edges_14_val128),
    .J_edges_15_val(J_edges_15_val136),
    .J_edges_16_val(J_edges_16_val144),
    .J_edges_17_val(J_edges_17_val152),
    .J_edges_18_val(J_edges_18_val160),
    .J_edges_19_val(J_edges_19_val168),
    .J_edges_20_val(J_edges_20_val176),
    .J_edges_21_val(J_edges_21_val184),
    .J_edges_22_val(J_edges_22_val192),
    .J_edges_23_val(J_edges_23_val200),
    .J_edges_24_val(J_edges_24_val208),
    .J_edges_25_val(J_edges_25_val216),
    .J_edges_26_val(J_edges_26_val224),
    .J_edges_27_val(J_edges_27_val232),
    .flip_mask(flip_mask),
    .j(3'd6),
    .ap_return(grp_selected_coupling_for_j_fu_760_ap_return)
);

local_spin_flip_operation_selected_coupling_for_j grp_selected_coupling_for_j_fu_824(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_selected_coupling_for_j_fu_824_ap_start),
    .ap_done(grp_selected_coupling_for_j_fu_824_ap_done),
    .ap_idle(grp_selected_coupling_for_j_fu_824_ap_idle),
    .ap_ready(grp_selected_coupling_for_j_fu_824_ap_ready),
    .J_edges_0_val(J_edges_0_val16),
    .J_edges_1_val(J_edges_1_val24),
    .J_edges_2_val(J_edges_2_val32),
    .J_edges_3_val(J_edges_3_val40),
    .J_edges_4_val(J_edges_4_val48),
    .J_edges_5_val(J_edges_5_val56),
    .J_edges_6_val(J_edges_6_val64),
    .J_edges_7_val(J_edges_7_val72),
    .J_edges_8_val(J_edges_8_val80),
    .J_edges_9_val(J_edges_9_val88),
    .J_edges_10_val(J_edges_10_val96),
    .J_edges_11_val(J_edges_11_val104),
    .J_edges_12_val(J_edges_12_val112),
    .J_edges_13_val(J_edges_13_val120),
    .J_edges_14_val(J_edges_14_val128),
    .J_edges_15_val(J_edges_15_val136),
    .J_edges_16_val(J_edges_16_val144),
    .J_edges_17_val(J_edges_17_val152),
    .J_edges_18_val(J_edges_18_val160),
    .J_edges_19_val(J_edges_19_val168),
    .J_edges_20_val(J_edges_20_val176),
    .J_edges_21_val(J_edges_21_val184),
    .J_edges_22_val(J_edges_22_val192),
    .J_edges_23_val(J_edges_23_val200),
    .J_edges_24_val(J_edges_24_val208),
    .J_edges_25_val(J_edges_25_val216),
    .J_edges_26_val(J_edges_26_val224),
    .J_edges_27_val(J_edges_27_val232),
    .flip_mask(flip_mask),
    .j(3'd7),
    .ap_return(grp_selected_coupling_for_j_fu_824_ap_return)
);

local_spin_flip_operation_spin_value ref_tmp4_assign_s_spin_value_fu_888(
    .ap_ready(ref_tmp4_assign_s_spin_value_fu_888_ap_ready),
    .b(ref_tmp4_assign_s_spin_value_fu_888_b),
    .ap_return(ref_tmp4_assign_s_spin_value_fu_888_ap_return),
    .ap_rst(ap_rst)
);

local_spin_flip_operation_spin_value ref_tmp4_assign_1_spin_value_fu_893(
    .ap_ready(ref_tmp4_assign_1_spin_value_fu_893_ap_ready),
    .b(ref_tmp4_assign_1_spin_value_fu_893_b),
    .ap_return(ref_tmp4_assign_1_spin_value_fu_893_ap_return),
    .ap_rst(ap_rst)
);

local_spin_flip_operation_spin_value ref_tmp4_assign_2_spin_value_fu_898(
    .ap_ready(ref_tmp4_assign_2_spin_value_fu_898_ap_ready),
    .b(ref_tmp4_assign_2_spin_value_fu_898_b),
    .ap_return(ref_tmp4_assign_2_spin_value_fu_898_ap_return),
    .ap_rst(ap_rst)
);

local_spin_flip_operation_spin_value ref_tmp4_assign_3_spin_value_fu_903(
    .ap_ready(ref_tmp4_assign_3_spin_value_fu_903_ap_ready),
    .b(ref_tmp4_assign_3_spin_value_fu_903_b),
    .ap_return(ref_tmp4_assign_3_spin_value_fu_903_ap_return),
    .ap_rst(ap_rst)
);

local_spin_flip_operation_spin_value ref_tmp4_assign_4_spin_value_fu_908(
    .ap_ready(ref_tmp4_assign_4_spin_value_fu_908_ap_ready),
    .b(ref_tmp4_assign_4_spin_value_fu_908_b),
    .ap_return(ref_tmp4_assign_4_spin_value_fu_908_ap_return),
    .ap_rst(ap_rst)
);

local_spin_flip_operation_spin_value ref_tmp4_assign_9_spin_value_fu_913(
    .ap_ready(ref_tmp4_assign_9_spin_value_fu_913_ap_ready),
    .b(ref_tmp4_assign_9_spin_value_fu_913_b),
    .ap_return(ref_tmp4_assign_9_spin_value_fu_913_ap_return),
    .ap_rst(ap_rst)
);

local_spin_flip_operation_spin_value ref_tmp4_assign_8_spin_value_fu_918(
    .ap_ready(ref_tmp4_assign_8_spin_value_fu_918_ap_ready),
    .b(ref_tmp4_assign_8_spin_value_fu_918_b),
    .ap_return(ref_tmp4_assign_8_spin_value_fu_918_ap_return),
    .ap_rst(ap_rst)
);

local_spin_flip_operation_spin_value ref_tmp4_assign_7_spin_value_fu_923(
    .ap_ready(ref_tmp4_assign_7_spin_value_fu_923_ap_ready),
    .b(ref_tmp4_assign_7_spin_value_fu_923_b),
    .ap_return(ref_tmp4_assign_7_spin_value_fu_923_ap_return),
    .ap_rst(ap_rst)
);

local_spin_flip_operation_selected_field terms_selected_field_fu_928(
    .ap_ready(terms_selected_field_fu_928_ap_ready),
    .h_0_val(h_0_val1),
    .h_1_val(h_1_val2),
    .h_2_val(h_2_val3),
    .h_3_val(h_3_val4),
    .h_4_val(h_4_val5),
    .h_5_val(h_5_val6),
    .h_6_val(h_6_val7),
    .h_7_val(h_7_val8),
    .flip_mask(flip_mask),
    .ap_return(terms_selected_field_fu_928_ap_return),
    .ap_rst(ap_rst)
);

local_spin_flip_operation_tree_sum_9_s grp_tree_sum_9_s_fu_949(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tree_sum_9_s_fu_949_ap_start),
    .ap_done(grp_tree_sum_9_s_fu_949_ap_done),
    .ap_idle(grp_tree_sum_9_s_fu_949_ap_idle),
    .ap_ready(grp_tree_sum_9_s_fu_949_ap_ready),
    .x_0_val(terms_reg_3105),
    .x_1_val(terms_1_reg_3110),
    .x_2_val(terms_2_reg_3115),
    .x_3_val(terms_3_reg_3120),
    .x_4_val(terms_4_reg_3125),
    .x_5_val(terms_5_reg_3130),
    .x_6_val(terms_6_reg_3135),
    .x_7_val(terms_7_reg_3140),
    .x_8_val(terms_8_reg_3145),
    .ap_return(grp_tree_sum_9_s_fu_949_ap_return)
);

local_spin_flip_operation_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U66(
    .din0(ref_tmp4_assign_s_spin_value_fu_888_ap_return),
    .din1(selected_Jij_reg_2868),
    .dout(mul_ln204_fu_974_p2)
);

local_spin_flip_operation_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U67(
    .din0(ref_tmp4_assign_1_spin_value_fu_893_ap_return),
    .din1(selected_Jij_1_reg_2873),
    .dout(mul_ln204_1_fu_1030_p2)
);

local_spin_flip_operation_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U68(
    .din0(ref_tmp4_assign_2_spin_value_fu_898_ap_return),
    .din1(selected_Jij_2_reg_2878),
    .dout(mul_ln204_2_fu_1086_p2)
);

local_spin_flip_operation_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U69(
    .din0(ref_tmp4_assign_3_spin_value_fu_903_ap_return),
    .din1(selected_Jij_3_reg_2883),
    .dout(mul_ln204_3_fu_1142_p2)
);

local_spin_flip_operation_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U70(
    .din0(ref_tmp4_assign_4_spin_value_fu_908_ap_return),
    .din1(selected_Jij_4_reg_2888),
    .dout(mul_ln204_4_fu_1198_p2)
);

local_spin_flip_operation_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U71(
    .din0(ref_tmp4_assign_9_spin_value_fu_913_ap_return),
    .din1(selected_Jij_5_reg_2893),
    .dout(mul_ln204_5_fu_1254_p2)
);

local_spin_flip_operation_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U72(
    .din0(ref_tmp4_assign_8_spin_value_fu_918_ap_return),
    .din1(selected_Jij_6_reg_2898),
    .dout(mul_ln204_6_fu_1310_p2)
);

local_spin_flip_operation_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U73(
    .din0(ref_tmp4_assign_7_spin_value_fu_923_ap_return),
    .din1(selected_Jij_7_reg_2903),
    .dout(mul_ln204_7_fu_1366_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_selected_coupling_for_j_fu_376_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_selected_coupling_for_j_fu_376_ap_start_reg <= 1'b1;
        end else if ((grp_selected_coupling_for_j_fu_376_ap_ready == 1'b1)) begin
            grp_selected_coupling_for_j_fu_376_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_selected_coupling_for_j_fu_440_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_selected_coupling_for_j_fu_440_ap_start_reg <= 1'b1;
        end else if ((grp_selected_coupling_for_j_fu_440_ap_ready == 1'b1)) begin
            grp_selected_coupling_for_j_fu_440_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_selected_coupling_for_j_fu_504_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_selected_coupling_for_j_fu_504_ap_start_reg <= 1'b1;
        end else if ((grp_selected_coupling_for_j_fu_504_ap_ready == 1'b1)) begin
            grp_selected_coupling_for_j_fu_504_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_selected_coupling_for_j_fu_568_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_selected_coupling_for_j_fu_568_ap_start_reg <= 1'b1;
        end else if ((grp_selected_coupling_for_j_fu_568_ap_ready == 1'b1)) begin
            grp_selected_coupling_for_j_fu_568_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_selected_coupling_for_j_fu_632_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_selected_coupling_for_j_fu_632_ap_start_reg <= 1'b1;
        end else if ((grp_selected_coupling_for_j_fu_632_ap_ready == 1'b1)) begin
            grp_selected_coupling_for_j_fu_632_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_selected_coupling_for_j_fu_696_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_selected_coupling_for_j_fu_696_ap_start_reg <= 1'b1;
        end else if ((grp_selected_coupling_for_j_fu_696_ap_ready == 1'b1)) begin
            grp_selected_coupling_for_j_fu_696_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_selected_coupling_for_j_fu_760_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_selected_coupling_for_j_fu_760_ap_start_reg <= 1'b1;
        end else if ((grp_selected_coupling_for_j_fu_760_ap_ready == 1'b1)) begin
            grp_selected_coupling_for_j_fu_760_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_selected_coupling_for_j_fu_824_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_selected_coupling_for_j_fu_824_ap_start_reg <= 1'b1;
        end else if ((grp_selected_coupling_for_j_fu_824_ap_ready == 1'b1)) begin
            grp_selected_coupling_for_j_fu_824_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tree_sum_9_s_fu_949_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_tree_sum_9_s_fu_949_ap_start_reg <= 1'b1;
        end else if ((grp_tree_sum_9_s_fu_949_ap_ready == 1'b1)) begin
            grp_tree_sum_9_s_fu_949_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        field_over_alpha_reg_3150 <= grp_tree_sum_9_s_fu_949_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        selected_Jij_1_reg_2873 <= grp_selected_coupling_for_j_fu_440_ap_return;
        selected_Jij_2_reg_2878 <= grp_selected_coupling_for_j_fu_504_ap_return;
        selected_Jij_3_reg_2883 <= grp_selected_coupling_for_j_fu_568_ap_return;
        selected_Jij_4_reg_2888 <= grp_selected_coupling_for_j_fu_632_ap_return;
        selected_Jij_5_reg_2893 <= grp_selected_coupling_for_j_fu_696_ap_return;
        selected_Jij_6_reg_2898 <= grp_selected_coupling_for_j_fu_760_ap_return;
        selected_Jij_7_reg_2903 <= grp_selected_coupling_for_j_fu_824_ap_return;
        selected_Jij_reg_2868 <= grp_selected_coupling_for_j_fu_376_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        selected_bit_reg_3100 <= selected_bit_fu_1411_p2;
        tmp_25_reg_2921 <= mul_ln204_fu_974_p2[32'd7];
        tmp_26_reg_2926 <= mul_ln204_fu_974_p2[32'd16];
        tmp_29_reg_2932 <= mul_ln204_1_fu_1030_p2[32'd17];
        tmp_30_reg_2945 <= mul_ln204_1_fu_1030_p2[32'd7];
        tmp_31_reg_2950 <= mul_ln204_1_fu_1030_p2[32'd16];
        tmp_34_reg_2956 <= mul_ln204_2_fu_1086_p2[32'd17];
        tmp_35_reg_2969 <= mul_ln204_2_fu_1086_p2[32'd7];
        tmp_36_reg_2974 <= mul_ln204_2_fu_1086_p2[32'd16];
        tmp_39_reg_2980 <= mul_ln204_3_fu_1142_p2[32'd17];
        tmp_40_reg_2993 <= mul_ln204_3_fu_1142_p2[32'd7];
        tmp_41_reg_2998 <= mul_ln204_3_fu_1142_p2[32'd16];
        tmp_44_reg_3004 <= mul_ln204_4_fu_1198_p2[32'd17];
        tmp_45_reg_3017 <= mul_ln204_4_fu_1198_p2[32'd7];
        tmp_46_reg_3022 <= mul_ln204_4_fu_1198_p2[32'd16];
        tmp_49_reg_3028 <= mul_ln204_5_fu_1254_p2[32'd17];
        tmp_50_reg_3041 <= mul_ln204_5_fu_1254_p2[32'd7];
        tmp_51_reg_3046 <= mul_ln204_5_fu_1254_p2[32'd16];
        tmp_54_reg_3052 <= mul_ln204_6_fu_1310_p2[32'd17];
        tmp_55_reg_3065 <= mul_ln204_6_fu_1310_p2[32'd7];
        tmp_56_reg_3070 <= mul_ln204_6_fu_1310_p2[32'd16];
        tmp_59_reg_3076 <= mul_ln204_7_fu_1366_p2[32'd17];
        tmp_60_reg_3089 <= mul_ln204_7_fu_1366_p2[32'd7];
        tmp_61_reg_3094 <= mul_ln204_7_fu_1366_p2[32'd16];
        tmp_reg_2908 <= mul_ln204_fu_974_p2[32'd17];
        trunc_ln204_1_reg_2940 <= {{mul_ln204_1_fu_1030_p2[16:8]}};
        trunc_ln204_2_reg_2964 <= {{mul_ln204_2_fu_1086_p2[16:8]}};
        trunc_ln204_3_reg_2988 <= {{mul_ln204_3_fu_1142_p2[16:8]}};
        trunc_ln204_4_reg_3012 <= {{mul_ln204_4_fu_1198_p2[16:8]}};
        trunc_ln204_5_reg_3036 <= {{mul_ln204_5_fu_1254_p2[16:8]}};
        trunc_ln204_6_reg_3060 <= {{mul_ln204_6_fu_1310_p2[16:8]}};
        trunc_ln204_7_reg_3084 <= {{mul_ln204_7_fu_1366_p2[16:8]}};
        trunc_ln_reg_2916 <= {{mul_ln204_fu_974_p2[16:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        terms_1_reg_3110 <= terms_1_fu_1523_p3;
        terms_2_reg_3115 <= terms_2_fu_1637_p3;
        terms_3_reg_3120 <= terms_3_fu_1751_p3;
        terms_4_reg_3125 <= terms_4_fu_1865_p3;
        terms_5_reg_3130 <= terms_5_fu_1979_p3;
        terms_6_reg_3135 <= terms_6_fu_2093_p3;
        terms_7_reg_3140 <= terms_7_fu_2207_p3;
        terms_8_reg_3145 <= terms_8_fu_2321_p3;
        terms_reg_3105 <= terms_selected_field_fu_928_ap_return;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_tree_sum_9_s_fu_949_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_tree_sum_9_s_fu_949_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln204_1_fu_1534_p2 = (trunc_ln204_1_reg_2940 + zext_ln204_1_fu_1531_p1);

assign add_ln204_2_fu_1648_p2 = (trunc_ln204_2_reg_2964 + zext_ln204_2_fu_1645_p1);

assign add_ln204_3_fu_1762_p2 = (trunc_ln204_3_reg_2988 + zext_ln204_3_fu_1759_p1);

assign add_ln204_4_fu_1876_p2 = (trunc_ln204_4_reg_3012 + zext_ln204_4_fu_1873_p1);

assign add_ln204_5_fu_1990_p2 = (trunc_ln204_5_reg_3036 + zext_ln204_5_fu_1987_p1);

assign add_ln204_6_fu_2104_p2 = (trunc_ln204_6_reg_3060 + zext_ln204_6_fu_2101_p1);

assign add_ln204_7_fu_2218_p2 = (trunc_ln204_7_reg_3084 + zext_ln204_7_fu_2215_p1);

assign add_ln204_fu_1420_p2 = (trunc_ln_reg_2916 + zext_ln204_fu_1417_p1);

assign and_ln204_10_fu_1720_p2 = (tmp_37_fu_1653_p3 & select_ln204_9_fu_1684_p3);

assign and_ln204_11_fu_1732_p2 = (xor_ln204_14_fu_1726_p2 & tmp_34_reg_2956);

assign and_ln204_12_fu_1781_p2 = (xor_ln204_15_fu_1775_p2 & tmp_41_reg_2998);

assign and_ln204_13_fu_1828_p2 = (xor_ln204_16_fu_1786_p2 & or_ln204_10_fu_1822_p2);

assign and_ln204_14_fu_1834_p2 = (tmp_42_fu_1767_p3 & select_ln204_13_fu_1798_p3);

assign and_ln204_15_fu_1846_p2 = (xor_ln204_19_fu_1840_p2 & tmp_39_reg_2980);

assign and_ln204_16_fu_1895_p2 = (xor_ln204_20_fu_1889_p2 & tmp_46_reg_3022);

assign and_ln204_17_fu_1942_p2 = (xor_ln204_21_fu_1900_p2 & or_ln204_13_fu_1936_p2);

assign and_ln204_18_fu_1948_p2 = (tmp_47_fu_1881_p3 & select_ln204_17_fu_1912_p3);

assign and_ln204_19_fu_1960_p2 = (xor_ln204_24_fu_1954_p2 & tmp_44_reg_3004);

assign and_ln204_1_fu_1486_p2 = (xor_ln204_1_fu_1444_p2 & or_ln204_1_fu_1480_p2);

assign and_ln204_20_fu_2009_p2 = (xor_ln204_25_fu_2003_p2 & tmp_51_reg_3046);

assign and_ln204_21_fu_2056_p2 = (xor_ln204_26_fu_2014_p2 & or_ln204_16_fu_2050_p2);

assign and_ln204_22_fu_2062_p2 = (tmp_52_fu_1995_p3 & select_ln204_21_fu_2026_p3);

assign and_ln204_23_fu_2074_p2 = (xor_ln204_29_fu_2068_p2 & tmp_49_reg_3028);

assign and_ln204_24_fu_2123_p2 = (xor_ln204_30_fu_2117_p2 & tmp_56_reg_3070);

assign and_ln204_25_fu_2170_p2 = (xor_ln204_31_fu_2128_p2 & or_ln204_19_fu_2164_p2);

assign and_ln204_26_fu_2176_p2 = (tmp_57_fu_2109_p3 & select_ln204_25_fu_2140_p3);

assign and_ln204_27_fu_2188_p2 = (xor_ln204_34_fu_2182_p2 & tmp_54_reg_3052);

assign and_ln204_28_fu_2237_p2 = (xor_ln204_35_fu_2231_p2 & tmp_61_reg_3094);

assign and_ln204_29_fu_2284_p2 = (xor_ln204_36_fu_2242_p2 & or_ln204_22_fu_2278_p2);

assign and_ln204_2_fu_1492_p2 = (tmp_27_fu_1425_p3 & select_ln204_1_fu_1456_p3);

assign and_ln204_30_fu_2290_p2 = (tmp_62_fu_2223_p3 & select_ln204_29_fu_2254_p3);

assign and_ln204_31_fu_2302_p2 = (xor_ln204_39_fu_2296_p2 & tmp_59_reg_3076);

assign and_ln204_3_fu_1504_p2 = (xor_ln204_4_fu_1498_p2 & tmp_reg_2908);

assign and_ln204_4_fu_1553_p2 = (xor_ln204_5_fu_1547_p2 & tmp_31_reg_2950);

assign and_ln204_5_fu_1600_p2 = (xor_ln204_6_fu_1558_p2 & or_ln204_4_fu_1594_p2);

assign and_ln204_6_fu_1606_p2 = (tmp_32_fu_1539_p3 & select_ln204_5_fu_1570_p3);

assign and_ln204_7_fu_1618_p2 = (xor_ln204_9_fu_1612_p2 & tmp_29_reg_2932);

assign and_ln204_8_fu_1667_p2 = (xor_ln204_10_fu_1661_p2 & tmp_36_reg_2974);

assign and_ln204_9_fu_1714_p2 = (xor_ln204_11_fu_1672_p2 & or_ln204_7_fu_1708_p2);

assign and_ln204_fu_1439_p2 = (xor_ln204_fu_1433_p2 & tmp_26_reg_2926);

assign and_ln209_1_fu_2376_p2 = (xor_ln209_1_fu_2370_p2 & tmp_63_fu_2342_p3);

assign and_ln209_fu_2364_p2 = (xor_ln209_fu_2358_p2 & tmp_64_fu_2350_p3);

assign and_ln212_fu_1406_p2 = (spins & flip_mask);

assign and_ln214_1_fu_2470_p2 = (xor_ln214_1_fu_2464_p2 & tmp_65_fu_2436_p3);

assign and_ln214_fu_2458_p2 = (xor_ln214_fu_2452_p2 & tmp_66_fu_2444_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_selected_coupling_for_j_fu_824_ap_done == 1'b0) | (grp_selected_coupling_for_j_fu_760_ap_done == 1'b0) | (grp_selected_coupling_for_j_fu_696_ap_done == 1'b0) | (grp_selected_coupling_for_j_fu_632_ap_done == 1'b0) | (grp_selected_coupling_for_j_fu_568_ap_done == 1'b0) | (grp_selected_coupling_for_j_fu_504_ap_done == 1'b0) | (grp_selected_coupling_for_j_fu_440_ap_done == 1'b0) | (grp_selected_coupling_for_j_fu_376_ap_done == 1'b0));
end

assign ap_return = ((or_ln214_fu_2488_p2[0:0] == 1'b1) ? select_ln214_fu_2494_p3 : select_ln214_1_fu_2502_p3);

assign grp_selected_coupling_for_j_fu_376_ap_start = grp_selected_coupling_for_j_fu_376_ap_start_reg;

assign grp_selected_coupling_for_j_fu_440_ap_start = grp_selected_coupling_for_j_fu_440_ap_start_reg;

assign grp_selected_coupling_for_j_fu_504_ap_start = grp_selected_coupling_for_j_fu_504_ap_start_reg;

assign grp_selected_coupling_for_j_fu_568_ap_start = grp_selected_coupling_for_j_fu_568_ap_start_reg;

assign grp_selected_coupling_for_j_fu_632_ap_start = grp_selected_coupling_for_j_fu_632_ap_start_reg;

assign grp_selected_coupling_for_j_fu_696_ap_start = grp_selected_coupling_for_j_fu_696_ap_start_reg;

assign grp_selected_coupling_for_j_fu_760_ap_start = grp_selected_coupling_for_j_fu_760_ap_start_reg;

assign grp_selected_coupling_for_j_fu_824_ap_start = grp_selected_coupling_for_j_fu_824_ap_start_reg;

assign grp_tree_sum_9_s_fu_949_ap_start = grp_tree_sum_9_s_fu_949_ap_start_reg;

assign neg_field_over_alpha_fu_2338_p1 = sub_ln209_fu_2332_p2[8:0];

assign or_ln204_10_fu_1822_p2 = (xor_ln204_18_fu_1816_p2 | tmp_42_fu_1767_p3);

assign or_ln204_11_fu_1859_p2 = (and_ln204_15_fu_1846_p2 | and_ln204_13_fu_1828_p2);

assign or_ln204_12_fu_1924_p2 = (xor_ln204_22_fu_1919_p2 | tmp_47_fu_1881_p3);

assign or_ln204_13_fu_1936_p2 = (xor_ln204_23_fu_1930_p2 | tmp_47_fu_1881_p3);

assign or_ln204_14_fu_1973_p2 = (and_ln204_19_fu_1960_p2 | and_ln204_17_fu_1942_p2);

assign or_ln204_15_fu_2038_p2 = (xor_ln204_27_fu_2033_p2 | tmp_52_fu_1995_p3);

assign or_ln204_16_fu_2050_p2 = (xor_ln204_28_fu_2044_p2 | tmp_52_fu_1995_p3);

assign or_ln204_17_fu_2087_p2 = (and_ln204_23_fu_2074_p2 | and_ln204_21_fu_2056_p2);

assign or_ln204_18_fu_2152_p2 = (xor_ln204_32_fu_2147_p2 | tmp_57_fu_2109_p3);

assign or_ln204_19_fu_2164_p2 = (xor_ln204_33_fu_2158_p2 | tmp_57_fu_2109_p3);

assign or_ln204_1_fu_1480_p2 = (xor_ln204_3_fu_1474_p2 | tmp_27_fu_1425_p3);

assign or_ln204_20_fu_2201_p2 = (and_ln204_27_fu_2188_p2 | and_ln204_25_fu_2170_p2);

assign or_ln204_21_fu_2266_p2 = (xor_ln204_37_fu_2261_p2 | tmp_62_fu_2223_p3);

assign or_ln204_22_fu_2278_p2 = (xor_ln204_38_fu_2272_p2 | tmp_62_fu_2223_p3);

assign or_ln204_23_fu_2315_p2 = (and_ln204_31_fu_2302_p2 | and_ln204_29_fu_2284_p2);

assign or_ln204_2_fu_1517_p2 = (and_ln204_3_fu_1504_p2 | and_ln204_1_fu_1486_p2);

assign or_ln204_3_fu_1582_p2 = (xor_ln204_7_fu_1577_p2 | tmp_32_fu_1539_p3);

assign or_ln204_4_fu_1594_p2 = (xor_ln204_8_fu_1588_p2 | tmp_32_fu_1539_p3);

assign or_ln204_5_fu_1631_p2 = (and_ln204_7_fu_1618_p2 | and_ln204_5_fu_1600_p2);

assign or_ln204_6_fu_1696_p2 = (xor_ln204_12_fu_1691_p2 | tmp_37_fu_1653_p3);

assign or_ln204_7_fu_1708_p2 = (xor_ln204_13_fu_1702_p2 | tmp_37_fu_1653_p3);

assign or_ln204_8_fu_1745_p2 = (and_ln204_9_fu_1714_p2 | and_ln204_11_fu_1732_p2);

assign or_ln204_9_fu_1810_p2 = (xor_ln204_17_fu_1805_p2 | tmp_42_fu_1767_p3);

assign or_ln204_fu_1468_p2 = (xor_ln204_2_fu_1463_p2 | tmp_27_fu_1425_p3);

assign or_ln209_fu_2394_p2 = (xor_ln209_3_fu_2388_p2 | and_ln209_fu_2364_p2);

assign or_ln214_fu_2488_p2 = (xor_ln214_3_fu_2482_p2 | and_ln214_fu_2458_p2);

assign ref_tmp4_assign_1_spin_value_fu_893_b = spins[32'd1];

assign ref_tmp4_assign_2_spin_value_fu_898_b = spins[32'd2];

assign ref_tmp4_assign_3_spin_value_fu_903_b = spins[32'd3];

assign ref_tmp4_assign_4_spin_value_fu_908_b = spins[32'd4];

assign ref_tmp4_assign_7_spin_value_fu_923_b = spins[32'd7];

assign ref_tmp4_assign_8_spin_value_fu_918_b = spins[32'd6];

assign ref_tmp4_assign_9_spin_value_fu_913_b = spins[32'd5];

assign ref_tmp4_assign_s_spin_value_fu_888_b = spins[0:0];

assign select_ln204_10_fu_1737_p3 = ((and_ln204_9_fu_1714_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln204_12_fu_1791_p3 = ((and_ln204_12_fu_1781_p2[0:0] == 1'b1) ? tmp_39_reg_2980 : xor_ln204_16_fu_1786_p2);

assign select_ln204_13_fu_1798_p3 = ((and_ln204_12_fu_1781_p2[0:0] == 1'b1) ? xor_ln204_16_fu_1786_p2 : tmp_39_reg_2980);

assign select_ln204_14_fu_1851_p3 = ((and_ln204_13_fu_1828_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln204_16_fu_1905_p3 = ((and_ln204_16_fu_1895_p2[0:0] == 1'b1) ? tmp_44_reg_3004 : xor_ln204_21_fu_1900_p2);

assign select_ln204_17_fu_1912_p3 = ((and_ln204_16_fu_1895_p2[0:0] == 1'b1) ? xor_ln204_21_fu_1900_p2 : tmp_44_reg_3004);

assign select_ln204_18_fu_1965_p3 = ((and_ln204_17_fu_1942_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln204_1_fu_1456_p3 = ((and_ln204_fu_1439_p2[0:0] == 1'b1) ? xor_ln204_1_fu_1444_p2 : tmp_reg_2908);

assign select_ln204_20_fu_2019_p3 = ((and_ln204_20_fu_2009_p2[0:0] == 1'b1) ? tmp_49_reg_3028 : xor_ln204_26_fu_2014_p2);

assign select_ln204_21_fu_2026_p3 = ((and_ln204_20_fu_2009_p2[0:0] == 1'b1) ? xor_ln204_26_fu_2014_p2 : tmp_49_reg_3028);

assign select_ln204_22_fu_2079_p3 = ((and_ln204_21_fu_2056_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln204_24_fu_2133_p3 = ((and_ln204_24_fu_2123_p2[0:0] == 1'b1) ? tmp_54_reg_3052 : xor_ln204_31_fu_2128_p2);

assign select_ln204_25_fu_2140_p3 = ((and_ln204_24_fu_2123_p2[0:0] == 1'b1) ? xor_ln204_31_fu_2128_p2 : tmp_54_reg_3052);

assign select_ln204_26_fu_2193_p3 = ((and_ln204_25_fu_2170_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln204_28_fu_2247_p3 = ((and_ln204_28_fu_2237_p2[0:0] == 1'b1) ? tmp_59_reg_3076 : xor_ln204_36_fu_2242_p2);

assign select_ln204_29_fu_2254_p3 = ((and_ln204_28_fu_2237_p2[0:0] == 1'b1) ? xor_ln204_36_fu_2242_p2 : tmp_59_reg_3076);

assign select_ln204_2_fu_1509_p3 = ((and_ln204_1_fu_1486_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln204_30_fu_2307_p3 = ((and_ln204_29_fu_2284_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln204_4_fu_1563_p3 = ((and_ln204_4_fu_1553_p2[0:0] == 1'b1) ? tmp_29_reg_2932 : xor_ln204_6_fu_1558_p2);

assign select_ln204_5_fu_1570_p3 = ((and_ln204_4_fu_1553_p2[0:0] == 1'b1) ? xor_ln204_6_fu_1558_p2 : tmp_29_reg_2932);

assign select_ln204_6_fu_1623_p3 = ((and_ln204_5_fu_1600_p2[0:0] == 1'b1) ? 9'd255 : 9'd256);

assign select_ln204_8_fu_1677_p3 = ((and_ln204_8_fu_1667_p2[0:0] == 1'b1) ? tmp_34_reg_2956 : xor_ln204_11_fu_1672_p2);

assign select_ln204_9_fu_1684_p3 = ((and_ln204_8_fu_1667_p2[0:0] == 1'b1) ? xor_ln204_11_fu_1672_p2 : tmp_34_reg_2956);

assign select_ln204_fu_1449_p3 = ((and_ln204_fu_1439_p2[0:0] == 1'b1) ? tmp_reg_2908 : xor_ln204_1_fu_1444_p2);

assign select_ln209_1_fu_2408_p3 = ((and_ln209_1_fu_2376_p2[0:0] == 1'b1) ? 9'd256 : neg_field_over_alpha_fu_2338_p1);

assign select_ln209_2_fu_2416_p3 = ((or_ln209_fu_2394_p2[0:0] == 1'b1) ? select_ln209_fu_2400_p3 : select_ln209_1_fu_2408_p3);

assign select_ln209_fu_2400_p3 = ((xor_ln209_2_fu_2382_p2[0:0] == 1'b1) ? 9'd255 : neg_field_over_alpha_fu_2338_p1);

assign select_ln214_1_fu_2502_p3 = ((and_ln214_1_fu_2470_p2[0:0] == 1'b1) ? 9'd256 : shl_ln214_fu_2430_p2);

assign select_ln214_fu_2494_p3 = ((xor_ln214_2_fu_2476_p2[0:0] == 1'b1) ? 9'd255 : shl_ln214_fu_2430_p2);

assign selected_bit_fu_1411_p2 = ((and_ln212_fu_1406_p2 != 8'd0) ? 1'b1 : 1'b0);

assign sext_ln209_fu_2329_p1 = field_over_alpha_reg_3150;

assign shl_ln214_fu_2430_p2 = signed_field_fu_2424_p3 << 9'd1;

assign signed_field_fu_2424_p3 = ((selected_bit_reg_3100[0:0] == 1'b1) ? field_over_alpha_reg_3150 : select_ln209_2_fu_2416_p3);

assign sub_ln209_fu_2332_p2 = ($signed(10'd0) - $signed(sext_ln209_fu_2329_p1));

assign terms_1_fu_1523_p3 = ((or_ln204_2_fu_1517_p2[0:0] == 1'b1) ? select_ln204_2_fu_1509_p3 : add_ln204_fu_1420_p2);

assign terms_2_fu_1637_p3 = ((or_ln204_5_fu_1631_p2[0:0] == 1'b1) ? select_ln204_6_fu_1623_p3 : add_ln204_1_fu_1534_p2);

assign terms_3_fu_1751_p3 = ((or_ln204_8_fu_1745_p2[0:0] == 1'b1) ? select_ln204_10_fu_1737_p3 : add_ln204_2_fu_1648_p2);

assign terms_4_fu_1865_p3 = ((or_ln204_11_fu_1859_p2[0:0] == 1'b1) ? select_ln204_14_fu_1851_p3 : add_ln204_3_fu_1762_p2);

assign terms_5_fu_1979_p3 = ((or_ln204_14_fu_1973_p2[0:0] == 1'b1) ? select_ln204_18_fu_1965_p3 : add_ln204_4_fu_1876_p2);

assign terms_6_fu_2093_p3 = ((or_ln204_17_fu_2087_p2[0:0] == 1'b1) ? select_ln204_22_fu_2079_p3 : add_ln204_5_fu_1990_p2);

assign terms_7_fu_2207_p3 = ((or_ln204_20_fu_2201_p2[0:0] == 1'b1) ? select_ln204_26_fu_2193_p3 : add_ln204_6_fu_2104_p2);

assign terms_8_fu_2321_p3 = ((or_ln204_23_fu_2315_p2[0:0] == 1'b1) ? select_ln204_30_fu_2307_p3 : add_ln204_7_fu_2218_p2);

assign tmp_27_fu_1425_p3 = add_ln204_fu_1420_p2[32'd8];

assign tmp_32_fu_1539_p3 = add_ln204_1_fu_1534_p2[32'd8];

assign tmp_37_fu_1653_p3 = add_ln204_2_fu_1648_p2[32'd8];

assign tmp_42_fu_1767_p3 = add_ln204_3_fu_1762_p2[32'd8];

assign tmp_47_fu_1881_p3 = add_ln204_4_fu_1876_p2[32'd8];

assign tmp_52_fu_1995_p3 = add_ln204_5_fu_1990_p2[32'd8];

assign tmp_57_fu_2109_p3 = add_ln204_6_fu_2104_p2[32'd8];

assign tmp_62_fu_2223_p3 = add_ln204_7_fu_2218_p2[32'd8];

assign tmp_63_fu_2342_p3 = sub_ln209_fu_2332_p2[32'd9];

assign tmp_64_fu_2350_p3 = sub_ln209_fu_2332_p2[32'd8];

assign tmp_65_fu_2436_p3 = signed_field_fu_2424_p3[32'd8];

assign tmp_66_fu_2444_p3 = signed_field_fu_2424_p3[32'd7];

assign xor_ln204_10_fu_1661_p2 = (tmp_37_fu_1653_p3 ^ 1'd1);

assign xor_ln204_11_fu_1672_p2 = (tmp_34_reg_2956 ^ 1'd1);

assign xor_ln204_12_fu_1691_p2 = (tmp_36_reg_2974 ^ 1'd1);

assign xor_ln204_13_fu_1702_p2 = (select_ln204_8_fu_1677_p3 ^ 1'd1);

assign xor_ln204_14_fu_1726_p2 = (or_ln204_6_fu_1696_p2 ^ and_ln204_10_fu_1720_p2);

assign xor_ln204_15_fu_1775_p2 = (tmp_42_fu_1767_p3 ^ 1'd1);

assign xor_ln204_16_fu_1786_p2 = (tmp_39_reg_2980 ^ 1'd1);

assign xor_ln204_17_fu_1805_p2 = (tmp_41_reg_2998 ^ 1'd1);

assign xor_ln204_18_fu_1816_p2 = (select_ln204_12_fu_1791_p3 ^ 1'd1);

assign xor_ln204_19_fu_1840_p2 = (or_ln204_9_fu_1810_p2 ^ and_ln204_14_fu_1834_p2);

assign xor_ln204_1_fu_1444_p2 = (tmp_reg_2908 ^ 1'd1);

assign xor_ln204_20_fu_1889_p2 = (tmp_47_fu_1881_p3 ^ 1'd1);

assign xor_ln204_21_fu_1900_p2 = (tmp_44_reg_3004 ^ 1'd1);

assign xor_ln204_22_fu_1919_p2 = (tmp_46_reg_3022 ^ 1'd1);

assign xor_ln204_23_fu_1930_p2 = (select_ln204_16_fu_1905_p3 ^ 1'd1);

assign xor_ln204_24_fu_1954_p2 = (or_ln204_12_fu_1924_p2 ^ and_ln204_18_fu_1948_p2);

assign xor_ln204_25_fu_2003_p2 = (tmp_52_fu_1995_p3 ^ 1'd1);

assign xor_ln204_26_fu_2014_p2 = (tmp_49_reg_3028 ^ 1'd1);

assign xor_ln204_27_fu_2033_p2 = (tmp_51_reg_3046 ^ 1'd1);

assign xor_ln204_28_fu_2044_p2 = (select_ln204_20_fu_2019_p3 ^ 1'd1);

assign xor_ln204_29_fu_2068_p2 = (or_ln204_15_fu_2038_p2 ^ and_ln204_22_fu_2062_p2);

assign xor_ln204_2_fu_1463_p2 = (tmp_26_reg_2926 ^ 1'd1);

assign xor_ln204_30_fu_2117_p2 = (tmp_57_fu_2109_p3 ^ 1'd1);

assign xor_ln204_31_fu_2128_p2 = (tmp_54_reg_3052 ^ 1'd1);

assign xor_ln204_32_fu_2147_p2 = (tmp_56_reg_3070 ^ 1'd1);

assign xor_ln204_33_fu_2158_p2 = (select_ln204_24_fu_2133_p3 ^ 1'd1);

assign xor_ln204_34_fu_2182_p2 = (or_ln204_18_fu_2152_p2 ^ and_ln204_26_fu_2176_p2);

assign xor_ln204_35_fu_2231_p2 = (tmp_62_fu_2223_p3 ^ 1'd1);

assign xor_ln204_36_fu_2242_p2 = (tmp_59_reg_3076 ^ 1'd1);

assign xor_ln204_37_fu_2261_p2 = (tmp_61_reg_3094 ^ 1'd1);

assign xor_ln204_38_fu_2272_p2 = (select_ln204_28_fu_2247_p3 ^ 1'd1);

assign xor_ln204_39_fu_2296_p2 = (or_ln204_21_fu_2266_p2 ^ and_ln204_30_fu_2290_p2);

assign xor_ln204_3_fu_1474_p2 = (select_ln204_fu_1449_p3 ^ 1'd1);

assign xor_ln204_4_fu_1498_p2 = (or_ln204_fu_1468_p2 ^ and_ln204_2_fu_1492_p2);

assign xor_ln204_5_fu_1547_p2 = (tmp_32_fu_1539_p3 ^ 1'd1);

assign xor_ln204_6_fu_1558_p2 = (tmp_29_reg_2932 ^ 1'd1);

assign xor_ln204_7_fu_1577_p2 = (tmp_31_reg_2950 ^ 1'd1);

assign xor_ln204_8_fu_1588_p2 = (select_ln204_4_fu_1563_p3 ^ 1'd1);

assign xor_ln204_9_fu_1612_p2 = (or_ln204_3_fu_1582_p2 ^ and_ln204_6_fu_1606_p2);

assign xor_ln204_fu_1433_p2 = (tmp_27_fu_1425_p3 ^ 1'd1);

assign xor_ln209_1_fu_2370_p2 = (tmp_64_fu_2350_p3 ^ 1'd1);

assign xor_ln209_2_fu_2382_p2 = (tmp_64_fu_2350_p3 ^ tmp_63_fu_2342_p3);

assign xor_ln209_3_fu_2388_p2 = (xor_ln209_2_fu_2382_p2 ^ 1'd1);

assign xor_ln209_fu_2358_p2 = (tmp_63_fu_2342_p3 ^ 1'd1);

assign xor_ln214_1_fu_2464_p2 = (tmp_66_fu_2444_p3 ^ 1'd1);

assign xor_ln214_2_fu_2476_p2 = (tmp_66_fu_2444_p3 ^ tmp_65_fu_2436_p3);

assign xor_ln214_3_fu_2482_p2 = (xor_ln214_2_fu_2476_p2 ^ 1'd1);

assign xor_ln214_fu_2452_p2 = (tmp_65_fu_2436_p3 ^ 1'd1);

assign zext_ln204_1_fu_1531_p1 = tmp_30_reg_2945;

assign zext_ln204_2_fu_1645_p1 = tmp_35_reg_2969;

assign zext_ln204_3_fu_1759_p1 = tmp_40_reg_2993;

assign zext_ln204_4_fu_1873_p1 = tmp_45_reg_3017;

assign zext_ln204_5_fu_1987_p1 = tmp_50_reg_3041;

assign zext_ln204_6_fu_2101_p1 = tmp_55_reg_3065;

assign zext_ln204_7_fu_2215_p1 = tmp_60_reg_3089;

assign zext_ln204_fu_1417_p1 = tmp_25_reg_2921;

endmodule //local_spin_flip_operation_local_delta_over_alpha
